SELECT "CUSTOMER"."C_CUSTOMER_ID"
FROM (SELECT "STORE_RETURNS"."SR_CUSTOMER_SK" AS "SR_CUSTOMER_SK0", "STORE_RETURNS"."SR_STORE_SK" AS "SR_STORE_SK0", SUM("STORE_RETURNS"."SR_RETURN_AMT_INC_TAX") AS "$f2"
FROM "tpcds"."STORE_RETURNS",
"tpcds"."DATE_DIM"
WHERE "STORE_RETURNS"."SR_RETURNED_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_YEAR" = 2001
GROUP BY "STORE_RETURNS"."SR_CUSTOMER_SK", "STORE_RETURNS"."SR_STORE_SK") AS "t1",
"tpcds"."STORE",
"tpcds"."CUSTOMER"
WHERE CAST("t1"."$f2" AS DECIMAL(9, 3)) > (((SELECT AVG(SUM("STORE_RETURNS0"."SR_RETURN_AMT_INC_TAX")) * 1.2 AS "$f1"
FROM "tpcds"."STORE_RETURNS" AS "STORE_RETURNS0",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "STORE_RETURNS0"."SR_RETURNED_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_YEAR" = 2001
GROUP BY "STORE_RETURNS0"."SR_CUSTOMER_SK", "STORE_RETURNS0"."SR_STORE_SK"
HAVING "t1"."SR_STORE_SK0" = "STORE_RETURNS0"."SR_STORE_SK"))) AND "STORE"."S_STORE_SK" = "t1"."SR_STORE_SK0" AND "STORE"."S_STATE" = 'distmember(fips_county, 61, 3)' AND "t1"."SR_CUSTOMER_SK0" = "CUSTOMER"."C_CUSTOMER_SK"
ORDER BY "CUSTOMER"."C_CUSTOMER_ID"
FETCH NEXT 100 ROWS ONLY
