SELECT "t6"."D_WEEK_SEQ00" AS "D_WEEK_SEQ1", ROUND("t6"."$f10" / "t14"."$f10", 2), ROUND("t6"."$f20" / "t14"."$f20", 2), ROUND("t6"."$f30" / "t14"."$f30", 2), ROUND("t6"."$f40" / "t14"."$f40", 2), ROUND("t6"."$f50" / "t14"."$f50", 2), ROUND("t6"."$f60" / "t14"."$f60", 2), ROUND("t6"."$f70" / "t14"."$f70", 2)
FROM (SELECT "t4"."D_WEEK_SEQ0" AS "D_WEEK_SEQ00", "t4"."$f1" AS "$f10", "t4"."$f2" AS "$f20", "t4"."$f3" AS "$f30", "t4"."$f4" AS "$f40", "t4"."$f5" AS "$f50", "t4"."$f6" AS "$f60", "t4"."$f7" AS "$f70"
FROM (SELECT "DATE_DIM"."D_WEEK_SEQ" AS "D_WEEK_SEQ0", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Sunday' THEN CAST("t1"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f1", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Monday' THEN CAST("t1"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f2", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Tuesday' THEN CAST("t1"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f3", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Wednesday' THEN CAST("t1"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f4", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Thursday' THEN CAST("t1"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f5", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Friday' THEN CAST("t1"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f6", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Saturday' THEN CAST("t1"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f7"
FROM (SELECT "WS_SOLD_DATE_SK" AS "WS_SOLD_DATE_SK0", "WS_EXT_SALES_PRICE" AS "WS_EXT_SALES_PRICE0"
FROM "tpcds"."WEB_SALES"
UNION ALL
SELECT "CS_SOLD_DATE_SK" AS "CS_SOLD_DATE_SK0", "CS_EXT_SALES_PRICE" AS "CS_EXT_SALES_PRICE0"
FROM "tpcds"."CATALOG_SALES") AS "t1",
"tpcds"."DATE_DIM"
WHERE "DATE_DIM"."D_DATE_SK" = "t1"."WS_SOLD_DATE_SK0"
GROUP BY "DATE_DIM"."D_WEEK_SEQ") AS "t4",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "DATE_DIM0"."D_WEEK_SEQ" = "t4"."D_WEEK_SEQ0" AND "DATE_DIM0"."D_YEAR" = 2001) AS "t6",
(SELECT "t12"."D_WEEK_SEQ0" AS "D_WEEK_SEQ00", "t12"."$f1" AS "$f10", "t12"."$f2" AS "$f20", "t12"."$f3" AS "$f30", "t12"."$f4" AS "$f40", "t12"."$f5" AS "$f50", "t12"."$f6" AS "$f60", "t12"."$f7" AS "$f70"
FROM (SELECT "DATE_DIM1"."D_WEEK_SEQ" AS "D_WEEK_SEQ0", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Sunday' THEN CAST("t9"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f1", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Monday' THEN CAST("t9"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f2", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Tuesday' THEN CAST("t9"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f3", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Wednesday' THEN CAST("t9"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f4", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Thursday' THEN CAST("t9"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f5", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Friday' THEN CAST("t9"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f6", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Saturday' THEN CAST("t9"."WS_EXT_SALES_PRICE0" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f7"
FROM (SELECT "WS_SOLD_DATE_SK" AS "WS_SOLD_DATE_SK0", "WS_EXT_SALES_PRICE" AS "WS_EXT_SALES_PRICE0"
FROM "tpcds"."WEB_SALES"
UNION ALL
SELECT "CS_SOLD_DATE_SK" AS "CS_SOLD_DATE_SK0", "CS_EXT_SALES_PRICE" AS "CS_EXT_SALES_PRICE0"
FROM "tpcds"."CATALOG_SALES") AS "t9",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "DATE_DIM1"."D_DATE_SK" = "t9"."WS_SOLD_DATE_SK0"
GROUP BY "DATE_DIM1"."D_WEEK_SEQ") AS "t12",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "DATE_DIM2"."D_WEEK_SEQ" = "t12"."D_WEEK_SEQ0" AND "DATE_DIM2"."D_YEAR" = 2001 + 1) AS "t14"
WHERE "t6"."D_WEEK_SEQ00" = "t14"."D_WEEK_SEQ00" - 53
ORDER BY "t6"."D_WEEK_SEQ00"
