SELECT "t26"."C_LOGIN00" AS "CUSTOMER_LOGIN"
FROM (SELECT *
FROM (SELECT "CUSTOMER"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM"."D_YEAR" AS "D_YEAR00", SUM(("STORE_SALES"."SS_EXT_LIST_PRICE" - "STORE_SALES"."SS_EXT_WHOLESALE_COST" - "STORE_SALES"."SS_EXT_DISCOUNT_AMT" + "STORE_SALES"."SS_EXT_SALES_PRICE") / 2.00) AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER",
"tpcds"."STORE_SALES",
"tpcds"."DATE_DIM"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "STORE_SALES"."SS_CUSTOMER_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK"
GROUP BY "CUSTOMER"."C_CUSTOMER_ID", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_PREFERRED_CUST_FLAG", "CUSTOMER"."C_BIRTH_COUNTRY", "CUSTOMER"."C_LOGIN", "CUSTOMER"."C_EMAIL_ADDRESS", "DATE_DIM"."D_YEAR"
UNION ALL
SELECT "CUSTOMER0"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER0"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER0"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER0"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER0"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER0"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER0"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM0"."D_YEAR" AS "D_YEAR00", SUM(("CATALOG_SALES"."CS_EXT_LIST_PRICE" - "CATALOG_SALES"."CS_EXT_WHOLESALE_COST" - "CATALOG_SALES"."CS_EXT_DISCOUNT_AMT" + "CATALOG_SALES"."CS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'c' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER0",
"tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "CUSTOMER0"."C_CUSTOMER_SK" = "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK"
GROUP BY "CUSTOMER0"."C_CUSTOMER_ID", "CUSTOMER0"."C_FIRST_NAME", "CUSTOMER0"."C_LAST_NAME", "CUSTOMER0"."C_PREFERRED_CUST_FLAG", "CUSTOMER0"."C_BIRTH_COUNTRY", "CUSTOMER0"."C_LOGIN", "CUSTOMER0"."C_EMAIL_ADDRESS", "DATE_DIM0"."D_YEAR")
UNION ALL
SELECT "CUSTOMER1"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER1"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER1"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER1"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER1"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER1"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER1"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM1"."D_YEAR" AS "D_YEAR00", SUM(("WEB_SALES"."WS_EXT_LIST_PRICE" - "WEB_SALES"."WS_EXT_WHOLESALE_COST" - "WEB_SALES"."WS_EXT_DISCOUNT_AMT" + "WEB_SALES"."WS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER1",
"tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "CUSTOMER1"."C_CUSTOMER_SK" = "WEB_SALES"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK"
GROUP BY "CUSTOMER1"."C_CUSTOMER_ID", "CUSTOMER1"."C_FIRST_NAME", "CUSTOMER1"."C_LAST_NAME", "CUSTOMER1"."C_PREFERRED_CUST_FLAG", "CUSTOMER1"."C_BIRTH_COUNTRY", "CUSTOMER1"."C_LOGIN", "CUSTOMER1"."C_EMAIL_ADDRESS", "DATE_DIM1"."D_YEAR") AS "t12",
(SELECT *
FROM (SELECT "CUSTOMER2"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER2"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER2"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER2"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER2"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER2"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER2"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM2"."D_YEAR" AS "D_YEAR00", SUM(("STORE_SALES0"."SS_EXT_LIST_PRICE" - "STORE_SALES0"."SS_EXT_WHOLESALE_COST" - "STORE_SALES0"."SS_EXT_DISCOUNT_AMT" + "STORE_SALES0"."SS_EXT_SALES_PRICE") / 2.00) AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER2",
"tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "CUSTOMER2"."C_CUSTOMER_SK" = "STORE_SALES0"."SS_CUSTOMER_SK" AND "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM2"."D_DATE_SK"
GROUP BY "CUSTOMER2"."C_CUSTOMER_ID", "CUSTOMER2"."C_FIRST_NAME", "CUSTOMER2"."C_LAST_NAME", "CUSTOMER2"."C_PREFERRED_CUST_FLAG", "CUSTOMER2"."C_BIRTH_COUNTRY", "CUSTOMER2"."C_LOGIN", "CUSTOMER2"."C_EMAIL_ADDRESS", "DATE_DIM2"."D_YEAR"
UNION ALL
SELECT "CUSTOMER3"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER3"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER3"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER3"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER3"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER3"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER3"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM3"."D_YEAR" AS "D_YEAR00", SUM(("CATALOG_SALES0"."CS_EXT_LIST_PRICE" - "CATALOG_SALES0"."CS_EXT_WHOLESALE_COST" - "CATALOG_SALES0"."CS_EXT_DISCOUNT_AMT" + "CATALOG_SALES0"."CS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'c' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER3",
"tpcds"."CATALOG_SALES" AS "CATALOG_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM3"
WHERE "CUSTOMER3"."C_CUSTOMER_SK" = "CATALOG_SALES0"."CS_BILL_CUSTOMER_SK" AND "CATALOG_SALES0"."CS_SOLD_DATE_SK" = "DATE_DIM3"."D_DATE_SK"
GROUP BY "CUSTOMER3"."C_CUSTOMER_ID", "CUSTOMER3"."C_FIRST_NAME", "CUSTOMER3"."C_LAST_NAME", "CUSTOMER3"."C_PREFERRED_CUST_FLAG", "CUSTOMER3"."C_BIRTH_COUNTRY", "CUSTOMER3"."C_LOGIN", "CUSTOMER3"."C_EMAIL_ADDRESS", "DATE_DIM3"."D_YEAR")
UNION ALL
SELECT "CUSTOMER4"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER4"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER4"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER4"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER4"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER4"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER4"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM4"."D_YEAR" AS "D_YEAR00", SUM(("WEB_SALES0"."WS_EXT_LIST_PRICE" - "WEB_SALES0"."WS_EXT_WHOLESALE_COST" - "WEB_SALES0"."WS_EXT_DISCOUNT_AMT" + "WEB_SALES0"."WS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER4",
"tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM4"
WHERE "CUSTOMER4"."C_CUSTOMER_SK" = "WEB_SALES0"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES0"."WS_SOLD_DATE_SK" = "DATE_DIM4"."D_DATE_SK"
GROUP BY "CUSTOMER4"."C_CUSTOMER_ID", "CUSTOMER4"."C_FIRST_NAME", "CUSTOMER4"."C_LAST_NAME", "CUSTOMER4"."C_PREFERRED_CUST_FLAG", "CUSTOMER4"."C_BIRTH_COUNTRY", "CUSTOMER4"."C_LOGIN", "CUSTOMER4"."C_EMAIL_ADDRESS", "DATE_DIM4"."D_YEAR") AS "t26",
(SELECT *
FROM (SELECT "CUSTOMER5"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER5"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER5"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER5"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER5"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER5"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER5"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM5"."D_YEAR" AS "D_YEAR00", SUM(("STORE_SALES1"."SS_EXT_LIST_PRICE" - "STORE_SALES1"."SS_EXT_WHOLESALE_COST" - "STORE_SALES1"."SS_EXT_DISCOUNT_AMT" + "STORE_SALES1"."SS_EXT_SALES_PRICE") / 2.00) AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER5",
"tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM5"
WHERE "CUSTOMER5"."C_CUSTOMER_SK" = "STORE_SALES1"."SS_CUSTOMER_SK" AND "STORE_SALES1"."SS_SOLD_DATE_SK" = "DATE_DIM5"."D_DATE_SK"
GROUP BY "CUSTOMER5"."C_CUSTOMER_ID", "CUSTOMER5"."C_FIRST_NAME", "CUSTOMER5"."C_LAST_NAME", "CUSTOMER5"."C_PREFERRED_CUST_FLAG", "CUSTOMER5"."C_BIRTH_COUNTRY", "CUSTOMER5"."C_LOGIN", "CUSTOMER5"."C_EMAIL_ADDRESS", "DATE_DIM5"."D_YEAR"
UNION ALL
SELECT "CUSTOMER6"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER6"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER6"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER6"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER6"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER6"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER6"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM6"."D_YEAR" AS "D_YEAR00", SUM(("CATALOG_SALES1"."CS_EXT_LIST_PRICE" - "CATALOG_SALES1"."CS_EXT_WHOLESALE_COST" - "CATALOG_SALES1"."CS_EXT_DISCOUNT_AMT" + "CATALOG_SALES1"."CS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'c' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER6",
"tpcds"."CATALOG_SALES" AS "CATALOG_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM6"
WHERE "CUSTOMER6"."C_CUSTOMER_SK" = "CATALOG_SALES1"."CS_BILL_CUSTOMER_SK" AND "CATALOG_SALES1"."CS_SOLD_DATE_SK" = "DATE_DIM6"."D_DATE_SK"
GROUP BY "CUSTOMER6"."C_CUSTOMER_ID", "CUSTOMER6"."C_FIRST_NAME", "CUSTOMER6"."C_LAST_NAME", "CUSTOMER6"."C_PREFERRED_CUST_FLAG", "CUSTOMER6"."C_BIRTH_COUNTRY", "CUSTOMER6"."C_LOGIN", "CUSTOMER6"."C_EMAIL_ADDRESS", "DATE_DIM6"."D_YEAR")
UNION ALL
SELECT "CUSTOMER7"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER7"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER7"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER7"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER7"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER7"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER7"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM7"."D_YEAR" AS "D_YEAR00", SUM(("WEB_SALES1"."WS_EXT_LIST_PRICE" - "WEB_SALES1"."WS_EXT_WHOLESALE_COST" - "WEB_SALES1"."WS_EXT_DISCOUNT_AMT" + "WEB_SALES1"."WS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER7",
"tpcds"."WEB_SALES" AS "WEB_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM7"
WHERE "CUSTOMER7"."C_CUSTOMER_SK" = "WEB_SALES1"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES1"."WS_SOLD_DATE_SK" = "DATE_DIM7"."D_DATE_SK"
GROUP BY "CUSTOMER7"."C_CUSTOMER_ID", "CUSTOMER7"."C_FIRST_NAME", "CUSTOMER7"."C_LAST_NAME", "CUSTOMER7"."C_PREFERRED_CUST_FLAG", "CUSTOMER7"."C_BIRTH_COUNTRY", "CUSTOMER7"."C_LOGIN", "CUSTOMER7"."C_EMAIL_ADDRESS", "DATE_DIM7"."D_YEAR") AS "t40",
(SELECT *
FROM (SELECT "CUSTOMER8"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER8"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER8"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER8"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER8"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER8"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER8"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM8"."D_YEAR" AS "D_YEAR00", SUM(("STORE_SALES2"."SS_EXT_LIST_PRICE" - "STORE_SALES2"."SS_EXT_WHOLESALE_COST" - "STORE_SALES2"."SS_EXT_DISCOUNT_AMT" + "STORE_SALES2"."SS_EXT_SALES_PRICE") / 2.00) AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER8",
"tpcds"."STORE_SALES" AS "STORE_SALES2",
"tpcds"."DATE_DIM" AS "DATE_DIM8"
WHERE "CUSTOMER8"."C_CUSTOMER_SK" = "STORE_SALES2"."SS_CUSTOMER_SK" AND "STORE_SALES2"."SS_SOLD_DATE_SK" = "DATE_DIM8"."D_DATE_SK"
GROUP BY "CUSTOMER8"."C_CUSTOMER_ID", "CUSTOMER8"."C_FIRST_NAME", "CUSTOMER8"."C_LAST_NAME", "CUSTOMER8"."C_PREFERRED_CUST_FLAG", "CUSTOMER8"."C_BIRTH_COUNTRY", "CUSTOMER8"."C_LOGIN", "CUSTOMER8"."C_EMAIL_ADDRESS", "DATE_DIM8"."D_YEAR"
UNION ALL
SELECT "CUSTOMER9"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER9"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER9"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER9"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER9"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER9"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER9"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM9"."D_YEAR" AS "D_YEAR00", SUM(("CATALOG_SALES2"."CS_EXT_LIST_PRICE" - "CATALOG_SALES2"."CS_EXT_WHOLESALE_COST" - "CATALOG_SALES2"."CS_EXT_DISCOUNT_AMT" + "CATALOG_SALES2"."CS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'c' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER9",
"tpcds"."CATALOG_SALES" AS "CATALOG_SALES2",
"tpcds"."DATE_DIM" AS "DATE_DIM9"
WHERE "CUSTOMER9"."C_CUSTOMER_SK" = "CATALOG_SALES2"."CS_BILL_CUSTOMER_SK" AND "CATALOG_SALES2"."CS_SOLD_DATE_SK" = "DATE_DIM9"."D_DATE_SK"
GROUP BY "CUSTOMER9"."C_CUSTOMER_ID", "CUSTOMER9"."C_FIRST_NAME", "CUSTOMER9"."C_LAST_NAME", "CUSTOMER9"."C_PREFERRED_CUST_FLAG", "CUSTOMER9"."C_BIRTH_COUNTRY", "CUSTOMER9"."C_LOGIN", "CUSTOMER9"."C_EMAIL_ADDRESS", "DATE_DIM9"."D_YEAR")
UNION ALL
SELECT "CUSTOMER10"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER10"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER10"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER10"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER10"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER10"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER10"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM10"."D_YEAR" AS "D_YEAR00", SUM(("WEB_SALES2"."WS_EXT_LIST_PRICE" - "WEB_SALES2"."WS_EXT_WHOLESALE_COST" - "WEB_SALES2"."WS_EXT_DISCOUNT_AMT" + "WEB_SALES2"."WS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER10",
"tpcds"."WEB_SALES" AS "WEB_SALES2",
"tpcds"."DATE_DIM" AS "DATE_DIM10"
WHERE "CUSTOMER10"."C_CUSTOMER_SK" = "WEB_SALES2"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES2"."WS_SOLD_DATE_SK" = "DATE_DIM10"."D_DATE_SK"
GROUP BY "CUSTOMER10"."C_CUSTOMER_ID", "CUSTOMER10"."C_FIRST_NAME", "CUSTOMER10"."C_LAST_NAME", "CUSTOMER10"."C_PREFERRED_CUST_FLAG", "CUSTOMER10"."C_BIRTH_COUNTRY", "CUSTOMER10"."C_LOGIN", "CUSTOMER10"."C_EMAIL_ADDRESS", "DATE_DIM10"."D_YEAR") AS "t54",
(SELECT *
FROM (SELECT "CUSTOMER11"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER11"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER11"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER11"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER11"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER11"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER11"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM11"."D_YEAR" AS "D_YEAR00", SUM(("STORE_SALES3"."SS_EXT_LIST_PRICE" - "STORE_SALES3"."SS_EXT_WHOLESALE_COST" - "STORE_SALES3"."SS_EXT_DISCOUNT_AMT" + "STORE_SALES3"."SS_EXT_SALES_PRICE") / 2.00) AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER11",
"tpcds"."STORE_SALES" AS "STORE_SALES3",
"tpcds"."DATE_DIM" AS "DATE_DIM11"
WHERE "CUSTOMER11"."C_CUSTOMER_SK" = "STORE_SALES3"."SS_CUSTOMER_SK" AND "STORE_SALES3"."SS_SOLD_DATE_SK" = "DATE_DIM11"."D_DATE_SK"
GROUP BY "CUSTOMER11"."C_CUSTOMER_ID", "CUSTOMER11"."C_FIRST_NAME", "CUSTOMER11"."C_LAST_NAME", "CUSTOMER11"."C_PREFERRED_CUST_FLAG", "CUSTOMER11"."C_BIRTH_COUNTRY", "CUSTOMER11"."C_LOGIN", "CUSTOMER11"."C_EMAIL_ADDRESS", "DATE_DIM11"."D_YEAR"
UNION ALL
SELECT "CUSTOMER12"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER12"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER12"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER12"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER12"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER12"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER12"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM12"."D_YEAR" AS "D_YEAR00", SUM(("CATALOG_SALES3"."CS_EXT_LIST_PRICE" - "CATALOG_SALES3"."CS_EXT_WHOLESALE_COST" - "CATALOG_SALES3"."CS_EXT_DISCOUNT_AMT" + "CATALOG_SALES3"."CS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'c' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER12",
"tpcds"."CATALOG_SALES" AS "CATALOG_SALES3",
"tpcds"."DATE_DIM" AS "DATE_DIM12"
WHERE "CUSTOMER12"."C_CUSTOMER_SK" = "CATALOG_SALES3"."CS_BILL_CUSTOMER_SK" AND "CATALOG_SALES3"."CS_SOLD_DATE_SK" = "DATE_DIM12"."D_DATE_SK"
GROUP BY "CUSTOMER12"."C_CUSTOMER_ID", "CUSTOMER12"."C_FIRST_NAME", "CUSTOMER12"."C_LAST_NAME", "CUSTOMER12"."C_PREFERRED_CUST_FLAG", "CUSTOMER12"."C_BIRTH_COUNTRY", "CUSTOMER12"."C_LOGIN", "CUSTOMER12"."C_EMAIL_ADDRESS", "DATE_DIM12"."D_YEAR")
UNION ALL
SELECT "CUSTOMER13"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER13"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER13"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER13"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER13"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER13"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER13"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM13"."D_YEAR" AS "D_YEAR00", SUM(("WEB_SALES3"."WS_EXT_LIST_PRICE" - "WEB_SALES3"."WS_EXT_WHOLESALE_COST" - "WEB_SALES3"."WS_EXT_DISCOUNT_AMT" + "WEB_SALES3"."WS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER13",
"tpcds"."WEB_SALES" AS "WEB_SALES3",
"tpcds"."DATE_DIM" AS "DATE_DIM13"
WHERE "CUSTOMER13"."C_CUSTOMER_SK" = "WEB_SALES3"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES3"."WS_SOLD_DATE_SK" = "DATE_DIM13"."D_DATE_SK"
GROUP BY "CUSTOMER13"."C_CUSTOMER_ID", "CUSTOMER13"."C_FIRST_NAME", "CUSTOMER13"."C_LAST_NAME", "CUSTOMER13"."C_PREFERRED_CUST_FLAG", "CUSTOMER13"."C_BIRTH_COUNTRY", "CUSTOMER13"."C_LOGIN", "CUSTOMER13"."C_EMAIL_ADDRESS", "DATE_DIM13"."D_YEAR") AS "t68",
(SELECT *
FROM (SELECT "CUSTOMER14"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER14"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER14"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER14"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER14"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER14"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER14"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM14"."D_YEAR" AS "D_YEAR00", SUM(("STORE_SALES4"."SS_EXT_LIST_PRICE" - "STORE_SALES4"."SS_EXT_WHOLESALE_COST" - "STORE_SALES4"."SS_EXT_DISCOUNT_AMT" + "STORE_SALES4"."SS_EXT_SALES_PRICE") / 2.00) AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER14",
"tpcds"."STORE_SALES" AS "STORE_SALES4",
"tpcds"."DATE_DIM" AS "DATE_DIM14"
WHERE "CUSTOMER14"."C_CUSTOMER_SK" = "STORE_SALES4"."SS_CUSTOMER_SK" AND "STORE_SALES4"."SS_SOLD_DATE_SK" = "DATE_DIM14"."D_DATE_SK"
GROUP BY "CUSTOMER14"."C_CUSTOMER_ID", "CUSTOMER14"."C_FIRST_NAME", "CUSTOMER14"."C_LAST_NAME", "CUSTOMER14"."C_PREFERRED_CUST_FLAG", "CUSTOMER14"."C_BIRTH_COUNTRY", "CUSTOMER14"."C_LOGIN", "CUSTOMER14"."C_EMAIL_ADDRESS", "DATE_DIM14"."D_YEAR"
UNION ALL
SELECT "CUSTOMER15"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER15"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER15"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER15"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER15"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER15"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER15"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM15"."D_YEAR" AS "D_YEAR00", SUM(("CATALOG_SALES4"."CS_EXT_LIST_PRICE" - "CATALOG_SALES4"."CS_EXT_WHOLESALE_COST" - "CATALOG_SALES4"."CS_EXT_DISCOUNT_AMT" + "CATALOG_SALES4"."CS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'c' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER15",
"tpcds"."CATALOG_SALES" AS "CATALOG_SALES4",
"tpcds"."DATE_DIM" AS "DATE_DIM15"
WHERE "CUSTOMER15"."C_CUSTOMER_SK" = "CATALOG_SALES4"."CS_BILL_CUSTOMER_SK" AND "CATALOG_SALES4"."CS_SOLD_DATE_SK" = "DATE_DIM15"."D_DATE_SK"
GROUP BY "CUSTOMER15"."C_CUSTOMER_ID", "CUSTOMER15"."C_FIRST_NAME", "CUSTOMER15"."C_LAST_NAME", "CUSTOMER15"."C_PREFERRED_CUST_FLAG", "CUSTOMER15"."C_BIRTH_COUNTRY", "CUSTOMER15"."C_LOGIN", "CUSTOMER15"."C_EMAIL_ADDRESS", "DATE_DIM15"."D_YEAR")
UNION ALL
SELECT "CUSTOMER16"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER16"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER16"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER16"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER16"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER16"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER16"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM16"."D_YEAR" AS "D_YEAR00", SUM(("WEB_SALES4"."WS_EXT_LIST_PRICE" - "WEB_SALES4"."WS_EXT_WHOLESALE_COST" - "WEB_SALES4"."WS_EXT_DISCOUNT_AMT" + "WEB_SALES4"."WS_EXT_SALES_PRICE") / 2.00) AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER16",
"tpcds"."WEB_SALES" AS "WEB_SALES4",
"tpcds"."DATE_DIM" AS "DATE_DIM16"
WHERE "CUSTOMER16"."C_CUSTOMER_SK" = "WEB_SALES4"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES4"."WS_SOLD_DATE_SK" = "DATE_DIM16"."D_DATE_SK"
GROUP BY "CUSTOMER16"."C_CUSTOMER_ID", "CUSTOMER16"."C_FIRST_NAME", "CUSTOMER16"."C_LAST_NAME", "CUSTOMER16"."C_PREFERRED_CUST_FLAG", "CUSTOMER16"."C_BIRTH_COUNTRY", "CUSTOMER16"."C_LOGIN", "CUSTOMER16"."C_EMAIL_ADDRESS", "DATE_DIM16"."D_YEAR") AS "t82"
WHERE "t26"."C_CUSTOMER_ID00" = "t12"."C_CUSTOMER_ID00" AND "t12"."C_CUSTOMER_ID00" = "t54"."C_CUSTOMER_ID00" AND ("t12"."C_CUSTOMER_ID00" = "t40"."C_CUSTOMER_ID00" AND ("t12"."C_CUSTOMER_ID00" = "t68"."C_CUSTOMER_ID00" AND "t12"."C_CUSTOMER_ID00" = "t82"."C_CUSTOMER_ID00")) AND ("t12"."$f18" = 's' AND ("t40"."$f18" = 'c' AND "t68"."$f18" = 'w') AND ("t26"."$f18" = 's' AND ("t54"."$f18" = 'c' AND "t82"."$f18" = 'w'))) AND ("t12"."D_YEAR00" = 2000 AND "t26"."D_YEAR00" = 2000 + 1 AND ("t40"."D_YEAR00" = 2000 AND ("t54"."D_YEAR00" = 2000 + 1 AND "t68"."D_YEAR00" = 2000)) AND ("t82"."D_YEAR00" = 2000 + 1 AND ("t12"."$f80" > 0.000000 AND "t40"."$f80" > 0.000000) AND ("t68"."$f80" > 0.000000 AND (CASE WHEN "t40"."$f80" > 0.000000 THEN "t54"."$f80" / "t40"."$f80" ELSE NULL END > CASE WHEN "t12"."$f80" > 0.000000 THEN "t26"."$f80" / "t12"."$f80" ELSE NULL END AND CASE WHEN "t40"."$f80" > 0.000000 THEN "t54"."$f80" / "t40"."$f80" ELSE NULL END > CASE WHEN "t68"."$f80" > 0.000000 THEN "t82"."$f80" / "t68"."$f80" ELSE NULL END))))
ORDER BY "t26"."C_LOGIN00"
FETCH NEXT 100 ROWS ONLY
