SELECT "$f5" AS "CHANNEL", "$f6" AS "ID", SUM("$f10") AS "SALES", SUM("$f30") AS "RETS", SUM("$f9") AS "PROFIT"
FROM (SELECT *
FROM (SELECT 'store channel' AS "$f5", CAST('store' || CAST("STORE"."S_STORE_ID" AS VARCHAR(16)) AS VARCHAR(28)) AS "$f6", SUM("t1"."SS_EXT_SALES_PRICE0") AS "$f10", SUM("t1"."$f27") AS "$f30", SUM("t1"."SS_NET_PROFIT0") - SUM("t1"."$f28") AS "$f9"
FROM (SELECT "SS_STORE_SK" AS "SS_STORE_SK0", "SS_SOLD_DATE_SK" AS "SS_SOLD_DATE_SK0", "SS_EXT_SALES_PRICE" AS "SS_EXT_SALES_PRICE0", "SS_NET_PROFIT" AS "SS_NET_PROFIT0", 0.00 AS "$f27", 0.00 AS "$f28"
FROM "tpcds"."STORE_SALES"
UNION ALL
SELECT "SR_STORE_SK" AS "SR_STORE_SK0", "SR_RETURNED_DATE_SK" AS "SR_RETURNED_DATE_SK0", 0.00 AS "$f22", 0.00 AS "$f23", "SR_RETURN_AMT" AS "SR_RETURN_AMT0", "SR_NET_LOSS" AS "SR_NET_LOSS0"
FROM "tpcds"."STORE_RETURNS") AS "t1",
"tpcds"."DATE_DIM",
"tpcds"."STORE"
WHERE "t1"."SS_SOLD_DATE_SK0" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_DATE" >= DATE '1998-08-01' AND "DATE_DIM"."D_DATE" <= (DATE '1998-08-01' + INTERVAL '14 days') AND "t1"."SS_STORE_SK0" = "STORE"."S_STORE_SK"
GROUP BY "STORE"."S_STORE_ID"
UNION ALL
SELECT 'catalog channel' AS "$f5", CAST('catalog_page' || CAST("CATALOG_PAGE"."CP_CATALOG_PAGE_ID" AS VARCHAR(16)) AS VARCHAR(28)) AS "$f6", SUM("t8"."CS_EXT_SALES_PRICE0") AS "$f10", SUM("t8"."$f38") AS "$f30", SUM("t8"."CS_NET_PROFIT0") - SUM("t8"."$f39") AS "$f9"
FROM (SELECT "CS_CATALOG_PAGE_SK" AS "CS_CATALOG_PAGE_SK0", "CS_SOLD_DATE_SK" AS "CS_SOLD_DATE_SK0", "CS_EXT_SALES_PRICE" AS "CS_EXT_SALES_PRICE0", "CS_NET_PROFIT" AS "CS_NET_PROFIT0", 0.00 AS "$f38", 0.00 AS "$f39"
FROM "tpcds"."CATALOG_SALES"
UNION ALL
SELECT "CR_CATALOG_PAGE_SK" AS "CR_CATALOG_PAGE_SK0", "CR_RETURNED_DATE_SK" AS "CR_RETURNED_DATE_SK0", 0.00 AS "$f29", 0.00 AS "$f30", "CR_RETURN_AMOUNT" AS "CR_RETURN_AMOUNT0", "CR_NET_LOSS" AS "CR_NET_LOSS0"
FROM "tpcds"."CATALOG_RETURNS") AS "t8",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CATALOG_PAGE"
WHERE "t8"."CS_SOLD_DATE_SK0" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_DATE" >= DATE '1998-08-01' AND "DATE_DIM0"."D_DATE" <= (DATE '1998-08-01' + INTERVAL '14 days') AND "t8"."CS_CATALOG_PAGE_SK0" = "CATALOG_PAGE"."CP_CATALOG_PAGE_SK"
GROUP BY "CATALOG_PAGE"."CP_CATALOG_PAGE_ID")
UNION ALL
SELECT 'web channel' AS "$f5", CAST('web_site' || CAST("WEB_SITE"."WEB_SITE_ID" AS VARCHAR(16)) AS VARCHAR(28)) AS "$f6", SUM("t16"."WS_EXT_SALES_PRICE0") AS "$f10", SUM("t16"."$f38") AS "$f30", SUM("t16"."WS_NET_PROFIT0") - SUM("t16"."$f39") AS "$f9"
FROM (SELECT "WS_WEB_SITE_SK" AS "WS_WEB_SITE_SK0", "WS_SOLD_DATE_SK" AS "WS_SOLD_DATE_SK0", "WS_EXT_SALES_PRICE" AS "WS_EXT_SALES_PRICE0", "WS_NET_PROFIT" AS "WS_NET_PROFIT0", 0.00 AS "$f38", 0.00 AS "$f39"
FROM "tpcds"."WEB_SALES"
UNION ALL
SELECT "WEB_SALES0"."WS_WEB_SITE_SK" AS "WS_WEB_SITE_SK0", "WEB_RETURNS"."WR_RETURNED_DATE_SK" AS "WR_RETURNED_DATE_SK0", 0.00 AS "$f60", 0.00 AS "$f61", "WEB_RETURNS"."WR_RETURN_AMT" AS "WR_RETURN_AMT0", "WEB_RETURNS"."WR_NET_LOSS" AS "WR_NET_LOSS0"
FROM "tpcds"."WEB_RETURNS"
LEFT JOIN "tpcds"."WEB_SALES" AS "WEB_SALES0" ON "WEB_RETURNS"."WR_ITEM_SK" = "WEB_SALES0"."WS_ITEM_SK" AND "WEB_RETURNS"."WR_ORDER_NUMBER" = "WEB_SALES0"."WS_ORDER_NUMBER") AS "t16",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."WEB_SITE"
WHERE "t16"."WS_SOLD_DATE_SK0" = "DATE_DIM1"."D_DATE_SK" AND "DATE_DIM1"."D_DATE" >= DATE '1998-08-01' AND "DATE_DIM1"."D_DATE" <= (DATE '1998-08-01' + INTERVAL '14 days') AND "t16"."WS_WEB_SITE_SK0" = "WEB_SITE"."WEB_SITE_SK"
GROUP BY "WEB_SITE"."WEB_SITE_ID") AS "t21"
GROUP BY ROLLUP("$f5", "$f6")
ORDER BY "$f5", "$f6"
FETCH NEXT 100 ROWS ONLY
