SELECT "t9"."CA_STATE0" AS "STATE", "t9"."$f1" AS "CNT"
FROM (SELECT "CUSTOMER_ADDRESS"."CA_STATE" AS "CA_STATE0", COUNT(*) AS "$f1"
FROM "tpcds"."CUSTOMER_ADDRESS",
"tpcds"."CUSTOMER",
"tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."ITEM"
WHERE "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" = "CUSTOMER"."C_CURRENT_ADDR_SK" AND ("CUSTOMER"."C_CUSTOMER_SK" = "STORE_SALES"."SS_CUSTOMER_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK") AND ("STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("DATE_DIM"."D_MONTH_SEQ" = (((SELECT "D_MONTH_SEQ" AS "D_MONTH_SEQ0"
FROM "tpcds"."DATE_DIM"
WHERE "D_YEAR" = 1998 AND "D_MOY" = 3
GROUP BY "D_MONTH_SEQ"))) AND CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(9, 3)) > 1.2 * (((SELECT AVG("I_CURRENT_PRICE") AS "$f0"
FROM "tpcds"."ITEM"
WHERE "I_CATEGORY" = "ITEM"."I_CATEGORY")))))
GROUP BY "CUSTOMER_ADDRESS"."CA_STATE"
HAVING COUNT(*) >= 10
ORDER BY 2
FETCH NEXT 100 ROWS ONLY) AS "t9"
