SELECT "ITEM"."I_ITEM_ID", AVG("STORE_SALES"."SS_QUANTITY") AS "AGG1", AVG("STORE_SALES"."SS_LIST_PRICE") AS "AGG2", AVG("STORE_SALES"."SS_COUPON_AMT") AS "AGG3", AVG("STORE_SALES"."SS_SALES_PRICE") AS "AGG4"
FROM "tpcds"."STORE_SALES",
"tpcds"."CUSTOMER_DEMOGRAPHICS",
"tpcds"."DATE_DIM",
"tpcds"."ITEM",
"tpcds"."PROMOTION"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("STORE_SALES"."SS_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" AND "STORE_SALES"."SS_PROMO_SK" = "PROMOTION"."P_PROMO_SK") AND ("CUSTOMER_DEMOGRAPHICS"."CD_GENDER" = 'F' AND "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS" = 'W' AND ("CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS" = 'Primary' AND (("PROMOTION"."P_CHANNEL_EMAIL" = 'N' OR "PROMOTION"."P_CHANNEL_EVENT" = 'N') AND "DATE_DIM"."D_YEAR" = 1998)))
GROUP BY "ITEM"."I_ITEM_ID"
ORDER BY "ITEM"."I_ITEM_ID"
FETCH NEXT 100 ROWS ONLY
