SELECT "CUSTOMER_DEMOGRAPHICS"."CD_GENDER", "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS", COUNT(*) AS "CNT1", "CUSTOMER_DEMOGRAPHICS"."CD_PURCHASE_ESTIMATE", COUNT(*) AS "CNT2", "CUSTOMER_DEMOGRAPHICS"."CD_CREDIT_RATING", COUNT(*) AS "CNT3", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT", COUNT(*) AS "CNT4", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT", COUNT(*) AS "CNT5", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT", COUNT(*) AS "CNT6"
FROM "tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."CUSTOMER_DEMOGRAPHICS"
WHERE "CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND "CUSTOMER_ADDRESS"."CA_COUNTY" IN ('[COUNTY.1]', '[COUNTY.2]', '[COUNTY.3]', '[COUNTY.4]', '[COUNTY.5]') AND "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" = "CUSTOMER"."C_CURRENT_CDEMO_SK" AND EXISTS (SELECT *
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "STORE_SALES"."SS_CUSTOMER_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_YEAR" = 2002 AND "DATE_DIM"."D_MOY" >= 3 AND "DATE_DIM"."D_MOY" <= 3 + 3) AND (EXISTS (SELECT *
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "WEB_SALES"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_YEAR" = 2002 AND "DATE_DIM0"."D_MOY" >= 3 AND "DATE_DIM0"."D_MOY" <= 3 + 3) OR EXISTS (SELECT *
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "CATALOG_SALES"."CS_SHIP_CUSTOMER_SK" AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "DATE_DIM1"."D_YEAR" = 2002 AND "DATE_DIM1"."D_MOY" >= 3 AND "DATE_DIM1"."D_MOY" <= 3 + 3))
GROUP BY "CUSTOMER_DEMOGRAPHICS"."CD_GENDER", "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_PURCHASE_ESTIMATE", "CUSTOMER_DEMOGRAPHICS"."CD_CREDIT_RATING", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT"
ORDER BY "CUSTOMER_DEMOGRAPHICS"."CD_GENDER", "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_PURCHASE_ESTIMATE", "CUSTOMER_DEMOGRAPHICS"."CD_CREDIT_RATING", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT"
FETCH NEXT 100 ROWS ONLY
