SELECT "t16"."C_LOGIN00" AS "CUSTOMER_LOGIN"
FROM (SELECT "CUSTOMER"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM"."D_YEAR" AS "D_YEAR00", SUM("STORE_SALES"."SS_EXT_LIST_PRICE" - "STORE_SALES"."SS_EXT_DISCOUNT_AMT") AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER",
"tpcds"."STORE_SALES",
"tpcds"."DATE_DIM"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "STORE_SALES"."SS_CUSTOMER_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK"
GROUP BY "CUSTOMER"."C_CUSTOMER_ID", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_LAST_NAME", "DATE_DIM"."D_YEAR", "CUSTOMER"."C_PREFERRED_CUST_FLAG", "CUSTOMER"."C_BIRTH_COUNTRY", "CUSTOMER"."C_LOGIN", "CUSTOMER"."C_EMAIL_ADDRESS"
UNION ALL
SELECT "CUSTOMER0"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER0"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER0"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER0"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER0"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER0"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER0"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM0"."D_YEAR" AS "D_YEAR00", SUM("WEB_SALES"."WS_EXT_LIST_PRICE" - "WEB_SALES"."WS_EXT_DISCOUNT_AMT") AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER0",
"tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "CUSTOMER0"."C_CUSTOMER_SK" = "WEB_SALES"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK"
GROUP BY "CUSTOMER0"."C_CUSTOMER_ID", "CUSTOMER0"."C_FIRST_NAME", "CUSTOMER0"."C_LAST_NAME", "CUSTOMER0"."C_PREFERRED_CUST_FLAG", "CUSTOMER0"."C_BIRTH_COUNTRY", "CUSTOMER0"."C_LOGIN", "CUSTOMER0"."C_EMAIL_ADDRESS", "DATE_DIM0"."D_YEAR") AS "t7",
(SELECT "CUSTOMER1"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER1"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER1"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER1"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER1"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER1"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER1"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM1"."D_YEAR" AS "D_YEAR00", SUM("STORE_SALES0"."SS_EXT_LIST_PRICE" - "STORE_SALES0"."SS_EXT_DISCOUNT_AMT") AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER1",
"tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "CUSTOMER1"."C_CUSTOMER_SK" = "STORE_SALES0"."SS_CUSTOMER_SK" AND "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK"
GROUP BY "CUSTOMER1"."C_CUSTOMER_ID", "CUSTOMER1"."C_FIRST_NAME", "CUSTOMER1"."C_LAST_NAME", "DATE_DIM1"."D_YEAR", "CUSTOMER1"."C_PREFERRED_CUST_FLAG", "CUSTOMER1"."C_BIRTH_COUNTRY", "CUSTOMER1"."C_LOGIN", "CUSTOMER1"."C_EMAIL_ADDRESS"
UNION ALL
SELECT "CUSTOMER2"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER2"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER2"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER2"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER2"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER2"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER2"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM2"."D_YEAR" AS "D_YEAR00", SUM("WEB_SALES0"."WS_EXT_LIST_PRICE" - "WEB_SALES0"."WS_EXT_DISCOUNT_AMT") AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER2",
"tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "CUSTOMER2"."C_CUSTOMER_SK" = "WEB_SALES0"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES0"."WS_SOLD_DATE_SK" = "DATE_DIM2"."D_DATE_SK"
GROUP BY "CUSTOMER2"."C_CUSTOMER_ID", "CUSTOMER2"."C_FIRST_NAME", "CUSTOMER2"."C_LAST_NAME", "CUSTOMER2"."C_PREFERRED_CUST_FLAG", "CUSTOMER2"."C_BIRTH_COUNTRY", "CUSTOMER2"."C_LOGIN", "CUSTOMER2"."C_EMAIL_ADDRESS", "DATE_DIM2"."D_YEAR") AS "t16",
(SELECT "CUSTOMER3"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER3"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER3"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER3"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER3"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER3"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER3"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM3"."D_YEAR" AS "D_YEAR00", SUM("STORE_SALES1"."SS_EXT_LIST_PRICE" - "STORE_SALES1"."SS_EXT_DISCOUNT_AMT") AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER3",
"tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM3"
WHERE "CUSTOMER3"."C_CUSTOMER_SK" = "STORE_SALES1"."SS_CUSTOMER_SK" AND "STORE_SALES1"."SS_SOLD_DATE_SK" = "DATE_DIM3"."D_DATE_SK"
GROUP BY "CUSTOMER3"."C_CUSTOMER_ID", "CUSTOMER3"."C_FIRST_NAME", "CUSTOMER3"."C_LAST_NAME", "DATE_DIM3"."D_YEAR", "CUSTOMER3"."C_PREFERRED_CUST_FLAG", "CUSTOMER3"."C_BIRTH_COUNTRY", "CUSTOMER3"."C_LOGIN", "CUSTOMER3"."C_EMAIL_ADDRESS"
UNION ALL
SELECT "CUSTOMER4"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER4"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER4"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER4"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER4"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER4"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER4"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM4"."D_YEAR" AS "D_YEAR00", SUM("WEB_SALES1"."WS_EXT_LIST_PRICE" - "WEB_SALES1"."WS_EXT_DISCOUNT_AMT") AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER4",
"tpcds"."WEB_SALES" AS "WEB_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM4"
WHERE "CUSTOMER4"."C_CUSTOMER_SK" = "WEB_SALES1"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES1"."WS_SOLD_DATE_SK" = "DATE_DIM4"."D_DATE_SK"
GROUP BY "CUSTOMER4"."C_CUSTOMER_ID", "CUSTOMER4"."C_FIRST_NAME", "CUSTOMER4"."C_LAST_NAME", "CUSTOMER4"."C_PREFERRED_CUST_FLAG", "CUSTOMER4"."C_BIRTH_COUNTRY", "CUSTOMER4"."C_LOGIN", "CUSTOMER4"."C_EMAIL_ADDRESS", "DATE_DIM4"."D_YEAR") AS "t25",
(SELECT "CUSTOMER5"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER5"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER5"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER5"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER5"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER5"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER5"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM5"."D_YEAR" AS "D_YEAR00", SUM("STORE_SALES2"."SS_EXT_LIST_PRICE" - "STORE_SALES2"."SS_EXT_DISCOUNT_AMT") AS "$f80", 's' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER5",
"tpcds"."STORE_SALES" AS "STORE_SALES2",
"tpcds"."DATE_DIM" AS "DATE_DIM5"
WHERE "CUSTOMER5"."C_CUSTOMER_SK" = "STORE_SALES2"."SS_CUSTOMER_SK" AND "STORE_SALES2"."SS_SOLD_DATE_SK" = "DATE_DIM5"."D_DATE_SK"
GROUP BY "CUSTOMER5"."C_CUSTOMER_ID", "CUSTOMER5"."C_FIRST_NAME", "CUSTOMER5"."C_LAST_NAME", "DATE_DIM5"."D_YEAR", "CUSTOMER5"."C_PREFERRED_CUST_FLAG", "CUSTOMER5"."C_BIRTH_COUNTRY", "CUSTOMER5"."C_LOGIN", "CUSTOMER5"."C_EMAIL_ADDRESS"
UNION ALL
SELECT "CUSTOMER6"."C_CUSTOMER_ID" AS "C_CUSTOMER_ID00", "CUSTOMER6"."C_FIRST_NAME" AS "C_FIRST_NAME00", "CUSTOMER6"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER6"."C_PREFERRED_CUST_FLAG" AS "C_PREFERRED_CUST_FLAG00", "CUSTOMER6"."C_BIRTH_COUNTRY" AS "C_BIRTH_COUNTRY00", "CUSTOMER6"."C_LOGIN" AS "C_LOGIN00", "CUSTOMER6"."C_EMAIL_ADDRESS" AS "C_EMAIL_ADDRESS00", "DATE_DIM6"."D_YEAR" AS "D_YEAR00", SUM("WEB_SALES2"."WS_EXT_LIST_PRICE" - "WEB_SALES2"."WS_EXT_DISCOUNT_AMT") AS "$f80", 'w' AS "$f18"
FROM "tpcds"."CUSTOMER" AS "CUSTOMER6",
"tpcds"."WEB_SALES" AS "WEB_SALES2",
"tpcds"."DATE_DIM" AS "DATE_DIM6"
WHERE "CUSTOMER6"."C_CUSTOMER_SK" = "WEB_SALES2"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES2"."WS_SOLD_DATE_SK" = "DATE_DIM6"."D_DATE_SK"
GROUP BY "CUSTOMER6"."C_CUSTOMER_ID", "CUSTOMER6"."C_FIRST_NAME", "CUSTOMER6"."C_LAST_NAME", "CUSTOMER6"."C_PREFERRED_CUST_FLAG", "CUSTOMER6"."C_BIRTH_COUNTRY", "CUSTOMER6"."C_LOGIN", "CUSTOMER6"."C_EMAIL_ADDRESS", "DATE_DIM6"."D_YEAR") AS "t34"
WHERE "t16"."C_CUSTOMER_ID00" = "t7"."C_CUSTOMER_ID00" AND ("t7"."C_CUSTOMER_ID00" = "t34"."C_CUSTOMER_ID00" AND "t7"."C_CUSTOMER_ID00" = "t25"."C_CUSTOMER_ID00") AND ("t7"."$f18" = 's' AND "t25"."$f18" = 'w' AND ("t16"."$f18" = 's' AND "t34"."$f18" = 'w')) AND ("t7"."D_YEAR00" = 2000 AND ("t16"."D_YEAR00" = 2000 + 1 AND "t25"."D_YEAR00" = 2000) AND ("t34"."D_YEAR00" = 2000 + 1 AND CAST("t7"."$f80" AS DECIMAL(12, 2)) > 0.00 AND (CAST("t25"."$f80" AS DECIMAL(12, 2)) > 0.00 AND CASE WHEN CAST("t25"."$f80" AS DECIMAL(12, 2)) > 0.00 THEN "t34"."$f80" / "t25"."$f80" ELSE NULL END > CASE WHEN CAST("t7"."$f80" AS DECIMAL(12, 2)) > 0.00 THEN "t16"."$f80" / "t7"."$f80" ELSE NULL END)))
ORDER BY "t16"."C_LOGIN00"
FETCH NEXT 100 ROWS ONLY
