SELECT "$f5" AS "CHANNEL", "I_BRAND_ID00" AS "I_BRAND_ID", "I_CLASS_ID00" AS "I_CLASS_ID", "I_CATEGORY_ID00" AS "I_CATEGORY_ID", SUM("$f30"), SUM("$f40")
FROM (SELECT *
FROM (SELECT 'store' AS "$f5", "ITEM"."I_BRAND_ID" AS "I_BRAND_ID00", "ITEM"."I_CLASS_ID" AS "I_CLASS_ID00", "ITEM"."I_CATEGORY_ID" AS "I_CATEGORY_ID00", SUM(CAST("STORE_SALES"."SS_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES"."SS_LIST_PRICE") AS "$f30", COUNT(*) AS "$f40"
FROM "tpcds"."STORE_SALES",
"tpcds"."ITEM",
"tpcds"."DATE_DIM"
WHERE "STORE_SALES"."SS_ITEM_SK" IN (SELECT "ITEM0"."I_ITEM_SK" AS "I_ITEM_SK0"
FROM "tpcds"."ITEM" AS "ITEM0",
(SELECT *
FROM (SELECT "ITEM1"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM1"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM1"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."ITEM" AS "ITEM1",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "STORE_SALES0"."SS_ITEM_SK" = "ITEM1"."I_ITEM_SK" AND "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_YEAR" >= 1999 AND "DATE_DIM0"."D_YEAR" <= 1999 + 2
INTERSECT
SELECT "ITEM2"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM2"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM2"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."ITEM" AS "ITEM2",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "CATALOG_SALES"."CS_ITEM_SK" = "ITEM2"."I_ITEM_SK" AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "DATE_DIM1"."D_YEAR" >= 1999 AND "DATE_DIM1"."D_YEAR" <= 1999 + 2)
INTERSECT
SELECT "ITEM3"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM3"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM3"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."WEB_SALES",
"tpcds"."ITEM" AS "ITEM3",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "WEB_SALES"."WS_ITEM_SK" = "ITEM3"."I_ITEM_SK" AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM2"."D_DATE_SK" AND "DATE_DIM2"."D_YEAR" >= 1999 AND "DATE_DIM2"."D_YEAR" <= 1999 + 2) AS "t6"
WHERE "ITEM0"."I_BRAND_ID" = "t6"."I_BRAND_ID0" AND "ITEM0"."I_CLASS_ID" = "t6"."I_CLASS_ID0" AND "ITEM0"."I_CATEGORY_ID" = "t6"."I_CATEGORY_ID0") AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_YEAR" = 1998 + 2 AND "DATE_DIM"."D_MOY" = 11
GROUP BY "ITEM"."I_BRAND_ID", "ITEM"."I_CLASS_ID", "ITEM"."I_CATEGORY_ID"
HAVING SUM(CAST("STORE_SALES"."SS_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES"."SS_LIST_PRICE") > (((SELECT AVG(CAST("SS_QUANTITY0" AS DECIMAL(12, 2)) * "SS_LIST_PRICE0") AS "$f0"
FROM (SELECT *
FROM (SELECT "STORE_SALES1"."SS_QUANTITY" AS "SS_QUANTITY0", "STORE_SALES1"."SS_LIST_PRICE" AS "SS_LIST_PRICE0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM3"
WHERE "STORE_SALES1"."SS_SOLD_DATE_SK" = "DATE_DIM3"."D_DATE_SK" AND ("DATE_DIM3"."D_YEAR" >= 1999 AND "DATE_DIM3"."D_YEAR" <= 2001)
UNION ALL
SELECT "CATALOG_SALES0"."CS_QUANTITY" AS "CS_QUANTITY0", "CATALOG_SALES0"."CS_LIST_PRICE" AS "CS_LIST_PRICE0"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM4"
WHERE "CATALOG_SALES0"."CS_SOLD_DATE_SK" = "DATE_DIM4"."D_DATE_SK" AND "DATE_DIM4"."D_YEAR" >= 1998 AND "DATE_DIM4"."D_YEAR" <= 1998 + 2)
UNION ALL
SELECT "WEB_SALES0"."WS_QUANTITY" AS "WS_QUANTITY0", "WEB_SALES0"."WS_LIST_PRICE" AS "WS_LIST_PRICE0"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM5"
WHERE "WEB_SALES0"."WS_SOLD_DATE_SK" = "DATE_DIM5"."D_DATE_SK" AND "DATE_DIM5"."D_YEAR" >= 1998 AND "DATE_DIM5"."D_YEAR" <= 1998 + 2) AS "t19")))
UNION ALL
SELECT 'catalog' AS "$f5", "ITEM4"."I_BRAND_ID" AS "I_BRAND_ID00", "ITEM4"."I_CLASS_ID" AS "I_CLASS_ID00", "ITEM4"."I_CATEGORY_ID" AS "I_CATEGORY_ID00", SUM(CAST("CATALOG_SALES1"."CS_QUANTITY" AS DECIMAL(12, 2)) * "CATALOG_SALES1"."CS_LIST_PRICE") AS "$f30", COUNT(*) AS "$f40"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES1",
"tpcds"."ITEM" AS "ITEM4",
"tpcds"."DATE_DIM" AS "DATE_DIM6"
WHERE "CATALOG_SALES1"."CS_ITEM_SK" IN (SELECT "ITEM5"."I_ITEM_SK" AS "I_ITEM_SK0"
FROM "tpcds"."ITEM" AS "ITEM5",
(SELECT *
FROM (SELECT "ITEM6"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM6"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM6"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES2",
"tpcds"."ITEM" AS "ITEM6",
"tpcds"."DATE_DIM" AS "DATE_DIM7"
WHERE "STORE_SALES2"."SS_ITEM_SK" = "ITEM6"."I_ITEM_SK" AND "STORE_SALES2"."SS_SOLD_DATE_SK" = "DATE_DIM7"."D_DATE_SK" AND "DATE_DIM7"."D_YEAR" >= 1999 AND "DATE_DIM7"."D_YEAR" <= 1999 + 2
INTERSECT
SELECT "ITEM7"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM7"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM7"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES2",
"tpcds"."ITEM" AS "ITEM7",
"tpcds"."DATE_DIM" AS "DATE_DIM8"
WHERE "CATALOG_SALES2"."CS_ITEM_SK" = "ITEM7"."I_ITEM_SK" AND "CATALOG_SALES2"."CS_SOLD_DATE_SK" = "DATE_DIM8"."D_DATE_SK" AND "DATE_DIM8"."D_YEAR" >= 1999 AND "DATE_DIM8"."D_YEAR" <= 1999 + 2)
INTERSECT
SELECT "ITEM8"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM8"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM8"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES1",
"tpcds"."ITEM" AS "ITEM8",
"tpcds"."DATE_DIM" AS "DATE_DIM9"
WHERE "WEB_SALES1"."WS_ITEM_SK" = "ITEM8"."I_ITEM_SK" AND "WEB_SALES1"."WS_SOLD_DATE_SK" = "DATE_DIM9"."D_DATE_SK" AND "DATE_DIM9"."D_YEAR" >= 1999 AND "DATE_DIM9"."D_YEAR" <= 1999 + 2) AS "t31"
WHERE "ITEM5"."I_BRAND_ID" = "t31"."I_BRAND_ID0" AND "ITEM5"."I_CLASS_ID" = "t31"."I_CLASS_ID0" AND "ITEM5"."I_CATEGORY_ID" = "t31"."I_CATEGORY_ID0") AND "CATALOG_SALES1"."CS_ITEM_SK" = "ITEM4"."I_ITEM_SK" AND "CATALOG_SALES1"."CS_SOLD_DATE_SK" = "DATE_DIM6"."D_DATE_SK" AND "DATE_DIM6"."D_YEAR" = 1998 + 2 AND "DATE_DIM6"."D_MOY" = 11
GROUP BY "ITEM4"."I_BRAND_ID", "ITEM4"."I_CLASS_ID", "ITEM4"."I_CATEGORY_ID"
HAVING SUM(CAST("CATALOG_SALES1"."CS_QUANTITY" AS DECIMAL(12, 2)) * "CATALOG_SALES1"."CS_LIST_PRICE") > (((SELECT AVG(CAST("SS_QUANTITY0" AS DECIMAL(12, 2)) * "SS_LIST_PRICE0") AS "$f0"
FROM (SELECT *
FROM (SELECT "STORE_SALES3"."SS_QUANTITY" AS "SS_QUANTITY0", "STORE_SALES3"."SS_LIST_PRICE" AS "SS_LIST_PRICE0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES3",
"tpcds"."DATE_DIM" AS "DATE_DIM10"
WHERE "STORE_SALES3"."SS_SOLD_DATE_SK" = "DATE_DIM10"."D_DATE_SK" AND ("DATE_DIM10"."D_YEAR" >= 1999 AND "DATE_DIM10"."D_YEAR" <= 2001)
UNION ALL
SELECT "CATALOG_SALES3"."CS_QUANTITY" AS "CS_QUANTITY0", "CATALOG_SALES3"."CS_LIST_PRICE" AS "CS_LIST_PRICE0"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES3",
"tpcds"."DATE_DIM" AS "DATE_DIM11"
WHERE "CATALOG_SALES3"."CS_SOLD_DATE_SK" = "DATE_DIM11"."D_DATE_SK" AND "DATE_DIM11"."D_YEAR" >= 1998 AND "DATE_DIM11"."D_YEAR" <= 1998 + 2)
UNION ALL
SELECT "WEB_SALES2"."WS_QUANTITY" AS "WS_QUANTITY0", "WEB_SALES2"."WS_LIST_PRICE" AS "WS_LIST_PRICE0"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES2",
"tpcds"."DATE_DIM" AS "DATE_DIM12"
WHERE "WEB_SALES2"."WS_SOLD_DATE_SK" = "DATE_DIM12"."D_DATE_SK" AND "DATE_DIM12"."D_YEAR" >= 1998 AND "DATE_DIM12"."D_YEAR" <= 1998 + 2) AS "t44"))))
UNION ALL
SELECT 'web' AS "$f5", "ITEM9"."I_BRAND_ID" AS "I_BRAND_ID00", "ITEM9"."I_CLASS_ID" AS "I_CLASS_ID00", "ITEM9"."I_CATEGORY_ID" AS "I_CATEGORY_ID00", SUM(CAST("WEB_SALES3"."WS_QUANTITY" AS DECIMAL(12, 2)) * "WEB_SALES3"."WS_LIST_PRICE") AS "$f30", COUNT(*) AS "$f40"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES3",
"tpcds"."ITEM" AS "ITEM9",
"tpcds"."DATE_DIM" AS "DATE_DIM13"
WHERE "WEB_SALES3"."WS_ITEM_SK" IN (SELECT "ITEM10"."I_ITEM_SK" AS "I_ITEM_SK0"
FROM "tpcds"."ITEM" AS "ITEM10",
(SELECT *
FROM (SELECT "ITEM11"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM11"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM11"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES4",
"tpcds"."ITEM" AS "ITEM11",
"tpcds"."DATE_DIM" AS "DATE_DIM14"
WHERE "STORE_SALES4"."SS_ITEM_SK" = "ITEM11"."I_ITEM_SK" AND "STORE_SALES4"."SS_SOLD_DATE_SK" = "DATE_DIM14"."D_DATE_SK" AND "DATE_DIM14"."D_YEAR" >= 1999 AND "DATE_DIM14"."D_YEAR" <= 1999 + 2
INTERSECT
SELECT "ITEM12"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM12"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM12"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES4",
"tpcds"."ITEM" AS "ITEM12",
"tpcds"."DATE_DIM" AS "DATE_DIM15"
WHERE "CATALOG_SALES4"."CS_ITEM_SK" = "ITEM12"."I_ITEM_SK" AND "CATALOG_SALES4"."CS_SOLD_DATE_SK" = "DATE_DIM15"."D_DATE_SK" AND "DATE_DIM15"."D_YEAR" >= 1999 AND "DATE_DIM15"."D_YEAR" <= 1999 + 2)
INTERSECT
SELECT "ITEM13"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM13"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM13"."I_CATEGORY_ID" AS "I_CATEGORY_ID0"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES4",
"tpcds"."ITEM" AS "ITEM13",
"tpcds"."DATE_DIM" AS "DATE_DIM16"
WHERE "WEB_SALES4"."WS_ITEM_SK" = "ITEM13"."I_ITEM_SK" AND "WEB_SALES4"."WS_SOLD_DATE_SK" = "DATE_DIM16"."D_DATE_SK" AND "DATE_DIM16"."D_YEAR" >= 1999 AND "DATE_DIM16"."D_YEAR" <= 1999 + 2) AS "t57"
WHERE "ITEM10"."I_BRAND_ID" = "t57"."I_BRAND_ID0" AND "ITEM10"."I_CLASS_ID" = "t57"."I_CLASS_ID0" AND "ITEM10"."I_CATEGORY_ID" = "t57"."I_CATEGORY_ID0") AND "WEB_SALES3"."WS_ITEM_SK" = "ITEM9"."I_ITEM_SK" AND "WEB_SALES3"."WS_SOLD_DATE_SK" = "DATE_DIM13"."D_DATE_SK" AND "DATE_DIM13"."D_YEAR" = 1998 + 2 AND "DATE_DIM13"."D_MOY" = 11
GROUP BY "ITEM9"."I_BRAND_ID", "ITEM9"."I_CLASS_ID", "ITEM9"."I_CATEGORY_ID"
HAVING SUM(CAST("WEB_SALES3"."WS_QUANTITY" AS DECIMAL(12, 2)) * "WEB_SALES3"."WS_LIST_PRICE") > (((SELECT AVG(CAST("SS_QUANTITY0" AS DECIMAL(12, 2)) * "SS_LIST_PRICE0") AS "$f0"
FROM (SELECT *
FROM (SELECT "STORE_SALES5"."SS_QUANTITY" AS "SS_QUANTITY0", "STORE_SALES5"."SS_LIST_PRICE" AS "SS_LIST_PRICE0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES5",
"tpcds"."DATE_DIM" AS "DATE_DIM17"
WHERE "STORE_SALES5"."SS_SOLD_DATE_SK" = "DATE_DIM17"."D_DATE_SK" AND ("DATE_DIM17"."D_YEAR" >= 1999 AND "DATE_DIM17"."D_YEAR" <= 2001)
UNION ALL
SELECT "CATALOG_SALES5"."CS_QUANTITY" AS "CS_QUANTITY0", "CATALOG_SALES5"."CS_LIST_PRICE" AS "CS_LIST_PRICE0"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES5",
"tpcds"."DATE_DIM" AS "DATE_DIM18"
WHERE "CATALOG_SALES5"."CS_SOLD_DATE_SK" = "DATE_DIM18"."D_DATE_SK" AND "DATE_DIM18"."D_YEAR" >= 1998 AND "DATE_DIM18"."D_YEAR" <= 1998 + 2)
UNION ALL
SELECT "WEB_SALES5"."WS_QUANTITY" AS "WS_QUANTITY0", "WEB_SALES5"."WS_LIST_PRICE" AS "WS_LIST_PRICE0"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES5",
"tpcds"."DATE_DIM" AS "DATE_DIM19"
WHERE "WEB_SALES5"."WS_SOLD_DATE_SK" = "DATE_DIM19"."D_DATE_SK" AND "DATE_DIM19"."D_YEAR" >= 1998 AND "DATE_DIM19"."D_YEAR" <= 1998 + 2) AS "t70")))) AS "t75"
GROUP BY ROLLUP("$f5", "I_BRAND_ID00", "I_CLASS_ID00", "I_CATEGORY_ID00")
ORDER BY "$f5", "I_BRAND_ID00", "I_CLASS_ID00", "I_CATEGORY_ID00"
FETCH NEXT 100 ROWS ONLY
