SELECT "CUSTOMER_ADDRESS"."CA_ZIP", SUM("CATALOG_SALES"."CS_SALES_PRICE")
FROM "tpcds"."CATALOG_SALES",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."DATE_DIM"
WHERE "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND ("CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND (SUBSTRING("CUSTOMER_ADDRESS"."CA_ZIP", 1, 5) IN ('80348', '81792', '83405', '85392', '85460', '85669', '86197', '86475', '88274') OR "CUSTOMER_ADDRESS"."CA_STATE" IN ('CA', 'GA', 'WA') OR CAST("CATALOG_SALES"."CS_SALES_PRICE" AS DECIMAL(12, 2)) > 500.00)) AND ("CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("DATE_DIM"."D_QOY" = 2 AND "DATE_DIM"."D_YEAR" = 1998))
GROUP BY "CUSTOMER_ADDRESS"."CA_ZIP"
ORDER BY "CUSTOMER_ADDRESS"."CA_ZIP"
FETCH NEXT 100 ROWS ONLY
