SELECT "t4"."$f0" AS "order count", "t4"."$f1" AS "total shipping cost", "t4"."$f2" AS "total net profit"
FROM (SELECT COUNT(DISTINCT "CATALOG_SALES"."CS_ORDER_NUMBER") AS "$f0", SUM("CATALOG_SALES"."CS_EXT_SHIP_COST") AS "$f1", SUM("CATALOG_SALES"."CS_NET_PROFIT") AS "$f2"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."CALL_CENTER"
WHERE "DATE_DIM"."D_DATE" >= DATE '2001-05-01' AND "DATE_DIM"."D_DATE" <= (DATE '2001-05-01' + INTERVAL '60 days') AND ("CATALOG_SALES"."CS_SHIP_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "CATALOG_SALES"."CS_SHIP_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK") AND ("CUSTOMER_ADDRESS"."CA_STATE" = 'dist(fips_county,3,1)' AND "CATALOG_SALES"."CS_CALL_CENTER_SK" = "CALL_CENTER"."CC_CALL_CENTER_SK" AND (CAST("CALL_CENTER"."CC_COUNTY" AS VARCHAR(44)) IN ('distmember(fips_county, [COUNTYNUMBER.1], 2)', 'distmember(fips_county, [COUNTYNUMBER.2], 2)', 'distmember(fips_county, [COUNTYNUMBER.3], 2)', 'distmember(fips_county, [COUNTYNUMBER.4], 2)', 'distmember(fips_county, [COUNTYNUMBER.5], 2)') AND (EXISTS (SELECT *
FROM "tpcds"."CATALOG_SALES"
WHERE "CATALOG_SALES"."CS_ORDER_NUMBER" = "CS_ORDER_NUMBER" AND "CATALOG_SALES"."CS_WAREHOUSE_SK" <> "CS_WAREHOUSE_SK") AND NOT EXISTS (SELECT *
FROM "tpcds"."CATALOG_RETURNS"
WHERE "CATALOG_SALES"."CS_ORDER_NUMBER" = "CR_ORDER_NUMBER"))))
ORDER BY 1
FETCH NEXT 100 ROWS ONLY) AS "t4"
