SELECT "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "STORE"."S_STATE", COUNT(*) AS "STORE_SALES_QUANTITYCOUNT", AVG("STORE_SALES"."SS_QUANTITY") AS "STORE_SALES_QUANTITYAVE", AVG("STORE_SALES"."SS_QUANTITY") AS "STORE_SALES_QUANTITYSTDEV", AVG("STORE_SALES"."SS_QUANTITY") / AVG("STORE_SALES"."SS_QUANTITY") AS "STORE_SALES_QUANTITYCOV", COUNT(*) AS "AS_STORE_RETURNS_QUANTITYCOUNT", AVG("STORE_RETURNS"."SR_RETURN_QUANTITY") AS "AS_STORE_RETURNS_QUANTITYAVE", AVG("STORE_RETURNS"."SR_RETURN_QUANTITY") AS "AS_STORE_RETURNS_QUANTITYSTDEV", AVG("STORE_RETURNS"."SR_RETURN_QUANTITY") / AVG("STORE_RETURNS"."SR_RETURN_QUANTITY") AS "STORE_RETURNS_QUANTITYCOV", COUNT(*) AS "CATALOG_SALES_QUANTITYCOUNT", AVG("CATALOG_SALES"."CS_QUANTITY") AS "CATALOG_SALES_QUANTITYAVE", AVG("CATALOG_SALES"."CS_QUANTITY") / AVG("CATALOG_SALES"."CS_QUANTITY") AS "CATALOG_SALES_QUANTITYSTDEV", AVG("CATALOG_SALES"."CS_QUANTITY") / AVG("CATALOG_SALES"."CS_QUANTITY") AS "CATALOG_SALES_QUANTITYCOV"
FROM "tpcds"."STORE_SALES",
"tpcds"."STORE_RETURNS",
"tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."STORE",
"tpcds"."ITEM"
WHERE "DATE_DIM"."D_QUARTER_NAME" = '1998Q1' AND ("DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "ITEM"."I_ITEM_SK" = "STORE_SALES"."SS_ITEM_SK") AND ("STORE"."S_STORE_SK" = "STORE_SALES"."SS_STORE_SK" AND ("STORE_SALES"."SS_CUSTOMER_SK" = "STORE_RETURNS"."SR_CUSTOMER_SK" AND "STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK")) AND ("STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER" AND ("STORE_RETURNS"."SR_RETURNED_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_QUARTER_NAME" IN ('1998Q1', '1998Q2', '1998Q3')) AND ("STORE_RETURNS"."SR_CUSTOMER_SK" = "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" AND "STORE_RETURNS"."SR_ITEM_SK" = "CATALOG_SALES"."CS_ITEM_SK" AND ("CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "DATE_DIM1"."D_QUARTER_NAME" IN ('1998Q1', '1998Q2', '1998Q3'))))
GROUP BY "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "STORE"."S_STATE"
ORDER BY "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "STORE"."S_STATE"
FETCH NEXT 100 ROWS ONLY
