SELECT "ITEM"."I_ITEM_ID", "CUSTOMER_ADDRESS"."CA_COUNTRY", "CUSTOMER_ADDRESS"."CA_STATE", "CUSTOMER_ADDRESS"."CA_COUNTY", AVG(CAST("CATALOG_SALES"."CS_QUANTITY" AS DECIMAL(12, 2))) AS "AGG1", AVG(CAST("CATALOG_SALES"."CS_LIST_PRICE" AS DECIMAL(12, 2))) AS "AGG2", AVG(CAST("CATALOG_SALES"."CS_COUPON_AMT" AS DECIMAL(12, 2))) AS "AGG3", AVG(CAST("CATALOG_SALES"."CS_SALES_PRICE" AS DECIMAL(12, 2))) AS "AGG4", AVG(CAST("CATALOG_SALES"."CS_NET_PROFIT" AS DECIMAL(12, 2))) AS "AGG5", AVG(CAST("CUSTOMER"."C_BIRTH_YEAR" AS DECIMAL(12, 2))) AS "AGG6", AVG(CAST("CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT" AS DECIMAL(12, 2))) AS "AGG7"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."CUSTOMER_DEMOGRAPHICS",
"tpcds"."CUSTOMER_DEMOGRAPHICS" AS "CUSTOMER_DEMOGRAPHICS0",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."DATE_DIM",
"tpcds"."ITEM"
WHERE "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "CATALOG_SALES"."CS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("CATALOG_SALES"."CS_BILL_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" AND ("CATALOG_SALES"."CS_BILL_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND "CUSTOMER_DEMOGRAPHICS"."CD_GENDER" = 'dist(gender, 1, 1)')) AND ("CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS" = 'dist(education, 1, 1)' AND ("CUSTOMER"."C_CURRENT_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS0"."CD_DEMO_SK" AND "CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK") AND ("CUSTOMER"."C_BIRTH_MONTH" IN (1, 2, 6, 8, 9, 12) AND ("DATE_DIM"."D_YEAR" = 1998 AND "CUSTOMER_ADDRESS"."CA_STATE" IN ('IN', 'MS', 'ND', 'NM', 'OK', 'VA'))))
GROUP BY ROLLUP("ITEM"."I_ITEM_ID", "CUSTOMER_ADDRESS"."CA_COUNTRY", "CUSTOMER_ADDRESS"."CA_STATE", "CUSTOMER_ADDRESS"."CA_COUNTY")
ORDER BY "CUSTOMER_ADDRESS"."CA_COUNTRY", "CUSTOMER_ADDRESS"."CA_STATE", "CUSTOMER_ADDRESS"."CA_COUNTY", "ITEM"."I_ITEM_ID"
FETCH NEXT 100 ROWS ONLY
