SELECT "t3"."I_BRAND_ID00" AS "BRAND_ID", "t3"."I_BRAND00" AS "BRAND", "t3"."I_MANUFACT_ID00" AS "I_MANUFACT_ID", "t3"."I_MANUFACT00" AS "I_MANUFACT", "t3"."$f40" AS "EXT_PRICE"
FROM (SELECT "ITEM"."I_BRAND_ID" AS "I_BRAND_ID00", "ITEM"."I_BRAND" AS "I_BRAND00", "ITEM"."I_MANUFACT_ID" AS "I_MANUFACT_ID00", "ITEM"."I_MANUFACT" AS "I_MANUFACT00", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f40"
FROM "tpcds"."DATE_DIM",
"tpcds"."STORE_SALES",
"tpcds"."ITEM",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."STORE"
WHERE "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("ITEM"."I_MANAGER_ID" = 28 AND "DATE_DIM"."D_MOY" = 12) AND ("DATE_DIM"."D_YEAR" = 1998 AND "STORE_SALES"."SS_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND ("CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND (SUBSTRING("CUSTOMER_ADDRESS"."CA_ZIP", 1, 5) <> SUBSTRING("STORE"."S_ZIP", 1, 5) AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK")))
GROUP BY "ITEM"."I_BRAND", "ITEM"."I_BRAND_ID", "ITEM"."I_MANUFACT_ID", "ITEM"."I_MANUFACT"
ORDER BY 5 DESC, "ITEM"."I_BRAND", "ITEM"."I_BRAND_ID", "ITEM"."I_MANUFACT_ID", "ITEM"."I_MANUFACT"
FETCH NEXT 100 ROWS ONLY) AS "t3"
