SELECT "WAREHOUSE"."W_WAREHOUSE_NAME", "ITEM"."I_ITEM_ID", SUM(CASE WHEN "DATE_DIM"."D_DATE" < DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) AS "INV_BEFORE", SUM(CASE WHEN "DATE_DIM"."D_DATE" >= DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) AS "INV_AFTER"
FROM "tpcds"."INVENTORY",
"tpcds"."WAREHOUSE",
"tpcds"."ITEM",
"tpcds"."DATE_DIM"
WHERE "ITEM"."I_CURRENT_PRICE" >= 0.99 AND "ITEM"."I_CURRENT_PRICE" <= 1.49 AND ("ITEM"."I_ITEM_SK" = "INVENTORY"."INV_ITEM_SK" AND "INVENTORY"."INV_WAREHOUSE_SK" = "WAREHOUSE"."W_WAREHOUSE_SK") AND ("INVENTORY"."INV_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("DATE_DIM"."D_DATE" >= (DATE '2000-03-11' - INTERVAL '30 days') AND "DATE_DIM"."D_DATE" <= (DATE '2000-03-11' + INTERVAL '30 days')))
GROUP BY "WAREHOUSE"."W_WAREHOUSE_NAME", "ITEM"."I_ITEM_ID"
HAVING CAST(CASE WHEN SUM(CASE WHEN "DATE_DIM"."D_DATE" < DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) > 0 THEN SUM(CASE WHEN "DATE_DIM"."D_DATE" >= DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) / SUM(CASE WHEN "DATE_DIM"."D_DATE" < DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) ELSE NULL END AS DECIMAL(16, 6)) >= CAST(2.0 / 3.0 AS DECIMAL(16, 6)) AND CAST(CASE WHEN SUM(CASE WHEN "DATE_DIM"."D_DATE" < DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) > 0 THEN SUM(CASE WHEN "DATE_DIM"."D_DATE" >= DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) / SUM(CASE WHEN "DATE_DIM"."D_DATE" < DATE '2000-03-11' THEN "INVENTORY"."INV_QUANTITY_ON_HAND" ELSE 0 END) ELSE NULL END AS DECIMAL(16, 6)) <= CAST(3.0 / 2.0 AS DECIMAL(16, 6))
ORDER BY "WAREHOUSE"."W_WAREHOUSE_NAME", "ITEM"."I_ITEM_ID"
FETCH NEXT 100 ROWS ONLY
