SELECT "t2"."I_PRODUCT_NAME0" AS "I_PRODUCT_NAME", "t2"."I_BRAND0" AS "I_BRAND", "t2"."I_CLASS0" AS "I_CLASS", "t2"."I_CATEGORY0" AS "I_CATEGORY", "t2"."$f4" AS "QOH"
FROM (SELECT "ITEM"."I_PRODUCT_NAME" AS "I_PRODUCT_NAME0", "ITEM"."I_BRAND" AS "I_BRAND0", "ITEM"."I_CLASS" AS "I_CLASS0", "ITEM"."I_CATEGORY" AS "I_CATEGORY0", AVG("INVENTORY"."INV_QUANTITY_ON_HAND") AS "$f4"
FROM "tpcds"."INVENTORY",
"tpcds"."DATE_DIM",
"tpcds"."ITEM",
"tpcds"."WAREHOUSE"
WHERE "INVENTORY"."INV_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "INVENTORY"."INV_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "INVENTORY"."INV_WAREHOUSE_SK" = "WAREHOUSE"."W_WAREHOUSE_SK" AND "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY ROLLUP("ITEM"."I_PRODUCT_NAME", "ITEM"."I_BRAND", "ITEM"."I_CLASS", "ITEM"."I_CATEGORY")
ORDER BY 5, "ITEM"."I_PRODUCT_NAME", "ITEM"."I_BRAND", "ITEM"."I_CLASS", "ITEM"."I_CATEGORY"
FETCH NEXT 100 ROWS ONLY) AS "t2"
