SELECT SUM("$f62")
FROM (SELECT CAST("CATALOG_SALES"."CS_QUANTITY" AS DECIMAL(12, 2)) * "CATALOG_SALES"."CS_LIST_PRICE" AS "$f62"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM"
WHERE "DATE_DIM"."D_YEAR" = 1998 AND "DATE_DIM"."D_MOY" = 3 AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "CATALOG_SALES"."CS_ITEM_SK" IN (SELECT "ITEM"."I_ITEM_SK" AS "I_ITEM_SK00"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."ITEM"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("DATE_DIM0"."D_YEAR" = 1998 OR "DATE_DIM0"."D_YEAR" = 1998 + 1 OR "DATE_DIM0"."D_YEAR" = 1998 + 2 OR "DATE_DIM0"."D_YEAR" = 1998 + 3)
GROUP BY SUBSTRING("ITEM"."I_ITEM_DESC", 1, 30), "ITEM"."I_ITEM_SK", "DATE_DIM0"."D_DATE"
HAVING COUNT(*) > 4) AND "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" IN (SELECT "CUSTOMER"."C_CUSTOMER_SK" AS "C_CUSTOMER_SK00"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."CUSTOMER"
WHERE "STORE_SALES0"."SS_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK"
GROUP BY "CUSTOMER"."C_CUSTOMER_SK"
HAVING CAST(SUM(CAST("STORE_SALES0"."SS_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES0"."SS_SALES_PRICE") AS DECIMAL(19, 4)) > CAST(95.0 / 100.0 * (((SELECT MAX(SUM(CAST("STORE_SALES1"."SS_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES1"."SS_SALES_PRICE")) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."CUSTOMER" AS "CUSTOMER0",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "STORE_SALES1"."SS_CUSTOMER_SK" = "CUSTOMER0"."C_CUSTOMER_SK" AND "STORE_SALES1"."SS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND ("DATE_DIM1"."D_YEAR" = 1998 OR "DATE_DIM1"."D_YEAR" = 1998 + 1 OR "DATE_DIM1"."D_YEAR" = 1998 + 2 OR "DATE_DIM1"."D_YEAR" = 1998 + 3)
GROUP BY "CUSTOMER0"."C_CUSTOMER_SK"))) AS DECIMAL(19, 4)))
UNION ALL
SELECT CAST("WEB_SALES"."WS_QUANTITY" AS DECIMAL(12, 2)) * "WEB_SALES"."WS_LIST_PRICE" AS "$f62"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "DATE_DIM2"."D_YEAR" = 1998 AND "DATE_DIM2"."D_MOY" = 3 AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM2"."D_DATE_SK" AND "WEB_SALES"."WS_ITEM_SK" IN (SELECT "ITEM0"."I_ITEM_SK" AS "I_ITEM_SK00"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES2",
"tpcds"."DATE_DIM" AS "DATE_DIM3",
"tpcds"."ITEM" AS "ITEM0"
WHERE "STORE_SALES2"."SS_SOLD_DATE_SK" = "DATE_DIM3"."D_DATE_SK" AND "STORE_SALES2"."SS_ITEM_SK" = "ITEM0"."I_ITEM_SK" AND ("DATE_DIM3"."D_YEAR" = 1998 OR "DATE_DIM3"."D_YEAR" = 1998 + 1 OR "DATE_DIM3"."D_YEAR" = 1998 + 2 OR "DATE_DIM3"."D_YEAR" = 1998 + 3)
GROUP BY SUBSTRING("ITEM0"."I_ITEM_DESC", 1, 30), "ITEM0"."I_ITEM_SK", "DATE_DIM3"."D_DATE"
HAVING COUNT(*) > 4) AND "WEB_SALES"."WS_BILL_CUSTOMER_SK" IN (SELECT "CUSTOMER1"."C_CUSTOMER_SK" AS "C_CUSTOMER_SK00"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES3",
"tpcds"."CUSTOMER" AS "CUSTOMER1"
WHERE "STORE_SALES3"."SS_CUSTOMER_SK" = "CUSTOMER1"."C_CUSTOMER_SK"
GROUP BY "CUSTOMER1"."C_CUSTOMER_SK"
HAVING CAST(SUM(CAST("STORE_SALES3"."SS_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES3"."SS_SALES_PRICE") AS DECIMAL(19, 4)) > CAST(95.0 / 100.0 * (((SELECT MAX(SUM(CAST("STORE_SALES4"."SS_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES4"."SS_SALES_PRICE")) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES4",
"tpcds"."CUSTOMER" AS "CUSTOMER2",
"tpcds"."DATE_DIM" AS "DATE_DIM4"
WHERE "STORE_SALES4"."SS_CUSTOMER_SK" = "CUSTOMER2"."C_CUSTOMER_SK" AND "STORE_SALES4"."SS_SOLD_DATE_SK" = "DATE_DIM4"."D_DATE_SK" AND ("DATE_DIM4"."D_YEAR" = 1998 OR "DATE_DIM4"."D_YEAR" = 1998 + 1 OR "DATE_DIM4"."D_YEAR" = 1998 + 2 OR "DATE_DIM4"."D_YEAR" = 1998 + 3)
GROUP BY "CUSTOMER2"."C_CUSTOMER_SK"))) AS DECIMAL(19, 4)))) AS "t33"
FETCH NEXT 100 ROWS ONLY
