SELECT "t3"."C_LAST_NAME00" AS "C_LAST_NAME", "t3"."C_FIRST_NAME00" AS "C_FIRST_NAME", "t3"."S_STORE_NAME00" AS "S_STORE_NAME", SUM("t3"."$f100") AS "PAID"
FROM (SELECT "CUSTOMER"."C_LAST_NAME" AS "C_LAST_NAME00", "CUSTOMER"."C_FIRST_NAME" AS "C_FIRST_NAME00", "STORE"."S_STORE_NAME" AS "S_STORE_NAME00", SUM("STORE_SALES"."SS_NET_PROFIT") AS "$f100"
FROM "tpcds"."STORE_SALES",
"tpcds"."STORE_RETURNS",
"tpcds"."STORE",
"tpcds"."ITEM",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS"
WHERE "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER" AND "STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK" AND ("STORE_SALES"."SS_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK") AND ("STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND "CUSTOMER"."C_BIRTH_COUNTRY" = UPPER("CUSTOMER_ADDRESS"."CA_COUNTRY") AND ("STORE"."S_ZIP" = "CUSTOMER_ADDRESS"."CA_ZIP" AND "STORE"."S_MARKET_ID" = 5))
GROUP BY "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_FIRST_NAME", "STORE"."S_STORE_NAME", "CUSTOMER_ADDRESS"."CA_STATE", "STORE"."S_STATE", "ITEM"."I_COLOR", "ITEM"."I_CURRENT_PRICE", "ITEM"."I_MANAGER_ID", "ITEM"."I_UNITS", "ITEM"."I_SIZE"
HAVING "ITEM"."I_COLOR" = '[COLOR.1]') AS "t3"
GROUP BY "t3"."C_LAST_NAME00", "t3"."C_FIRST_NAME00", "t3"."S_STORE_NAME00"
HAVING CAST(SUM("t3"."$f100") AS DECIMAL(10, 4)) > (((SELECT 0.05 * AVG(SUM("STORE_SALES0"."SS_NET_PROFIT")) AS "$f1"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."STORE_RETURNS" AS "STORE_RETURNS0",
"tpcds"."STORE" AS "STORE0",
"tpcds"."ITEM" AS "ITEM0",
"tpcds"."CUSTOMER" AS "CUSTOMER0",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0"
WHERE "STORE_SALES0"."SS_TICKET_NUMBER" = "STORE_RETURNS0"."SR_TICKET_NUMBER" AND "STORE_SALES0"."SS_ITEM_SK" = "STORE_RETURNS0"."SR_ITEM_SK" AND ("STORE_SALES0"."SS_CUSTOMER_SK" = "CUSTOMER0"."C_CUSTOMER_SK" AND "STORE_SALES0"."SS_ITEM_SK" = "ITEM0"."I_ITEM_SK") AND ("STORE_SALES0"."SS_STORE_SK" = "STORE0"."S_STORE_SK" AND "CUSTOMER0"."C_BIRTH_COUNTRY" = UPPER("CUSTOMER_ADDRESS0"."CA_COUNTRY") AND ("STORE0"."S_ZIP" = "CUSTOMER_ADDRESS0"."CA_ZIP" AND "STORE0"."S_MARKET_ID" = 5))
GROUP BY "CUSTOMER0"."C_LAST_NAME", "CUSTOMER0"."C_FIRST_NAME", "STORE0"."S_STORE_NAME", "CUSTOMER_ADDRESS0"."CA_STATE", "STORE0"."S_STATE", "ITEM0"."I_COLOR", "ITEM0"."I_CURRENT_PRICE", "ITEM0"."I_MANAGER_ID", "ITEM0"."I_UNITS", "ITEM0"."I_SIZE")))
