SELECT "ITEM"."I_ITEM_ID", AVG("CATALOG_SALES"."CS_QUANTITY") AS "AGG1", AVG("CATALOG_SALES"."CS_LIST_PRICE") AS "AGG2", AVG("CATALOG_SALES"."CS_COUPON_AMT") AS "AGG3", AVG("CATALOG_SALES"."CS_SALES_PRICE") AS "AGG4"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."CUSTOMER_DEMOGRAPHICS",
"tpcds"."DATE_DIM",
"tpcds"."ITEM",
"tpcds"."PROMOTION"
WHERE "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "CATALOG_SALES"."CS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("CATALOG_SALES"."CS_BILL_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" AND "CATALOG_SALES"."CS_PROMO_SK" = "PROMOTION"."P_PROMO_SK") AND ("CUSTOMER_DEMOGRAPHICS"."CD_GENDER" = 'dist(gender, 1, 1)' AND "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS" = 'dist(marital_status, 1, 1)' AND ("CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS" = 'dist(education, 1, 1)' AND (("PROMOTION"."P_CHANNEL_EMAIL" = 'N' OR "PROMOTION"."P_CHANNEL_EVENT" = 'N') AND "DATE_DIM"."D_YEAR" = 1998)))
GROUP BY "ITEM"."I_ITEM_ID"
ORDER BY "ITEM"."I_ITEM_ID"
FETCH NEXT 100 ROWS ONLY
