SELECT "I_ITEM_ID00" AS "I_ITEM_ID", "S_STATE00" AS "S_STATE", "$f8" AS "G_STATE", "$f20" AS "AGG1", "$f30" AS "AGG2", "$f40" AS "AGG3", "$f50" AS "AGG4"
FROM (SELECT *
FROM (SELECT "ITEM"."I_ITEM_ID" AS "I_ITEM_ID00", "STORE"."S_STATE" AS "S_STATE00", 0 AS "$f8", AVG("STORE_SALES"."SS_QUANTITY") AS "$f20", AVG("STORE_SALES"."SS_LIST_PRICE") AS "$f30", AVG("STORE_SALES"."SS_COUPON_AMT") AS "$f40", AVG("STORE_SALES"."SS_SALES_PRICE") AS "$f50"
FROM "tpcds"."STORE_SALES",
"tpcds"."CUSTOMER_DEMOGRAPHICS",
"tpcds"."DATE_DIM",
"tpcds"."STORE",
"tpcds"."ITEM"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND "STORE_SALES"."SS_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK") AND ("CUSTOMER_DEMOGRAPHICS"."CD_GENDER" = 'dist(gender, 1, 1)' AND "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS" = 'dist(marital_status, 1, 1)' AND ("CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS" = 'dist(education, 1, 1)' AND ("DATE_DIM"."D_YEAR" = 1998 AND "STORE"."S_STATE" = 'TN')))
GROUP BY "ITEM"."I_ITEM_ID", "STORE"."S_STATE"
UNION ALL
SELECT "ITEM0"."I_ITEM_ID" AS "I_ITEM_ID00", CAST(NULL AS CHAR(2)) AS "$f6", 1 AS "$f7", AVG("STORE_SALES0"."SS_QUANTITY") AS "$f10", AVG("STORE_SALES0"."SS_LIST_PRICE") AS "$f20", AVG("STORE_SALES0"."SS_COUPON_AMT") AS "$f30", AVG("STORE_SALES0"."SS_SALES_PRICE") AS "$f40"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."CUSTOMER_DEMOGRAPHICS" AS "CUSTOMER_DEMOGRAPHICS0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."STORE" AS "STORE0",
"tpcds"."ITEM" AS "ITEM0"
WHERE "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "STORE_SALES0"."SS_ITEM_SK" = "ITEM0"."I_ITEM_SK" AND ("STORE_SALES0"."SS_STORE_SK" = "STORE0"."S_STORE_SK" AND "STORE_SALES0"."SS_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS0"."CD_DEMO_SK") AND ("CUSTOMER_DEMOGRAPHICS0"."CD_GENDER" = 'dist(gender, 1, 1)' AND "CUSTOMER_DEMOGRAPHICS0"."CD_MARITAL_STATUS" = 'dist(marital_status, 1, 1)' AND ("CUSTOMER_DEMOGRAPHICS0"."CD_EDUCATION_STATUS" = 'dist(education, 1, 1)' AND ("DATE_DIM0"."D_YEAR" = 1998 AND "STORE0"."S_STATE" = 'TN')))
GROUP BY "ITEM0"."I_ITEM_ID")
UNION ALL
SELECT CAST(NULL AS CHAR(16)) AS "$f4", CAST(NULL AS CHAR(2)) AS "$f5", 1 AS "$f6", AVG("STORE_SALES1"."SS_QUANTITY") AS "$f00", AVG("STORE_SALES1"."SS_LIST_PRICE") AS "$f10", AVG("STORE_SALES1"."SS_COUPON_AMT") AS "$f20", AVG("STORE_SALES1"."SS_SALES_PRICE") AS "$f30"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."CUSTOMER_DEMOGRAPHICS" AS "CUSTOMER_DEMOGRAPHICS1",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."STORE" AS "STORE1",
"tpcds"."ITEM" AS "ITEM1"
WHERE "STORE_SALES1"."SS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "STORE_SALES1"."SS_ITEM_SK" = "ITEM1"."I_ITEM_SK" AND ("STORE_SALES1"."SS_STORE_SK" = "STORE1"."S_STORE_SK" AND "STORE_SALES1"."SS_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS1"."CD_DEMO_SK") AND ("CUSTOMER_DEMOGRAPHICS1"."CD_GENDER" = 'dist(gender, 1, 1)' AND "CUSTOMER_DEMOGRAPHICS1"."CD_MARITAL_STATUS" = 'dist(marital_status, 1, 1)' AND ("CUSTOMER_DEMOGRAPHICS1"."CD_EDUCATION_STATUS" = 'dist(education, 1, 1)' AND ("DATE_DIM1"."D_YEAR" = 1998 AND "STORE1"."S_STATE" = 'TN'))))
ORDER BY "I_ITEM_ID00", "S_STATE00"
FETCH NEXT 100 ROWS ONLY
