SELECT "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "STORE"."S_STORE_ID", "STORE"."S_STORE_NAME", AVG("STORE_SALES"."SS_QUANTITY") AS "STORE_SALES_QUANTITY", AVG("STORE_RETURNS"."SR_RETURN_QUANTITY") AS "STORE_RETURNS_QUANTITY", AVG("CATALOG_SALES"."CS_QUANTITY") AS "CATALOG_SALES_QUANTITY"
FROM "tpcds"."STORE_SALES",
"tpcds"."STORE_RETURNS",
"tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."STORE",
"tpcds"."ITEM"
WHERE "DATE_DIM"."D_MOY" = 4 AND "DATE_DIM"."D_YEAR" = 1998 AND ("DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "ITEM"."I_ITEM_SK" = "STORE_SALES"."SS_ITEM_SK") AND ("STORE"."S_STORE_SK" = "STORE_SALES"."SS_STORE_SK" AND "STORE_SALES"."SS_CUSTOMER_SK" = "STORE_RETURNS"."SR_CUSTOMER_SK" AND ("STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK" AND "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER")) AND ("STORE_RETURNS"."SR_RETURNED_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_MOY" >= 4 AND ("DATE_DIM0"."D_MOY" <= 4 + 3 AND "DATE_DIM0"."D_YEAR" = 1998) AND ("STORE_RETURNS"."SR_CUSTOMER_SK" = "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" AND "STORE_RETURNS"."SR_ITEM_SK" = "CATALOG_SALES"."CS_ITEM_SK" AND ("CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND ("DATE_DIM1"."D_YEAR" = 1998 OR "DATE_DIM1"."D_YEAR" = 1998 + 1 OR "DATE_DIM1"."D_YEAR" = 1998 + 2))))
GROUP BY "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "STORE"."S_STORE_ID", "STORE"."S_STORE_NAME"
ORDER BY "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "STORE"."S_STORE_ID", "STORE"."S_STORE_NAME"
FETCH NEXT 100 ROWS ONLY
