SELECT "CUSTOMER"."C_CUSTOMER_ID", "CUSTOMER"."C_SALUTATION", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_PREFERRED_CUST_FLAG", "CUSTOMER"."C_BIRTH_DAY", "CUSTOMER"."C_BIRTH_MONTH", "CUSTOMER"."C_BIRTH_YEAR", "CUSTOMER"."C_BIRTH_COUNTRY", "CUSTOMER"."C_LOGIN", "CUSTOMER"."C_EMAIL_ADDRESS", "CUSTOMER"."C_LAST_REVIEW_DATE_SK", "t1"."$f2" AS "CTR_TOTAL_RETURN"
FROM (SELECT "WEB_RETURNS"."WR_RETURNING_CUSTOMER_SK" AS "WR_RETURNING_CUSTOMER_SK0", "CUSTOMER_ADDRESS"."CA_STATE" AS "CA_STATE0", SUM("WEB_RETURNS"."WR_RETURN_AMT") AS "$f2"
FROM "tpcds"."WEB_RETURNS",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER_ADDRESS"
WHERE "WEB_RETURNS"."WR_RETURNED_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_YEAR" = 2001 AND "WEB_RETURNS"."WR_RETURNING_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK"
GROUP BY "WEB_RETURNS"."WR_RETURNING_CUSTOMER_SK", "CUSTOMER_ADDRESS"."CA_STATE") AS "t1",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0",
"tpcds"."CUSTOMER"
WHERE CAST("t1"."$f2" AS DECIMAL(9, 3)) > (((SELECT AVG(SUM("WEB_RETURNS0"."WR_RETURN_AMT")) * 1.2 AS "$f1"
FROM "tpcds"."WEB_RETURNS" AS "WEB_RETURNS0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS1"
WHERE "WEB_RETURNS0"."WR_RETURNED_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_YEAR" = 2001 AND "WEB_RETURNS0"."WR_RETURNING_ADDR_SK" = "CUSTOMER_ADDRESS1"."CA_ADDRESS_SK"
GROUP BY "WEB_RETURNS0"."WR_RETURNING_CUSTOMER_SK", "CUSTOMER_ADDRESS1"."CA_STATE"
HAVING "t1"."CA_STATE0" = "CUSTOMER_ADDRESS1"."CA_STATE"))) AND "CUSTOMER_ADDRESS0"."CA_ADDRESS_SK" = "CUSTOMER"."C_CURRENT_ADDR_SK" AND "CUSTOMER_ADDRESS0"."CA_STATE" = 'dist(fips_county, 3, 1)' AND "t1"."WR_RETURNING_CUSTOMER_SK0" = "CUSTOMER"."C_CUSTOMER_SK"
ORDER BY "CUSTOMER"."C_CUSTOMER_ID", "CUSTOMER"."C_SALUTATION", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_PREFERRED_CUST_FLAG", "CUSTOMER"."C_BIRTH_DAY", "CUSTOMER"."C_BIRTH_MONTH", "CUSTOMER"."C_BIRTH_YEAR", "CUSTOMER"."C_BIRTH_COUNTRY", "CUSTOMER"."C_LOGIN", "CUSTOMER"."C_EMAIL_ADDRESS", "CUSTOMER"."C_LAST_REVIEW_DATE_SK", "t1"."$f2"
FETCH NEXT 100 ROWS ONLY
