SELECT "t19"."CA_COUNTY05" AS "CA_COUNTY", "t19"."D_YEAR05" AS "D_YEAR", "t19"."$f26" AS "WEB_Q1_Q2_INCREASE", "t19"."$f27" AS "STORE_Q1_Q2_INCREASE", "t19"."$f28" AS "WEB_Q2_Q3_INCREASE", "t19"."$f29" AS "STORE_Q2_Q3_INCREASE"
FROM (SELECT "t1"."CA_COUNTY0" AS "CA_COUNTY05", "t1"."D_YEAR0" AS "D_YEAR05", "t13"."$f3" / "t10"."$f3" AS "$f26", "t4"."$f3" / "t1"."$f3" AS "$f27", "t16"."$f3" / "t13"."$f3" AS "$f28", "t7"."$f3" / "t4"."$f3" AS "$f29"
FROM (SELECT "CUSTOMER_ADDRESS"."CA_COUNTY" AS "CA_COUNTY0", "DATE_DIM"."D_QOY" AS "D_QOY0", "DATE_DIM"."D_YEAR" AS "D_YEAR0", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f3"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER_ADDRESS"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK"
GROUP BY "CUSTOMER_ADDRESS"."CA_COUNTY", "DATE_DIM"."D_QOY", "DATE_DIM"."D_YEAR") AS "t1",
(SELECT "CUSTOMER_ADDRESS0"."CA_COUNTY" AS "CA_COUNTY0", "DATE_DIM0"."D_QOY" AS "D_QOY0", "DATE_DIM0"."D_YEAR" AS "D_YEAR0", SUM("STORE_SALES0"."SS_EXT_SALES_PRICE") AS "$f3"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0"
WHERE "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "STORE_SALES0"."SS_ADDR_SK" = "CUSTOMER_ADDRESS0"."CA_ADDRESS_SK"
GROUP BY "CUSTOMER_ADDRESS0"."CA_COUNTY", "DATE_DIM0"."D_QOY", "DATE_DIM0"."D_YEAR") AS "t4",
(SELECT "CUSTOMER_ADDRESS1"."CA_COUNTY" AS "CA_COUNTY0", "DATE_DIM1"."D_QOY" AS "D_QOY0", "DATE_DIM1"."D_YEAR" AS "D_YEAR0", SUM("STORE_SALES1"."SS_EXT_SALES_PRICE") AS "$f3"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS1"
WHERE "STORE_SALES1"."SS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "STORE_SALES1"."SS_ADDR_SK" = "CUSTOMER_ADDRESS1"."CA_ADDRESS_SK"
GROUP BY "CUSTOMER_ADDRESS1"."CA_COUNTY", "DATE_DIM1"."D_QOY", "DATE_DIM1"."D_YEAR") AS "t7",
(SELECT "CUSTOMER_ADDRESS2"."CA_COUNTY" AS "CA_COUNTY0", "DATE_DIM2"."D_QOY" AS "D_QOY0", "DATE_DIM2"."D_YEAR" AS "D_YEAR0", SUM("WEB_SALES"."WS_EXT_SALES_PRICE") AS "$f3"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM2",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS2"
WHERE "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM2"."D_DATE_SK" AND "WEB_SALES"."WS_BILL_ADDR_SK" = "CUSTOMER_ADDRESS2"."CA_ADDRESS_SK"
GROUP BY "CUSTOMER_ADDRESS2"."CA_COUNTY", "DATE_DIM2"."D_QOY", "DATE_DIM2"."D_YEAR") AS "t10",
(SELECT "CUSTOMER_ADDRESS3"."CA_COUNTY" AS "CA_COUNTY0", "DATE_DIM3"."D_QOY" AS "D_QOY0", "DATE_DIM3"."D_YEAR" AS "D_YEAR0", SUM("WEB_SALES0"."WS_EXT_SALES_PRICE") AS "$f3"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM3",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS3"
WHERE "WEB_SALES0"."WS_SOLD_DATE_SK" = "DATE_DIM3"."D_DATE_SK" AND "WEB_SALES0"."WS_BILL_ADDR_SK" = "CUSTOMER_ADDRESS3"."CA_ADDRESS_SK"
GROUP BY "CUSTOMER_ADDRESS3"."CA_COUNTY", "DATE_DIM3"."D_QOY", "DATE_DIM3"."D_YEAR") AS "t13",
(SELECT "CUSTOMER_ADDRESS4"."CA_COUNTY" AS "CA_COUNTY0", "DATE_DIM4"."D_QOY" AS "D_QOY0", "DATE_DIM4"."D_YEAR" AS "D_YEAR0", SUM("WEB_SALES1"."WS_EXT_SALES_PRICE") AS "$f3"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM4",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS4"
WHERE "WEB_SALES1"."WS_SOLD_DATE_SK" = "DATE_DIM4"."D_DATE_SK" AND "WEB_SALES1"."WS_BILL_ADDR_SK" = "CUSTOMER_ADDRESS4"."CA_ADDRESS_SK"
GROUP BY "CUSTOMER_ADDRESS4"."CA_COUNTY", "DATE_DIM4"."D_QOY", "DATE_DIM4"."D_YEAR") AS "t16"
WHERE "t1"."D_QOY0" = 1 AND "t1"."D_YEAR0" = 1998 AND ("t1"."CA_COUNTY0" = "t4"."CA_COUNTY0" AND "t4"."D_QOY0" = 2) AND ("t4"."D_YEAR0" = 1998 AND "t4"."CA_COUNTY0" = "t7"."CA_COUNTY0" AND ("t7"."D_QOY0" = 3 AND ("t7"."D_YEAR0" = 1998 AND "t1"."CA_COUNTY0" = "t10"."CA_COUNTY0"))) AND ("t10"."D_QOY0" = 1 AND "t10"."D_YEAR0" = 1998 AND ("t10"."CA_COUNTY0" = "t13"."CA_COUNTY0" AND ("t13"."D_QOY0" = 2 AND "t13"."D_YEAR0" = 1998)) AND ("t10"."CA_COUNTY0" = "t16"."CA_COUNTY0" AND "t16"."D_QOY0" = 3 AND ("t16"."D_YEAR0" = 1998 AND (CASE WHEN CAST("t10"."$f3" AS DECIMAL(12, 2)) > 0.00 THEN "t13"."$f3" / "t10"."$f3" ELSE NULL END > CASE WHEN CAST("t1"."$f3" AS DECIMAL(12, 2)) > 0.00 THEN "t4"."$f3" / "t1"."$f3" ELSE NULL END AND CASE WHEN CAST("t13"."$f3" AS DECIMAL(12, 2)) > 0.00 THEN "t16"."$f3" / "t13"."$f3" ELSE NULL END > CASE WHEN CAST("t4"."$f3" AS DECIMAL(12, 2)) > 0.00 THEN "t7"."$f3" / "t4"."$f3" ELSE NULL END))))
ORDER BY 4) AS "t19"
