SELECT SUM("CATALOG_SALES"."CS_EXT_DISCOUNT_AMT") AS "excess discount amount"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."ITEM",
"tpcds"."DATE_DIM"
WHERE "ITEM"."I_MANUFACT_ID" = 361 AND ("ITEM"."I_ITEM_SK" = "CATALOG_SALES"."CS_ITEM_SK" AND "DATE_DIM"."D_DATE" >= DATE '2000-01-27') AND ("DATE_DIM"."D_DATE" <= (DATE '2000-01-27' + INTERVAL '90 days') AND ("DATE_DIM"."D_DATE_SK" = "CATALOG_SALES"."CS_SOLD_DATE_SK" AND CAST("CATALOG_SALES"."CS_EXT_DISCOUNT_AMT" AS DECIMAL(9, 3)) > (((SELECT 1.3 * AVG("CATALOG_SALES0"."CS_EXT_DISCOUNT_AMT") AS "$f1"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "CATALOG_SALES0"."CS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "DATE_DIM0"."D_DATE" >= DATE '2000-01-27' AND "DATE_DIM0"."D_DATE" <= (DATE '2000-01-27' + INTERVAL '90 days') AND "DATE_DIM0"."D_DATE_SK" = "CATALOG_SALES0"."CS_SOLD_DATE_SK")))))
FETCH NEXT 100 ROWS ONLY
