SELECT "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_SALUTATION", "CUSTOMER"."C_PREFERRED_CUST_FLAG", "t1"."SS_TICKET_NUMBER0" AS "SS_TICKET_NUMBER", "t1"."$f2" AS "CNT"
FROM (SELECT "STORE_SALES"."SS_TICKET_NUMBER" AS "SS_TICKET_NUMBER0", "STORE_SALES"."SS_CUSTOMER_SK" AS "SS_CUSTOMER_SK0", COUNT(*) AS "$f2"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND ("STORE_SALES"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" AND ("DATE_DIM"."D_DOM" >= 1 AND "DATE_DIM"."D_DOM" <= 3 OR "DATE_DIM"."D_DOM" >= 25 AND "DATE_DIM"."D_DOM" <= 28)) AND (CAST("HOUSEHOLD_DEMOGRAPHICS"."HD_BUY_POTENTIAL" AS VARCHAR(15)) IN ('0-500', '1001-5000') AND "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" > 0 AND (CAST(CASE WHEN "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" > 0 THEN "HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" / "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" ELSE NULL END AS DECIMAL(11, 1)) > 1.2 AND (("DATE_DIM"."D_YEAR" = 1999 OR "DATE_DIM"."D_YEAR" = 1999 + 1 OR "DATE_DIM"."D_YEAR" = 1999 + 2) AND CAST("STORE"."S_COUNTY" AS VARCHAR(44)) IN ('distmember(fips_county, [COUNTYNUMBER.1], 2)', 'distmember(fips_county, [COUNTYNUMBER.2], 2)', 'distmember(fips_county, [COUNTYNUMBER.3], 2)', 'distmember(fips_county, [COUNTYNUMBER.4], 2)', 'distmember(fips_county, [COUNTYNUMBER.5], 2)', 'distmember(fips_county, [COUNTYNUMBER.6], 2)', 'distmember(fips_county, [COUNTYNUMBER.7], 2)', 'distmember(fips_county, [COUNTYNUMBER.8], 2)'))))
GROUP BY "STORE_SALES"."SS_TICKET_NUMBER", "STORE_SALES"."SS_CUSTOMER_SK") AS "t1",
"tpcds"."CUSTOMER"
WHERE "t1"."SS_CUSTOMER_SK0" = "CUSTOMER"."C_CUSTOMER_SK" AND ("t1"."$f2" >= 15 AND "t1"."$f2" <= 20)
ORDER BY "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_SALUTATION", "CUSTOMER"."C_PREFERRED_CUST_FLAG" DESC
