SELECT "t7"."CA_STATE000" AS "CA_STATE", "t7"."CD_GENDER000" AS "CD_GENDER", "t7"."CD_MARITAL_STATUS000" AS "CD_MARITAL_STATUS", "t7"."$f600" AS "CNT1", "t7"."$f700", "t7"."$f800", "t7"."$f900", "t7"."CD_DEP_EMPLOYED_COUNT000" AS "CD_DEP_EMPLOYED_COUNT", "t7"."$f610" AS "CNT2", "t7"."$f1000", "t7"."$f1100", "t7"."$f1200", "t7"."CD_DEP_COLLEGE_COUNT000" AS "CD_DEP_COLLEGE_COUNT", "t7"."$f620" AS "CNT3", "t7"."$f1300", "t7"."$f1400", "t7"."$f1500"
FROM (SELECT "CUSTOMER_ADDRESS"."CA_STATE" AS "CA_STATE000", "CUSTOMER_DEMOGRAPHICS"."CD_GENDER" AS "CD_GENDER000", "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS" AS "CD_MARITAL_STATUS000", COUNT(*) AS "$f600", MAX("CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT") AS "$f700", AVG("CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT") AS "$f800", MIN("CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT") AS "$f900", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT" AS "CD_DEP_EMPLOYED_COUNT000", COUNT(*) AS "$f610", MAX("CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT") AS "$f1000", AVG("CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT") AS "$f1100", MIN("CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT") AS "$f1200", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT" AS "CD_DEP_COLLEGE_COUNT000", COUNT(*) AS "$f620", MAX("CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT") AS "$f1300", AVG("CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT") AS "$f1400", MIN("CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT") AS "$f1500"
FROM "tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."CUSTOMER_DEMOGRAPHICS"
WHERE "CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" = "CUSTOMER"."C_CURRENT_CDEMO_SK" AND EXISTS (SELECT *
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "STORE_SALES"."SS_CUSTOMER_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_YEAR" = 2001 AND "DATE_DIM"."D_QOY" < 4) AND (EXISTS (SELECT *
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "WEB_SALES"."WS_BILL_CUSTOMER_SK" AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_YEAR" = 2001 AND "DATE_DIM0"."D_QOY" < 4) OR EXISTS (SELECT *
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "CUSTOMER"."C_CUSTOMER_SK" = "CATALOG_SALES"."CS_SHIP_CUSTOMER_SK" AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "DATE_DIM1"."D_YEAR" = 2001 AND "DATE_DIM1"."D_QOY" < 4))
GROUP BY "CUSTOMER_ADDRESS"."CA_STATE", "CUSTOMER_DEMOGRAPHICS"."CD_GENDER", "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT"
ORDER BY "CUSTOMER_ADDRESS"."CA_STATE", "CUSTOMER_DEMOGRAPHICS"."CD_GENDER", "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_EMPLOYED_COUNT", "CUSTOMER_DEMOGRAPHICS"."CD_DEP_COLLEGE_COUNT"
FETCH NEXT 100 ROWS ONLY) AS "t7"
