SELECT "$f40" AS "GROSS_MARGIN", "I_CATEGORY000" AS "I_CATEGORY", "I_CLASS000" AS "I_CLASS", "$f90" AS "LOCHIERARCHY", "$f10" AS "RANK_WITHIN_PARENT"
FROM (SELECT "$f4" AS "$f40", "I_CATEGORY00" AS "I_CATEGORY000", "I_CLASS00" AS "I_CLASS000", "$f9" AS "$f90", RANK() OVER (PARTITION BY "$f9", CASE WHEN "$f8" = 0 THEN "I_CATEGORY00" ELSE NULL END ORDER BY "$f4") AS "$f10", CASE WHEN "$f9" = 0 THEN "I_CATEGORY00" ELSE NULL END AS "$f11"
FROM (SELECT *
FROM (SELECT SUM("STORE_SALES"."SS_NET_PROFIT") / SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f4", "ITEM"."I_CATEGORY" AS "I_CATEGORY00", "ITEM"."I_CLASS" AS "I_CLASS00", 0 AS "$f7", 0 AS "$f8", 0 AS "$f9"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."ITEM",
"tpcds"."STORE"
WHERE "DATE_DIM"."D_YEAR" = 1998 AND "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "ITEM"."I_ITEM_SK" = "STORE_SALES"."SS_ITEM_SK" AND "STORE"."S_STORE_SK" = "STORE_SALES"."SS_STORE_SK" AND "STORE"."S_STATE" = 'TN'
GROUP BY "ITEM"."I_CATEGORY", "ITEM"."I_CLASS"
UNION
SELECT SUM("t6"."$f20") / SUM("t6"."$f30") AS "$f3", "t6"."I_CATEGORY00" AS "I_CATEGORY000", CAST(NULL AS CHAR(50)) AS "$f5", 0 AS "$f6", 1 AS "$f7", 1 AS "$f8"
FROM (SELECT "ITEM0"."I_CATEGORY" AS "I_CATEGORY00", SUM("STORE_SALES0"."SS_NET_PROFIT") AS "$f20", SUM("STORE_SALES0"."SS_EXT_SALES_PRICE") AS "$f30"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."ITEM" AS "ITEM0",
"tpcds"."STORE" AS "STORE0"
WHERE "DATE_DIM0"."D_YEAR" = 1998 AND "DATE_DIM0"."D_DATE_SK" = "STORE_SALES0"."SS_SOLD_DATE_SK" AND "ITEM0"."I_ITEM_SK" = "STORE_SALES0"."SS_ITEM_SK" AND "STORE0"."S_STORE_SK" = "STORE_SALES0"."SS_STORE_SK" AND "STORE0"."S_STATE" = 'TN'
GROUP BY "ITEM0"."I_CATEGORY", "ITEM0"."I_CLASS") AS "t6"
GROUP BY "t6"."I_CATEGORY00")
UNION
SELECT SUM(SUM("STORE_SALES1"."SS_NET_PROFIT")) / SUM(SUM("STORE_SALES1"."SS_EXT_SALES_PRICE")) AS "$f2", CAST(NULL AS CHAR(50)) AS "$f3", CAST(NULL AS CHAR(50)) AS "$f4", 1 AS "$f5", 1 AS "$f6", 2 AS "$f7"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."ITEM" AS "ITEM1",
"tpcds"."STORE" AS "STORE1"
WHERE "DATE_DIM1"."D_YEAR" = 1998 AND "DATE_DIM1"."D_DATE_SK" = "STORE_SALES1"."SS_SOLD_DATE_SK" AND "ITEM1"."I_ITEM_SK" = "STORE_SALES1"."SS_ITEM_SK" AND "STORE1"."S_STORE_SK" = "STORE_SALES1"."SS_STORE_SK" AND "STORE1"."S_STATE" = 'TN'
GROUP BY "ITEM1"."I_CATEGORY", "ITEM1"."I_CLASS") AS "t16"
ORDER BY "$f9" DESC, 6, 5
FETCH NEXT 100 ROWS ONLY) AS "t18"
