SELECT "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "ITEM"."I_CURRENT_PRICE"
FROM "tpcds"."ITEM",
"tpcds"."INVENTORY",
"tpcds"."DATE_DIM",
"tpcds"."CATALOG_SALES"
WHERE CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) >= 29.00 AND CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) <= CAST(29 + 30 AS DECIMAL(12, 2)) AND ("INVENTORY"."INV_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "DATE_DIM"."D_DATE_SK" = "INVENTORY"."INV_DATE_SK") AND ("DATE_DIM"."D_DATE" >= DATE '2000-02-01' AND "DATE_DIM"."D_DATE" <= (DATE '2000-02-01' + INTERVAL '60 days') AND ("ITEM"."I_MANUFACT_ID" IN (677, 694, 808, 940) AND ("INVENTORY"."INV_QUANTITY_ON_HAND" >= 100 AND "INVENTORY"."INV_QUANTITY_ON_HAND" <= 500 AND "CATALOG_SALES"."CS_ITEM_SK" = "ITEM"."I_ITEM_SK")))
GROUP BY "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "ITEM"."I_CURRENT_PRICE"
ORDER BY "ITEM"."I_ITEM_ID"
FETCH NEXT 100 ROWS ONLY
