SELECT COUNT(*)
FROM (SELECT *
FROM (SELECT "CUSTOMER"."C_LAST_NAME" AS "C_LAST_NAME0", "CUSTOMER"."C_FIRST_NAME" AS "C_FIRST_NAME0", "DATE_DIM"."D_DATE" AS "D_DATE0"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_FIRST_NAME", "DATE_DIM"."D_DATE"
INTERSECT
SELECT "CUSTOMER0"."C_LAST_NAME" AS "C_LAST_NAME0", "CUSTOMER0"."C_FIRST_NAME" AS "C_FIRST_NAME0", "DATE_DIM0"."D_DATE" AS "D_DATE0"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CUSTOMER" AS "CUSTOMER0"
WHERE "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" = "CUSTOMER0"."C_CUSTOMER_SK" AND "DATE_DIM0"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM0"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "CUSTOMER0"."C_LAST_NAME", "CUSTOMER0"."C_FIRST_NAME", "DATE_DIM0"."D_DATE")
INTERSECT
SELECT "CUSTOMER1"."C_LAST_NAME" AS "C_LAST_NAME0", "CUSTOMER1"."C_FIRST_NAME" AS "C_FIRST_NAME0", "DATE_DIM1"."D_DATE" AS "D_DATE0"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."CUSTOMER" AS "CUSTOMER1"
WHERE "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "WEB_SALES"."WS_BILL_CUSTOMER_SK" = "CUSTOMER1"."C_CUSTOMER_SK" AND "DATE_DIM1"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM1"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "CUSTOMER1"."C_LAST_NAME", "CUSTOMER1"."C_FIRST_NAME", "DATE_DIM1"."D_DATE") AS "t9"
FETCH NEXT 100 ROWS ONLY
