SELECT "t4"."W_WAREHOUSE_SK00" AS "W_WAREHOUSE_SK", "t4"."I_ITEM_SK00" AS "I_ITEM_SK", "t4"."D_MOY00" AS "D_MOY", "t4"."$f400" AS "MEAN", "t4"."$f12" AS "COV", "t10"."W_WAREHOUSE_SK00" AS "W_WAREHOUSE_SK_2", "t10"."I_ITEM_SK00" AS "I_ITEM_SK_2", "t10"."D_MOY00" AS "D_MOY_2", "t10"."$f400" AS "MEAN_2", "t10"."$f12" AS "COV_2"
FROM (SELECT "W_WAREHOUSE_NAME0" AS "W_WAREHOUSE_NAME00", "W_WAREHOUSE_SK0" AS "W_WAREHOUSE_SK00", "I_ITEM_SK0" AS "I_ITEM_SK00", "D_MOY0" AS "D_MOY00", "$f4" AS "$f41", "$f40" AS "$f400", CASE WHEN "$f40" = 0 THEN NULL ELSE "$f4" / "$f40" END AS "$f12"
FROM (SELECT "WAREHOUSE"."W_WAREHOUSE_NAME" AS "W_WAREHOUSE_NAME0", "WAREHOUSE"."W_WAREHOUSE_SK" AS "W_WAREHOUSE_SK0", "ITEM"."I_ITEM_SK" AS "I_ITEM_SK0", "DATE_DIM"."D_MOY" AS "D_MOY0", AVG("INVENTORY"."INV_QUANTITY_ON_HAND") AS "$f4", AVG("INVENTORY"."INV_QUANTITY_ON_HAND") AS "$f40"
FROM "tpcds"."INVENTORY",
"tpcds"."ITEM",
"tpcds"."WAREHOUSE",
"tpcds"."DATE_DIM"
WHERE "INVENTORY"."INV_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "INVENTORY"."INV_WAREHOUSE_SK" = "WAREHOUSE"."W_WAREHOUSE_SK" AND "INVENTORY"."INV_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_YEAR" = 2001
GROUP BY "WAREHOUSE"."W_WAREHOUSE_NAME", "WAREHOUSE"."W_WAREHOUSE_SK", "ITEM"."I_ITEM_SK", "DATE_DIM"."D_MOY") AS "t2"
WHERE CASE WHEN "t2"."$f40" = 0 THEN 0 ELSE "t2"."$f4" / "t2"."$f40" END > 1) AS "t4",
(SELECT "W_WAREHOUSE_NAME0" AS "W_WAREHOUSE_NAME00", "W_WAREHOUSE_SK0" AS "W_WAREHOUSE_SK00", "I_ITEM_SK0" AS "I_ITEM_SK00", "D_MOY0" AS "D_MOY00", "$f4" AS "$f41", "$f40" AS "$f400", CASE WHEN "$f40" = 0 THEN NULL ELSE "$f4" / "$f40" END AS "$f12"
FROM (SELECT "WAREHOUSE0"."W_WAREHOUSE_NAME" AS "W_WAREHOUSE_NAME0", "WAREHOUSE0"."W_WAREHOUSE_SK" AS "W_WAREHOUSE_SK0", "ITEM0"."I_ITEM_SK" AS "I_ITEM_SK0", "DATE_DIM0"."D_MOY" AS "D_MOY0", AVG("INVENTORY0"."INV_QUANTITY_ON_HAND") AS "$f4", AVG("INVENTORY0"."INV_QUANTITY_ON_HAND") AS "$f40"
FROM "tpcds"."INVENTORY" AS "INVENTORY0",
"tpcds"."ITEM" AS "ITEM0",
"tpcds"."WAREHOUSE" AS "WAREHOUSE0",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "INVENTORY0"."INV_ITEM_SK" = "ITEM0"."I_ITEM_SK" AND "INVENTORY0"."INV_WAREHOUSE_SK" = "WAREHOUSE0"."W_WAREHOUSE_SK" AND "INVENTORY0"."INV_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_YEAR" = 2001
GROUP BY "WAREHOUSE0"."W_WAREHOUSE_NAME", "WAREHOUSE0"."W_WAREHOUSE_SK", "ITEM0"."I_ITEM_SK", "DATE_DIM0"."D_MOY") AS "t8"
WHERE CASE WHEN "t8"."$f40" = 0 THEN 0 ELSE "t8"."$f4" / "t8"."$f40" END > 1) AS "t10"
WHERE "t4"."I_ITEM_SK00" = "t10"."I_ITEM_SK00" AND "t4"."W_WAREHOUSE_SK00" = "t10"."W_WAREHOUSE_SK00" AND "t4"."D_MOY00" = 1 AND "t10"."D_MOY00" = 1 + 1
ORDER BY "t4"."W_WAREHOUSE_SK00", "t4"."I_ITEM_SK00", "t4"."D_MOY00", "t4"."$f400", "t4"."$f12", "t10"."D_MOY00", "t10"."$f400", "t10"."$f12"
