SELECT "WAREHOUSE"."W_STATE", "ITEM"."I_ITEM_ID", SUM(CASE WHEN "DATE_DIM"."D_DATE" < DATE '2000-03-11' THEN "CATALOG_SALES"."CS_SALES_PRICE" - CASE WHEN "CATALOG_RETURNS"."CR_REFUNDED_CASH" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_REFUNDED_CASH" AS DECIMAL(12, 2)) ELSE 0.00 END ELSE 0.00 END) AS "SALES_BEFORE", SUM(CASE WHEN "DATE_DIM"."D_DATE" >= DATE '2000-03-11' THEN "CATALOG_SALES"."CS_SALES_PRICE" - CASE WHEN "CATALOG_RETURNS"."CR_REFUNDED_CASH" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_REFUNDED_CASH" AS DECIMAL(12, 2)) ELSE 0.00 END ELSE 0.00 END) AS "SALES_AFTER"
FROM "tpcds"."CATALOG_SALES"
LEFT JOIN "tpcds"."CATALOG_RETURNS" ON "CATALOG_SALES"."CS_ORDER_NUMBER" = "CATALOG_RETURNS"."CR_ORDER_NUMBER" AND "CATALOG_SALES"."CS_ITEM_SK" = "CATALOG_RETURNS"."CR_ITEM_SK"
CROSS JOIN "tpcds"."WAREHOUSE"
CROSS JOIN "tpcds"."ITEM"
CROSS JOIN "tpcds"."DATE_DIM"
WHERE "ITEM"."I_CURRENT_PRICE" >= 0.99 AND "ITEM"."I_CURRENT_PRICE" <= 1.49 AND ("ITEM"."I_ITEM_SK" = "CATALOG_SALES"."CS_ITEM_SK" AND "CATALOG_SALES"."CS_WAREHOUSE_SK" = "WAREHOUSE"."W_WAREHOUSE_SK") AND ("CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("DATE_DIM"."D_DATE" >= (DATE '2000-03-11' - INTERVAL '30 days') AND "DATE_DIM"."D_DATE" <= (DATE '2000-03-11' + INTERVAL '30 days')))
GROUP BY "WAREHOUSE"."W_STATE", "ITEM"."I_ITEM_ID"
ORDER BY "WAREHOUSE"."W_STATE", "ITEM"."I_ITEM_ID"
FETCH NEXT 100 ROWS ONLY
