SELECT "t2"."D_YEAR0" AS "D_YEAR", "t2"."I_CATEGORY_ID0" AS "I_CATEGORY_ID", "t2"."I_CATEGORY0" AS "I_CATEGORY", "t2"."$f3"
FROM (SELECT "DATE_DIM"."D_YEAR" AS "D_YEAR0", "ITEM"."I_CATEGORY_ID" AS "I_CATEGORY_ID0", "ITEM"."I_CATEGORY" AS "I_CATEGORY0", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f3"
FROM "tpcds"."DATE_DIM",
"tpcds"."STORE_SALES",
"tpcds"."ITEM"
WHERE "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "ITEM"."I_MANAGER_ID" = 1 AND "DATE_DIM"."D_MOY" = 12 AND "DATE_DIM"."D_YEAR" = 2001
GROUP BY "DATE_DIM"."D_YEAR", "ITEM"."I_CATEGORY_ID", "ITEM"."I_CATEGORY"
ORDER BY 4 DESC, "DATE_DIM"."D_YEAR", "ITEM"."I_CATEGORY_ID", "ITEM"."I_CATEGORY"
FETCH NEXT 100 ROWS ONLY) AS "t2"
