SELECT "t2"."S_STORE_NAME0" AS "S_STORE_NAME", "t2"."S_STORE_ID0" AS "S_STORE_ID", "t2"."$f2" AS "SUN_SALES", "t2"."$f3" AS "MON_SALES", "t2"."$f4" AS "TUE_SALES", "t2"."$f5" AS "WED_SALES", "t2"."$f6" AS "THU_SALES", "t2"."$f7" AS "FRI_SALES", "t2"."$f8" AS "SAT_SALES"
FROM (SELECT "STORE"."S_STORE_NAME" AS "S_STORE_NAME0", "STORE"."S_STORE_ID" AS "S_STORE_ID0", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Sunday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f2", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Monday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f3", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Tuesday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f4", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Wednesday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f5", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Thursday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f6", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Friday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f7", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Saturday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f8"
FROM "tpcds"."DATE_DIM",
"tpcds"."STORE_SALES",
"tpcds"."STORE"
WHERE "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "STORE"."S_STORE_SK" = "STORE_SALES"."SS_STORE_SK" AND CAST("STORE"."S_GMT_OFFSET" AS DECIMAL(12, 2)) = -5.00 AND "DATE_DIM"."D_YEAR" = 2001
GROUP BY "STORE"."S_STORE_NAME", "STORE"."S_STORE_ID"
ORDER BY "STORE"."S_STORE_NAME", "STORE"."S_STORE_ID", 3, 4, 5, 6, 7, 8, 9
FETCH NEXT 100 ROWS ONLY) AS "t2"
