SELECT "t8"."$f3" AS "RNK", "ITEM"."I_PRODUCT_NAME" AS "BEST_PERFORMING", "ITEM0"."I_PRODUCT_NAME" AS "WORST_PERFORMING"
FROM (SELECT *
FROM (SELECT "SS_ITEM_SK" AS "SS_ITEM_SK00", RANK() OVER (ORDER BY AVG("SS_NET_PROFIT")) AS "$f3"
FROM "tpcds"."STORE_SALES"
WHERE "SS_STORE_SK" = 49
GROUP BY "SS_ITEM_SK"
HAVING CAST(AVG("SS_NET_PROFIT") AS DECIMAL(9, 3)) > 0.9 * (((SELECT AVG("SS_NET_PROFIT") AS "$f10"
FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS "t" ("SS_SOLD_DATE_SK", "SS_SOLD_TIME_SK", "SS_ITEM_SK", "SS_CUSTOMER_SK", "SS_CDEMO_SK", "SS_HDEMO_SK", "SS_ADDR_SK", "SS_STORE_SK", "SS_PROMO_SK", "SS_TICKET_NUMBER", "SS_QUANTITY", "SS_WHOLESALE_COST", "SS_LIST_PRICE", "SS_SALES_PRICE", "SS_EXT_DISCOUNT_AMT", "SS_EXT_SALES_PRICE", "SS_EXT_WHOLESALE_COST", "SS_EXT_LIST_PRICE", "SS_EXT_TAX", "SS_COUPON_AMT", "SS_NET_PAID", "SS_NET_PAID_INC_TAX", "SS_NET_PROFIT")
WHERE 1 = 0
GROUP BY "SS_STORE_SK")))) AS "t7"
WHERE "$f3" < 11) AS "t8",
(SELECT *
FROM (SELECT "SS_ITEM_SK" AS "SS_ITEM_SK00", RANK() OVER (ORDER BY AVG("SS_NET_PROFIT") DESC) AS "$f3"
FROM "tpcds"."STORE_SALES"
WHERE "SS_STORE_SK" = 49
GROUP BY "SS_ITEM_SK"
HAVING CAST(AVG("SS_NET_PROFIT") AS DECIMAL(9, 3)) > 0.9 * (((SELECT AVG("SS_NET_PROFIT") AS "$f10"
FROM (VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)) AS "t" ("SS_SOLD_DATE_SK", "SS_SOLD_TIME_SK", "SS_ITEM_SK", "SS_CUSTOMER_SK", "SS_CDEMO_SK", "SS_HDEMO_SK", "SS_ADDR_SK", "SS_STORE_SK", "SS_PROMO_SK", "SS_TICKET_NUMBER", "SS_QUANTITY", "SS_WHOLESALE_COST", "SS_LIST_PRICE", "SS_SALES_PRICE", "SS_EXT_DISCOUNT_AMT", "SS_EXT_SALES_PRICE", "SS_EXT_WHOLESALE_COST", "SS_EXT_LIST_PRICE", "SS_EXT_TAX", "SS_COUPON_AMT", "SS_NET_PAID", "SS_NET_PAID_INC_TAX", "SS_NET_PROFIT")
WHERE 1 = 0
GROUP BY "SS_STORE_SK")))) AS "t17"
WHERE "$f3" < 11) AS "t18",
"tpcds"."ITEM",
"tpcds"."ITEM" AS "ITEM0"
WHERE "t8"."$f3" = "t18"."$f3" AND "ITEM"."I_ITEM_SK" = "t8"."SS_ITEM_SK00" AND "ITEM0"."I_ITEM_SK" = "t18"."SS_ITEM_SK00"
ORDER BY "t8"."$f3"
FETCH NEXT 100 ROWS ONLY
