SELECT "CUSTOMER_ADDRESS"."CA_ZIP", "CUSTOMER_ADDRESS"."CA_CITY", SUM("WEB_SALES"."WS_SALES_PRICE")
FROM "tpcds"."WEB_SALES",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."DATE_DIM",
"tpcds"."ITEM"
WHERE "WEB_SALES"."WS_BILL_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND ("CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND "WEB_SALES"."WS_ITEM_SK" = "ITEM"."I_ITEM_SK") AND ((SUBSTRING("CUSTOMER_ADDRESS"."CA_ZIP", 1, 5) IN ('80348', '81792', '83405', '85392', '85460', '85669', '86197', '86475', '88274') OR "ITEM"."I_ITEM_ID" IN (SELECT "I_ITEM_ID" AS "I_ITEM_ID0"
FROM "tpcds"."ITEM"
WHERE "I_ITEM_SK" IN (2, 3, 5, 7, 11, 13, 17, 19, 23, 29))) AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("DATE_DIM"."D_QOY" = 1 AND "DATE_DIM"."D_YEAR" = 2001))
GROUP BY "CUSTOMER_ADDRESS"."CA_ZIP", "CUSTOMER_ADDRESS"."CA_CITY"
ORDER BY "CUSTOMER_ADDRESS"."CA_ZIP", "CUSTOMER_ADDRESS"."CA_CITY"
FETCH NEXT 100 ROWS ONLY
