SELECT "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER_ADDRESS0"."CA_CITY", "t2"."CA_CITY00" AS "BOUGHT_CITY", "t2"."SS_TICKET_NUMBER00" AS "SS_TICKET_NUMBER", "t2"."$f40" AS "AMT", "t2"."$f50" AS "PROFIT"
FROM (SELECT "STORE_SALES"."SS_TICKET_NUMBER" AS "SS_TICKET_NUMBER00", "STORE_SALES"."SS_CUSTOMER_SK" AS "SS_CUSTOMER_SK00", "CUSTOMER_ADDRESS"."CA_CITY" AS "CA_CITY00", SUM("STORE_SALES"."SS_COUPON_AMT") AS "$f40", SUM("STORE_SALES"."SS_NET_PROFIT") AS "$f50"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS",
"tpcds"."CUSTOMER_ADDRESS"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND ("STORE_SALES"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" AND "STORE_SALES"."SS_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK") AND (("HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" = 0 OR "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" = 0) AND "DATE_DIM"."D_DOW" IN (0, 6) AND (("DATE_DIM"."D_YEAR" = 1999 OR "DATE_DIM"."D_YEAR" = 1999 + 1 OR "DATE_DIM"."D_YEAR" = 1999 + 2) AND "STORE"."S_CITY" IN ('distmember(cities, [CITYNUMBER.1], 1)', 'distmember(cities, [CITYNUMBER.2], 1)', 'distmember(cities, [CITYNUMBER.3], 1)', 'distmember(cities, [CITYNUMBER.4], 1)', 'distmember(cities, [CITYNUMBER.5], 1)')))
GROUP BY "STORE_SALES"."SS_TICKET_NUMBER", "STORE_SALES"."SS_CUSTOMER_SK", "STORE_SALES"."SS_ADDR_SK", "CUSTOMER_ADDRESS"."CA_CITY") AS "t2",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0"
WHERE "t2"."SS_CUSTOMER_SK00" = "CUSTOMER"."C_CUSTOMER_SK" AND "CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS0"."CA_ADDRESS_SK" AND "CUSTOMER_ADDRESS0"."CA_CITY" <> "t2"."CA_CITY00"
ORDER BY "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER_ADDRESS0"."CA_CITY", "t2"."CA_CITY00", "t2"."SS_TICKET_NUMBER00"
FETCH NEXT 100 ROWS ONLY
