SELECT "I_BRAND0020" AS "I_BRAND", "D_YEAR0020" AS "D_YEAR", "$f1420" AS "AVG_MONTHLY_SALES", "$f6020" AS "SUM_SALES", "$f60000" AS "PSUM", "$f60100" AS "NSUM"
FROM (SELECT "I_BRAND002" AS "I_BRAND0020", "D_YEAR002" AS "D_YEAR0020", "$f142" AS "$f1420", "$f602" AS "$f6020", "$f6000" AS "$f60000", "$f6010" AS "$f60100", "$f602" - "$f142" AS "$f12"
FROM (SELECT "t2"."I_BRAND00" AS "I_BRAND002", "t2"."D_YEAR00" AS "D_YEAR002", "t2"."$f14" AS "$f142", "t2"."$f60" AS "$f602", "t6"."$f60" AS "$f6000", "t10"."$f60" AS "$f6010"
FROM (SELECT "ITEM"."I_CATEGORY" AS "I_CATEGORY00", "ITEM"."I_BRAND" AS "I_BRAND00", "STORE"."S_STORE_NAME" AS "S_STORE_NAME00", "STORE"."S_COMPANY_NAME" AS "S_COMPANY_NAME00", "DATE_DIM"."D_YEAR" AS "D_YEAR00", "DATE_DIM"."D_MOY" AS "D_MOY00", SUM("STORE_SALES"."SS_SALES_PRICE") AS "$f60", AVG(SUM("STORE_SALES"."SS_SALES_PRICE")) OVER (PARTITION BY "ITEM"."I_CATEGORY", "ITEM"."I_BRAND", "STORE"."S_STORE_NAME", "STORE"."S_COMPANY_NAME", "DATE_DIM"."D_YEAR" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f14", RANK() OVER (PARTITION BY "ITEM"."I_CATEGORY", "ITEM"."I_BRAND", "STORE"."S_STORE_NAME", "STORE"."S_COMPANY_NAME" ORDER BY "DATE_DIM"."D_YEAR", "DATE_DIM"."D_MOY") AS "$f15"
FROM "tpcds"."ITEM",
"tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE"
WHERE "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND ("DATE_DIM"."D_YEAR" = 1999 OR "DATE_DIM"."D_YEAR" = 1999 - 1 AND "DATE_DIM"."D_MOY" = 12 OR "DATE_DIM"."D_YEAR" = 1999 + 1 AND "DATE_DIM"."D_MOY" = 1)
GROUP BY "ITEM"."I_CATEGORY", "ITEM"."I_BRAND", "STORE"."S_STORE_NAME", "STORE"."S_COMPANY_NAME", "DATE_DIM"."D_YEAR", "DATE_DIM"."D_MOY") AS "t2",
(SELECT "ITEM0"."I_CATEGORY" AS "I_CATEGORY00", "ITEM0"."I_BRAND" AS "I_BRAND00", "STORE0"."S_STORE_NAME" AS "S_STORE_NAME00", "STORE0"."S_COMPANY_NAME" AS "S_COMPANY_NAME00", "DATE_DIM0"."D_YEAR" AS "D_YEAR00", "DATE_DIM0"."D_MOY" AS "D_MOY00", SUM("STORE_SALES0"."SS_SALES_PRICE") AS "$f60", AVG(SUM("STORE_SALES0"."SS_SALES_PRICE")) OVER (PARTITION BY "ITEM0"."I_CATEGORY", "ITEM0"."I_BRAND", "STORE0"."S_STORE_NAME", "STORE0"."S_COMPANY_NAME", "DATE_DIM0"."D_YEAR" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f14", RANK() OVER (PARTITION BY "ITEM0"."I_CATEGORY", "ITEM0"."I_BRAND", "STORE0"."S_STORE_NAME", "STORE0"."S_COMPANY_NAME" ORDER BY "DATE_DIM0"."D_YEAR", "DATE_DIM0"."D_MOY") AS "$f15"
FROM "tpcds"."ITEM" AS "ITEM0",
"tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."STORE" AS "STORE0"
WHERE "STORE_SALES0"."SS_ITEM_SK" = "ITEM0"."I_ITEM_SK" AND "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "STORE_SALES0"."SS_STORE_SK" = "STORE0"."S_STORE_SK" AND ("DATE_DIM0"."D_YEAR" = 1999 OR "DATE_DIM0"."D_YEAR" = 1999 - 1 AND "DATE_DIM0"."D_MOY" = 12 OR "DATE_DIM0"."D_YEAR" = 1999 + 1 AND "DATE_DIM0"."D_MOY" = 1)
GROUP BY "ITEM0"."I_CATEGORY", "ITEM0"."I_BRAND", "STORE0"."S_STORE_NAME", "STORE0"."S_COMPANY_NAME", "DATE_DIM0"."D_YEAR", "DATE_DIM0"."D_MOY") AS "t6",
(SELECT "ITEM1"."I_CATEGORY" AS "I_CATEGORY00", "ITEM1"."I_BRAND" AS "I_BRAND00", "STORE1"."S_STORE_NAME" AS "S_STORE_NAME00", "STORE1"."S_COMPANY_NAME" AS "S_COMPANY_NAME00", "DATE_DIM1"."D_YEAR" AS "D_YEAR00", "DATE_DIM1"."D_MOY" AS "D_MOY00", SUM("STORE_SALES1"."SS_SALES_PRICE") AS "$f60", AVG(SUM("STORE_SALES1"."SS_SALES_PRICE")) OVER (PARTITION BY "ITEM1"."I_CATEGORY", "ITEM1"."I_BRAND", "STORE1"."S_STORE_NAME", "STORE1"."S_COMPANY_NAME", "DATE_DIM1"."D_YEAR" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f14", RANK() OVER (PARTITION BY "ITEM1"."I_CATEGORY", "ITEM1"."I_BRAND", "STORE1"."S_STORE_NAME", "STORE1"."S_COMPANY_NAME" ORDER BY "DATE_DIM1"."D_YEAR", "DATE_DIM1"."D_MOY") AS "$f15"
FROM "tpcds"."ITEM" AS "ITEM1",
"tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."STORE" AS "STORE1"
WHERE "STORE_SALES1"."SS_ITEM_SK" = "ITEM1"."I_ITEM_SK" AND "STORE_SALES1"."SS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "STORE_SALES1"."SS_STORE_SK" = "STORE1"."S_STORE_SK" AND ("DATE_DIM1"."D_YEAR" = 1999 OR "DATE_DIM1"."D_YEAR" = 1999 - 1 AND "DATE_DIM1"."D_MOY" = 12 OR "DATE_DIM1"."D_YEAR" = 1999 + 1 AND "DATE_DIM1"."D_MOY" = 1)
GROUP BY "ITEM1"."I_CATEGORY", "ITEM1"."I_BRAND", "STORE1"."S_STORE_NAME", "STORE1"."S_COMPANY_NAME", "DATE_DIM1"."D_YEAR", "DATE_DIM1"."D_MOY") AS "t10"
WHERE "t2"."I_CATEGORY00" = "t6"."I_CATEGORY00" AND "t2"."I_CATEGORY00" = "t10"."I_CATEGORY00" AND ("t2"."I_BRAND00" = "t6"."I_BRAND00" AND ("t2"."I_BRAND00" = "t10"."I_BRAND00" AND "t2"."S_STORE_NAME00" = "t6"."S_STORE_NAME00")) AND ("t2"."S_STORE_NAME00" = "t10"."S_STORE_NAME00" AND "t2"."S_COMPANY_NAME00" = "t6"."S_COMPANY_NAME00" AND ("t2"."S_COMPANY_NAME00" = "t10"."S_COMPANY_NAME00" AND ("t2"."$f15" = "t6"."$f15" + 1 AND "t2"."$f15" = "t10"."$f15" - 1)))) AS "t12"
WHERE "t12"."D_YEAR002" = 1999 AND CAST("t12"."$f142" AS DECIMAL(12, 2)) > 0.00 AND CASE WHEN CAST("t12"."$f142" AS DECIMAL(12, 2)) > 0.00 THEN ABS("t12"."$f602" - "t12"."$f142") / "t12"."$f142" ELSE NULL END > 0.100000
ORDER BY 7, "$f142"
FETCH NEXT 100 ROWS ONLY) AS "t15"
