SELECT "$f5" AS "CHANNEL", "WS_ITEM_SK000" AS "ITEM", "$f60" AS "RETURN_RATIO", "$f80" AS "RETURN_RANK", "$f90" AS "CURRENCY_RANK"
FROM (SELECT *
FROM (SELECT 'web' AS "$f5", "WS_ITEM_SK00" AS "WS_ITEM_SK000", "$f6" AS "$f60", "$f8" AS "$f80", "$f9" AS "$f90"
FROM (SELECT "WEB_SALES"."WS_ITEM_SK" AS "WS_ITEM_SK00", CAST(SUM(CASE WHEN "WEB_RETURNS"."WR_RETURN_QUANTITY" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END) AS DECIMAL(15, 4)) / CAST(SUM("WEB_SALES"."WS_QUANTITY") AS DECIMAL(15, 4)) AS "$f6", CAST(SUM(CASE WHEN "WEB_RETURNS"."WR_RETURN_AMT" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_RETURN_AMT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS DECIMAL(15, 4)) / CAST(SUM(CAST("WEB_SALES"."WS_NET_PAID" AS DECIMAL(12, 2))) AS DECIMAL(15, 4)) AS "$f7", RANK() OVER (ORDER BY CAST(SUM(CASE WHEN "WEB_RETURNS"."WR_RETURN_QUANTITY" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END) AS DECIMAL(15, 4)) / CAST(SUM("WEB_SALES"."WS_QUANTITY") AS DECIMAL(15, 4))) AS "$f8", RANK() OVER (ORDER BY CAST(SUM(CASE WHEN "WEB_RETURNS"."WR_RETURN_AMT" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_RETURN_AMT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS DECIMAL(15, 4)) / CAST(SUM(CAST("WEB_SALES"."WS_NET_PAID" AS DECIMAL(12, 2))) AS DECIMAL(15, 4))) AS "$f9"
FROM "tpcds"."WEB_SALES"
LEFT JOIN "tpcds"."WEB_RETURNS" ON "WEB_SALES"."WS_ORDER_NUMBER" = "WEB_RETURNS"."WR_ORDER_NUMBER" AND "WEB_SALES"."WS_ITEM_SK" = "WEB_RETURNS"."WR_ITEM_SK"
CROSS JOIN "tpcds"."DATE_DIM"
WHERE CAST("WEB_RETURNS"."WR_RETURN_AMT" AS DECIMAL(12, 2)) > 10000.00 AND (CAST("WEB_SALES"."WS_NET_PROFIT" AS DECIMAL(12, 2)) > 1.00 AND CAST("WEB_SALES"."WS_NET_PAID" AS DECIMAL(12, 2)) > 0.00) AND ("WEB_SALES"."WS_QUANTITY" > 0 AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("DATE_DIM"."D_YEAR" = 1998 AND "DATE_DIM"."D_MOY" = 12))
GROUP BY "WEB_SALES"."WS_ITEM_SK") AS "t2"
WHERE "t2"."$f8" <= 10 OR "t2"."$f9" <= 10
UNION
SELECT 'catalog' AS "$f5", "CS_ITEM_SK00" AS "CS_ITEM_SK000", "$f6" AS "$f60", "$f8" AS "$f80", "$f9" AS "$f90"
FROM (SELECT "CATALOG_SALES"."CS_ITEM_SK" AS "CS_ITEM_SK00", CAST(SUM(CASE WHEN "CATALOG_RETURNS"."CR_RETURN_QUANTITY" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END) AS DECIMAL(15, 4)) / CAST(SUM("CATALOG_SALES"."CS_QUANTITY") AS DECIMAL(15, 4)) AS "$f6", CAST(SUM(CASE WHEN "CATALOG_RETURNS"."CR_RETURN_AMOUNT" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_RETURN_AMOUNT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS DECIMAL(15, 4)) / CAST(SUM(CAST("CATALOG_SALES"."CS_NET_PAID" AS DECIMAL(12, 2))) AS DECIMAL(15, 4)) AS "$f7", RANK() OVER (ORDER BY CAST(SUM(CASE WHEN "CATALOG_RETURNS"."CR_RETURN_QUANTITY" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END) AS DECIMAL(15, 4)) / CAST(SUM("CATALOG_SALES"."CS_QUANTITY") AS DECIMAL(15, 4))) AS "$f8", RANK() OVER (ORDER BY CAST(SUM(CASE WHEN "CATALOG_RETURNS"."CR_RETURN_AMOUNT" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_RETURN_AMOUNT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS DECIMAL(15, 4)) / CAST(SUM(CAST("CATALOG_SALES"."CS_NET_PAID" AS DECIMAL(12, 2))) AS DECIMAL(15, 4))) AS "$f9"
FROM "tpcds"."CATALOG_SALES"
LEFT JOIN "tpcds"."CATALOG_RETURNS" ON "CATALOG_SALES"."CS_ORDER_NUMBER" = "CATALOG_RETURNS"."CR_ORDER_NUMBER" AND "CATALOG_SALES"."CS_ITEM_SK" = "CATALOG_RETURNS"."CR_ITEM_SK"
CROSS JOIN "tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE CAST("CATALOG_RETURNS"."CR_RETURN_AMOUNT" AS DECIMAL(12, 2)) > 10000.00 AND (CAST("CATALOG_SALES"."CS_NET_PROFIT" AS DECIMAL(12, 2)) > 1.00 AND CAST("CATALOG_SALES"."CS_NET_PAID" AS DECIMAL(12, 2)) > 0.00) AND ("CATALOG_SALES"."CS_QUANTITY" > 0 AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND ("DATE_DIM0"."D_YEAR" = 1998 AND "DATE_DIM0"."D_MOY" = 12))
GROUP BY "CATALOG_SALES"."CS_ITEM_SK") AS "t8"
WHERE "t8"."$f8" <= 10 OR "t8"."$f9" <= 10)
UNION
SELECT 'store' AS "$f5", "SS_ITEM_SK00" AS "SS_ITEM_SK000", "$f6" AS "$f60", "$f8" AS "$f80", "$f9" AS "$f90"
FROM (SELECT "STORE_SALES"."SS_ITEM_SK" AS "SS_ITEM_SK00", CAST(SUM(CASE WHEN "STORE_RETURNS"."SR_RETURN_QUANTITY" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END) AS DECIMAL(15, 4)) / CAST(SUM("STORE_SALES"."SS_QUANTITY") AS DECIMAL(15, 4)) AS "$f6", CAST(SUM(CASE WHEN "STORE_RETURNS"."SR_RETURN_AMT" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_RETURN_AMT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS DECIMAL(15, 4)) / CAST(SUM(CAST("STORE_SALES"."SS_NET_PAID" AS DECIMAL(12, 2))) AS DECIMAL(15, 4)) AS "$f7", RANK() OVER (ORDER BY CAST(SUM(CASE WHEN "STORE_RETURNS"."SR_RETURN_QUANTITY" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END) AS DECIMAL(15, 4)) / CAST(SUM("STORE_SALES"."SS_QUANTITY") AS DECIMAL(15, 4))) AS "$f8", RANK() OVER (ORDER BY CAST(SUM(CASE WHEN "STORE_RETURNS"."SR_RETURN_AMT" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_RETURN_AMT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS DECIMAL(15, 4)) / CAST(SUM(CAST("STORE_SALES"."SS_NET_PAID" AS DECIMAL(12, 2))) AS DECIMAL(15, 4))) AS "$f9"
FROM "tpcds"."STORE_SALES"
LEFT JOIN "tpcds"."STORE_RETURNS" ON "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER" AND "STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK"
CROSS JOIN "tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE CAST("STORE_RETURNS"."SR_RETURN_AMT" AS DECIMAL(12, 2)) > 10000.00 AND (CAST("STORE_SALES"."SS_NET_PROFIT" AS DECIMAL(12, 2)) > 1.00 AND CAST("STORE_SALES"."SS_NET_PAID" AS DECIMAL(12, 2)) > 0.00) AND ("STORE_SALES"."SS_QUANTITY" > 0 AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND ("DATE_DIM1"."D_YEAR" = 1998 AND "DATE_DIM1"."D_MOY" = 12))
GROUP BY "STORE_SALES"."SS_ITEM_SK") AS "t15"
WHERE "t15"."$f8" <= 10 OR "t15"."$f9" <= 10)
ORDER BY "$f5", "$f80", "$f90"
FETCH NEXT 100 ROWS ONLY
