SELECT "$f6" AS "ITEM_SK", "$f7" AS "D_DATE", "$f51" AS "WEB_SALES", "$f500" AS "STORE_SALES", "$f10" AS "WEB_CUMULATIVE", "$f11" AS "STORE_CUMULATIVE"
FROM (SELECT CASE WHEN "t2"."WS_ITEM_SK00" IS NOT NULL THEN "t2"."WS_ITEM_SK00" ELSE "t6"."SS_ITEM_SK00" END AS "$f6", CASE WHEN "t2"."D_DATE00" IS NOT NULL THEN "t2"."D_DATE00" ELSE "t6"."D_DATE00" END AS "$f7", "t2"."$f5" AS "$f51", "t6"."$f5" AS "$f500", MAX("t2"."$f5") OVER (PARTITION BY CASE WHEN "t2"."WS_ITEM_SK00" IS NOT NULL THEN "t2"."WS_ITEM_SK00" ELSE "t6"."SS_ITEM_SK00" END ORDER BY CASE WHEN "t2"."D_DATE00" IS NOT NULL THEN "t2"."D_DATE00" ELSE "t6"."D_DATE00" END ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "$f10", MAX("t6"."$f5") OVER (PARTITION BY CASE WHEN "t2"."WS_ITEM_SK00" IS NOT NULL THEN "t2"."WS_ITEM_SK00" ELSE "t6"."SS_ITEM_SK00" END ORDER BY CASE WHEN "t2"."D_DATE00" IS NOT NULL THEN "t2"."D_DATE00" ELSE "t6"."D_DATE00" END ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "$f11"
FROM (SELECT "WEB_SALES"."WS_ITEM_SK" AS "WS_ITEM_SK00", "DATE_DIM"."D_DATE" AS "D_DATE00", SUM(SUM("WEB_SALES"."WS_SALES_PRICE")) OVER (PARTITION BY "WEB_SALES"."WS_ITEM_SK" ORDER BY "DATE_DIM"."D_DATE" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "$f5"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM"
WHERE "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "WEB_SALES"."WS_ITEM_SK", "DATE_DIM"."D_DATE") AS "t2"
FULL JOIN (SELECT "STORE_SALES"."SS_ITEM_SK" AS "SS_ITEM_SK00", "DATE_DIM0"."D_DATE" AS "D_DATE00", SUM(SUM("STORE_SALES"."SS_SALES_PRICE")) OVER (PARTITION BY "STORE_SALES"."SS_ITEM_SK" ORDER BY "DATE_DIM0"."D_DATE" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "$f5"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM0"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "STORE_SALES"."SS_ITEM_SK", "DATE_DIM0"."D_DATE") AS "t6" ON "t2"."WS_ITEM_SK00" = "t6"."SS_ITEM_SK00" AND "t2"."D_DATE00" = "t6"."D_DATE00") AS "t7"
WHERE "t7"."$f10" > "t7"."$f11"
ORDER BY "$f6", "$f7"
FETCH NEXT 100 ROWS ONLY
