SELECT "t3"."D_YEAR00" AS "D_YEAR", "t3"."I_BRAND_ID00" AS "BRAND_ID", "t3"."I_BRAND00" AS "BRAND", "t3"."$f30" AS "EXT_PRICE"
FROM (SELECT "DATE_DIM"."D_YEAR" AS "D_YEAR00", "ITEM"."I_BRAND_ID" AS "I_BRAND_ID00", "ITEM"."I_BRAND" AS "I_BRAND00", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f30"
FROM "tpcds"."DATE_DIM",
"tpcds"."STORE_SALES",
"tpcds"."ITEM"
WHERE "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "ITEM"."I_MANAGER_ID" = 1 AND "DATE_DIM"."D_MOY" = 12 AND "DATE_DIM"."D_YEAR" = 2001
GROUP BY "DATE_DIM"."D_YEAR", "ITEM"."I_BRAND", "ITEM"."I_BRAND_ID"
ORDER BY "DATE_DIM"."D_YEAR", 4 DESC, "ITEM"."I_BRAND_ID"
FETCH NEXT 100 ROWS ONLY) AS "t3"
