SELECT "$f20" AS "SEGMENT", "$f10" AS "NUM_CUSTOMERS", "$f4" AS "SEGMENT_BASE"
FROM (SELECT "t14"."$f2" AS "$f20", COUNT(*) AS "$f10", "t14"."$f2" * 50 AS "$f4"
FROM (SELECT CAST(SUM("STORE_SALES"."SS_EXT_SALES_PRICE") / 50.00 AS INTEGER) AS "$f2"
FROM (SELECT "CUSTOMER"."C_CUSTOMER_SK" AS "C_CUSTOMER_SK0", "CUSTOMER"."C_CURRENT_ADDR_SK" AS "C_CURRENT_ADDR_SK0"
FROM (SELECT "CS_SOLD_DATE_SK" AS "CS_SOLD_DATE_SK0", "CS_BILL_CUSTOMER_SK" AS "CS_BILL_CUSTOMER_SK0", "CS_ITEM_SK" AS "CS_ITEM_SK0"
FROM "tpcds"."CATALOG_SALES"
UNION ALL
SELECT "WS_SOLD_DATE_SK" AS "WS_SOLD_DATE_SK0", "WS_BILL_CUSTOMER_SK" AS "WS_BILL_CUSTOMER_SK0", "WS_ITEM_SK" AS "WS_ITEM_SK0"
FROM "tpcds"."WEB_SALES") AS "t1",
"tpcds"."ITEM",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER"
WHERE "t1"."CS_SOLD_DATE_SK0" = "DATE_DIM"."D_DATE_SK" AND ("t1"."CS_ITEM_SK0" = "ITEM"."I_ITEM_SK" AND "ITEM"."I_CATEGORY" = 'distmember(categories,30,1)') AND ("ITEM"."I_CLASS" = 'dist(distmember(categories,30,2),1,1)' AND "CUSTOMER"."C_CUSTOMER_SK" = "t1"."CS_BILL_CUSTOMER_SK0" AND ("DATE_DIM"."D_MOY" = 3 AND "DATE_DIM"."D_YEAR" = 1998))
GROUP BY "CUSTOMER"."C_CUSTOMER_SK", "CUSTOMER"."C_CURRENT_ADDR_SK") AS "t4",
"tpcds"."STORE_SALES",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."STORE",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "t4"."C_CURRENT_ADDR_SK0" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND ("CUSTOMER_ADDRESS"."CA_COUNTY" = "STORE"."S_COUNTY" AND "CUSTOMER_ADDRESS"."CA_STATE" = "STORE"."S_STATE") AND ("STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "t4"."C_CUSTOMER_SK0" = "STORE_SALES"."SS_CUSTOMER_SK" AND ("DATE_DIM0"."D_MONTH_SEQ" >= (((SELECT "D_MONTH_SEQ" + 1 AS "$f28"
FROM "tpcds"."DATE_DIM"
WHERE "D_YEAR" = 1998 AND "D_MOY" = 3
GROUP BY "D_MONTH_SEQ" + 1))) AND "DATE_DIM0"."D_MONTH_SEQ" <= (((SELECT "D_MONTH_SEQ" + 3 AS "$f28"
FROM "tpcds"."DATE_DIM"
WHERE "D_YEAR" = 1998 AND "D_MOY" = 3
GROUP BY "D_MONTH_SEQ" + 3)))))
GROUP BY "t4"."C_CUSTOMER_SK0") AS "t14"
GROUP BY "t14"."$f2"
ORDER BY "t14"."$f2", 2
FETCH NEXT 100 ROWS ONLY) AS "t17"
