SELECT "t3"."I_BRAND_ID00" AS "BRAND_ID", "t3"."I_BRAND00" AS "BRAND", "t3"."$f20" AS "EXT_PRICE"
FROM (SELECT "ITEM"."I_BRAND_ID" AS "I_BRAND_ID00", "ITEM"."I_BRAND" AS "I_BRAND00", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f20"
FROM "tpcds"."DATE_DIM",
"tpcds"."STORE_SALES",
"tpcds"."ITEM"
WHERE "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "ITEM"."I_MANAGER_ID" = 30 AND "DATE_DIM"."D_MOY" = 12 AND "DATE_DIM"."D_YEAR" = 1998
GROUP BY "ITEM"."I_BRAND", "ITEM"."I_BRAND_ID"
ORDER BY 3 DESC, "ITEM"."I_BRAND_ID"
FETCH NEXT 100 ROWS ONLY) AS "t3"
