SELECT "I_CATEGORY0020" AS "I_CATEGORY", "I_BRAND0020" AS "I_BRAND", "D_YEAR0020" AS "D_YEAR", "$f1220" AS "AVG_MONTHLY_SALES", "$f5020" AS "SUM_SALES", "$f50000" AS "PSUM", "$f50100" AS "NSUM"
FROM (SELECT "I_CATEGORY002" AS "I_CATEGORY0020", "I_BRAND002" AS "I_BRAND0020", "D_YEAR002" AS "D_YEAR0020", "$f122" AS "$f1220", "$f502" AS "$f5020", "$f5000" AS "$f50000", "$f5010" AS "$f50100", "$f502" - "$f122" AS "$f14"
FROM (SELECT "t2"."I_CATEGORY00" AS "I_CATEGORY002", "t2"."I_BRAND00" AS "I_BRAND002", "t2"."D_YEAR00" AS "D_YEAR002", "t2"."$f12" AS "$f122", "t2"."$f50" AS "$f502", "t6"."$f50" AS "$f5000", "t10"."$f50" AS "$f5010"
FROM (SELECT "ITEM"."I_CATEGORY" AS "I_CATEGORY00", "ITEM"."I_BRAND" AS "I_BRAND00", "CALL_CENTER"."CC_NAME" AS "CC_NAME00", "DATE_DIM"."D_YEAR" AS "D_YEAR00", "DATE_DIM"."D_MOY" AS "D_MOY00", SUM("CATALOG_SALES"."CS_SALES_PRICE") AS "$f50", AVG(SUM("CATALOG_SALES"."CS_SALES_PRICE")) OVER (PARTITION BY "ITEM"."I_CATEGORY", "ITEM"."I_BRAND", "CALL_CENTER"."CC_NAME", "DATE_DIM"."D_YEAR" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f12", RANK() OVER (PARTITION BY "ITEM"."I_CATEGORY", "ITEM"."I_BRAND", "CALL_CENTER"."CC_NAME" ORDER BY "DATE_DIM"."D_YEAR", "DATE_DIM"."D_MOY") AS "$f13"
FROM "tpcds"."ITEM",
"tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM",
"tpcds"."CALL_CENTER"
WHERE "CATALOG_SALES"."CS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "CALL_CENTER"."CC_CALL_CENTER_SK" = "CATALOG_SALES"."CS_CALL_CENTER_SK" AND ("DATE_DIM"."D_YEAR" = 1999 OR "DATE_DIM"."D_YEAR" = 1999 - 1 AND "DATE_DIM"."D_MOY" = 12 OR "DATE_DIM"."D_YEAR" = 1999 + 1 AND "DATE_DIM"."D_MOY" = 1)
GROUP BY "ITEM"."I_CATEGORY", "ITEM"."I_BRAND", "CALL_CENTER"."CC_NAME", "DATE_DIM"."D_YEAR", "DATE_DIM"."D_MOY") AS "t2",
(SELECT "ITEM0"."I_CATEGORY" AS "I_CATEGORY00", "ITEM0"."I_BRAND" AS "I_BRAND00", "CALL_CENTER0"."CC_NAME" AS "CC_NAME00", "DATE_DIM0"."D_YEAR" AS "D_YEAR00", "DATE_DIM0"."D_MOY" AS "D_MOY00", SUM("CATALOG_SALES0"."CS_SALES_PRICE") AS "$f50", AVG(SUM("CATALOG_SALES0"."CS_SALES_PRICE")) OVER (PARTITION BY "ITEM0"."I_CATEGORY", "ITEM0"."I_BRAND", "CALL_CENTER0"."CC_NAME", "DATE_DIM0"."D_YEAR" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f12", RANK() OVER (PARTITION BY "ITEM0"."I_CATEGORY", "ITEM0"."I_BRAND", "CALL_CENTER0"."CC_NAME" ORDER BY "DATE_DIM0"."D_YEAR", "DATE_DIM0"."D_MOY") AS "$f13"
FROM "tpcds"."ITEM" AS "ITEM0",
"tpcds"."CATALOG_SALES" AS "CATALOG_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CALL_CENTER" AS "CALL_CENTER0"
WHERE "CATALOG_SALES0"."CS_ITEM_SK" = "ITEM0"."I_ITEM_SK" AND "CATALOG_SALES0"."CS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "CALL_CENTER0"."CC_CALL_CENTER_SK" = "CATALOG_SALES0"."CS_CALL_CENTER_SK" AND ("DATE_DIM0"."D_YEAR" = 1999 OR "DATE_DIM0"."D_YEAR" = 1999 - 1 AND "DATE_DIM0"."D_MOY" = 12 OR "DATE_DIM0"."D_YEAR" = 1999 + 1 AND "DATE_DIM0"."D_MOY" = 1)
GROUP BY "ITEM0"."I_CATEGORY", "ITEM0"."I_BRAND", "CALL_CENTER0"."CC_NAME", "DATE_DIM0"."D_YEAR", "DATE_DIM0"."D_MOY") AS "t6",
(SELECT "ITEM1"."I_CATEGORY" AS "I_CATEGORY00", "ITEM1"."I_BRAND" AS "I_BRAND00", "CALL_CENTER1"."CC_NAME" AS "CC_NAME00", "DATE_DIM1"."D_YEAR" AS "D_YEAR00", "DATE_DIM1"."D_MOY" AS "D_MOY00", SUM("CATALOG_SALES1"."CS_SALES_PRICE") AS "$f50", AVG(SUM("CATALOG_SALES1"."CS_SALES_PRICE")) OVER (PARTITION BY "ITEM1"."I_CATEGORY", "ITEM1"."I_BRAND", "CALL_CENTER1"."CC_NAME", "DATE_DIM1"."D_YEAR" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f12", RANK() OVER (PARTITION BY "ITEM1"."I_CATEGORY", "ITEM1"."I_BRAND", "CALL_CENTER1"."CC_NAME" ORDER BY "DATE_DIM1"."D_YEAR", "DATE_DIM1"."D_MOY") AS "$f13"
FROM "tpcds"."ITEM" AS "ITEM1",
"tpcds"."CATALOG_SALES" AS "CATALOG_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."CALL_CENTER" AS "CALL_CENTER1"
WHERE "CATALOG_SALES1"."CS_ITEM_SK" = "ITEM1"."I_ITEM_SK" AND "CATALOG_SALES1"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "CALL_CENTER1"."CC_CALL_CENTER_SK" = "CATALOG_SALES1"."CS_CALL_CENTER_SK" AND ("DATE_DIM1"."D_YEAR" = 1999 OR "DATE_DIM1"."D_YEAR" = 1999 - 1 AND "DATE_DIM1"."D_MOY" = 12 OR "DATE_DIM1"."D_YEAR" = 1999 + 1 AND "DATE_DIM1"."D_MOY" = 1)
GROUP BY "ITEM1"."I_CATEGORY", "ITEM1"."I_BRAND", "CALL_CENTER1"."CC_NAME", "DATE_DIM1"."D_YEAR", "DATE_DIM1"."D_MOY") AS "t10"
WHERE "t2"."I_CATEGORY00" = "t6"."I_CATEGORY00" AND "t2"."I_CATEGORY00" = "t10"."I_CATEGORY00" AND ("t2"."I_BRAND00" = "t6"."I_BRAND00" AND "t2"."I_BRAND00" = "t10"."I_BRAND00") AND ("t2"."CC_NAME00" = "t6"."CC_NAME00" AND "t2"."CC_NAME00" = "t10"."CC_NAME00" AND ("t2"."$f13" = "t6"."$f13" + 1 AND "t2"."$f13" = "t10"."$f13" - 1))) AS "t12"
WHERE "t12"."D_YEAR002" = 1999 AND CAST("t12"."$f122" AS DECIMAL(12, 2)) > 0.00 AND CASE WHEN CAST("t12"."$f122" AS DECIMAL(12, 2)) > 0.00 THEN ABS("t12"."$f502" - "t12"."$f122") / "t12"."$f122" ELSE NULL END > 0.100000
ORDER BY 8, "D_YEAR002"
FETCH NEXT 100 ROWS ONLY) AS "t15"
