SELECT "t3"."S_STORE_NAME0" AS "S_STORE_NAME1", "t3"."S_STORE_ID0" AS "S_STORE_ID1", "t3"."D_WEEK_SEQ00" AS "D_WEEK_SEQ1", "t3"."$f20" / "t8"."$f20", "t3"."$f30" / "t8"."$f30", "t3"."$f40" / "t8"."$f40", "t3"."$f50" / "t8"."$f50", "t3"."$f60" / "t8"."$f60", "t3"."$f70" / "t8"."$f70", "t3"."$f80" / "t8"."$f80"
FROM (SELECT "STORE"."S_STORE_NAME" AS "S_STORE_NAME0", "t1"."D_WEEK_SEQ0" AS "D_WEEK_SEQ00", "STORE"."S_STORE_ID" AS "S_STORE_ID0", "t1"."$f2" AS "$f20", "t1"."$f3" AS "$f30", "t1"."$f4" AS "$f40", "t1"."$f5" AS "$f50", "t1"."$f6" AS "$f60", "t1"."$f7" AS "$f70", "t1"."$f8" AS "$f80"
FROM (SELECT "DATE_DIM"."D_WEEK_SEQ" AS "D_WEEK_SEQ0", "STORE_SALES"."SS_STORE_SK" AS "SS_STORE_SK0", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Sunday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f2", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Monday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f3", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Tuesday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f4", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Wednesday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f5", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Thursday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f6", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Friday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f7", SUM(CASE WHEN "DATE_DIM"."D_DAY_NAME" = 'Saturday' THEN CAST("STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f8"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM"
WHERE "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK"
GROUP BY "DATE_DIM"."D_WEEK_SEQ", "STORE_SALES"."SS_STORE_SK") AS "t1",
"tpcds"."STORE",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "DATE_DIM0"."D_WEEK_SEQ" = "t1"."D_WEEK_SEQ0" AND "t1"."SS_STORE_SK0" = "STORE"."S_STORE_SK" AND "DATE_DIM0"."D_MONTH_SEQ" >= 1195 AND "DATE_DIM0"."D_MONTH_SEQ" <= 1195 + 11) AS "t3",
(SELECT "STORE0"."S_STORE_NAME" AS "S_STORE_NAME0", "t6"."D_WEEK_SEQ0" AS "D_WEEK_SEQ00", "STORE0"."S_STORE_ID" AS "S_STORE_ID0", "t6"."$f2" AS "$f20", "t6"."$f3" AS "$f30", "t6"."$f4" AS "$f40", "t6"."$f5" AS "$f50", "t6"."$f6" AS "$f60", "t6"."$f7" AS "$f70", "t6"."$f8" AS "$f80"
FROM (SELECT "DATE_DIM1"."D_WEEK_SEQ" AS "D_WEEK_SEQ0", "STORE_SALES0"."SS_STORE_SK" AS "SS_STORE_SK0", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Sunday' THEN CAST("STORE_SALES0"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f2", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Monday' THEN CAST("STORE_SALES0"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f3", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Tuesday' THEN CAST("STORE_SALES0"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f4", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Wednesday' THEN CAST("STORE_SALES0"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f5", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Thursday' THEN CAST("STORE_SALES0"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f6", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Friday' THEN CAST("STORE_SALES0"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f7", SUM(CASE WHEN "DATE_DIM1"."D_DAY_NAME" = 'Saturday' THEN CAST("STORE_SALES0"."SS_SALES_PRICE" AS DECIMAL(7, 2)) ELSE NULL END) AS "$f8"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "DATE_DIM1"."D_DATE_SK" = "STORE_SALES0"."SS_SOLD_DATE_SK"
GROUP BY "DATE_DIM1"."D_WEEK_SEQ", "STORE_SALES0"."SS_STORE_SK") AS "t6",
"tpcds"."STORE" AS "STORE0",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "DATE_DIM2"."D_WEEK_SEQ" = "t6"."D_WEEK_SEQ0" AND "t6"."SS_STORE_SK0" = "STORE0"."S_STORE_SK" AND "DATE_DIM2"."D_MONTH_SEQ" >= 1195 + 12 AND "DATE_DIM2"."D_MONTH_SEQ" <= 1195 + 23) AS "t8"
WHERE "t3"."S_STORE_ID0" = "t8"."S_STORE_ID0" AND "t3"."D_WEEK_SEQ00" = "t8"."D_WEEK_SEQ00" - 52
ORDER BY "t3"."S_STORE_NAME0", "t3"."S_STORE_ID0", "t3"."D_WEEK_SEQ00"
FETCH NEXT 100 ROWS ONLY
