SELECT "I_ITEM_ID0" AS "I_ITEM_ID", "$f1" AS "TOTAL_SALES"
FROM (SELECT "I_ITEM_ID0", SUM("$f1") AS "$f1"
FROM (SELECT *
FROM (SELECT "ITEM"."I_ITEM_ID" AS "I_ITEM_ID0", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f1"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."ITEM"
WHERE "ITEM"."I_ITEM_ID" IN (SELECT "I_ITEM_ID" AS "I_ITEM_ID0"
FROM "tpcds"."ITEM"
WHERE "I_CATEGORY" = 'Jewelry') AND ("STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK") AND ("DATE_DIM"."D_YEAR" = 1998 AND "DATE_DIM"."D_MOY" = 9 AND ("STORE_SALES"."SS_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND CAST("CUSTOMER_ADDRESS"."CA_GMT_OFFSET" AS DECIMAL(12, 2)) = -5.00))
GROUP BY "ITEM"."I_ITEM_ID"
UNION ALL
SELECT "ITEM1"."I_ITEM_ID" AS "I_ITEM_ID0", SUM("CATALOG_SALES"."CS_EXT_SALES_PRICE") AS "$f1"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0",
"tpcds"."ITEM" AS "ITEM1"
WHERE "ITEM1"."I_ITEM_ID" IN (SELECT "I_ITEM_ID" AS "I_ITEM_ID0"
FROM "tpcds"."ITEM"
WHERE "I_CATEGORY" = 'Jewelry') AND ("CATALOG_SALES"."CS_ITEM_SK" = "ITEM1"."I_ITEM_SK" AND "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK") AND ("DATE_DIM0"."D_YEAR" = 1998 AND "DATE_DIM0"."D_MOY" = 9 AND ("CATALOG_SALES"."CS_BILL_ADDR_SK" = "CUSTOMER_ADDRESS0"."CA_ADDRESS_SK" AND CAST("CUSTOMER_ADDRESS0"."CA_GMT_OFFSET" AS DECIMAL(12, 2)) = -5.00))
GROUP BY "ITEM1"."I_ITEM_ID")
UNION ALL
SELECT "ITEM3"."I_ITEM_ID" AS "I_ITEM_ID0", SUM("WEB_SALES"."WS_EXT_SALES_PRICE") AS "$f1"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS1",
"tpcds"."ITEM" AS "ITEM3"
WHERE "ITEM3"."I_ITEM_ID" IN (SELECT "I_ITEM_ID" AS "I_ITEM_ID0"
FROM "tpcds"."ITEM"
WHERE "I_CATEGORY" = 'Jewelry') AND ("WEB_SALES"."WS_ITEM_SK" = "ITEM3"."I_ITEM_SK" AND "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK") AND ("DATE_DIM1"."D_YEAR" = 1998 AND "DATE_DIM1"."D_MOY" = 9 AND ("WEB_SALES"."WS_BILL_ADDR_SK" = "CUSTOMER_ADDRESS1"."CA_ADDRESS_SK" AND CAST("CUSTOMER_ADDRESS1"."CA_GMT_OFFSET" AS DECIMAL(12, 2)) = -5.00))
GROUP BY "ITEM3"."I_ITEM_ID") AS "t15"
GROUP BY "I_ITEM_ID0"
ORDER BY "I_ITEM_ID0", 2
FETCH NEXT 100 ROWS ONLY) AS "t17"
