SELECT "t1"."$f0" AS "PROMOTIONS", "t4"."$f0" AS "TOTAL", CAST("t1"."$f0" AS DECIMAL(15, 4)) / CAST("t4"."$f0" AS DECIMAL(15, 4)) * 100.000000
FROM (SELECT SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f0"
FROM "tpcds"."STORE_SALES",
"tpcds"."STORE",
"tpcds"."PROMOTION",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."ITEM"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND "STORE_SALES"."SS_PROMO_SK" = "PROMOTION"."P_PROMO_SK") AND ("STORE_SALES"."SS_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND ("CUSTOMER_ADDRESS"."CA_ADDRESS_SK" = "CUSTOMER"."C_CURRENT_ADDR_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK")) AND (CAST("CUSTOMER_ADDRESS"."CA_GMT_OFFSET" AS DECIMAL(12, 2)) = -6.00 AND ("ITEM"."I_CATEGORY" = 'Jewelry' AND ("PROMOTION"."P_CHANNEL_DMAIL" = 'Y' OR "PROMOTION"."P_CHANNEL_EMAIL" = 'Y' OR "PROMOTION"."P_CHANNEL_TV" = 'Y')) AND (CAST("STORE"."S_GMT_OFFSET" AS DECIMAL(12, 2)) = -6.00 AND ("DATE_DIM"."D_YEAR" = 1998 AND "DATE_DIM"."D_MOY" = 12)))) AS "t1",
(SELECT SUM("STORE_SALES0"."SS_EXT_SALES_PRICE") AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."STORE" AS "STORE0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CUSTOMER" AS "CUSTOMER0",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0",
"tpcds"."ITEM" AS "ITEM0"
WHERE "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "STORE_SALES0"."SS_STORE_SK" = "STORE0"."S_STORE_SK" AND ("STORE_SALES0"."SS_CUSTOMER_SK" = "CUSTOMER0"."C_CUSTOMER_SK" AND ("CUSTOMER_ADDRESS0"."CA_ADDRESS_SK" = "CUSTOMER0"."C_CURRENT_ADDR_SK" AND "STORE_SALES0"."SS_ITEM_SK" = "ITEM0"."I_ITEM_SK")) AND (CAST("CUSTOMER_ADDRESS0"."CA_GMT_OFFSET" AS DECIMAL(12, 2)) = -6.00 AND "ITEM0"."I_CATEGORY" = 'Jewelry' AND (CAST("STORE0"."S_GMT_OFFSET" AS DECIMAL(12, 2)) = -6.00 AND ("DATE_DIM0"."D_YEAR" = 1998 AND "DATE_DIM0"."D_MOY" = 12)))) AS "t4"
ORDER BY "t1"."$f0", "t4"."$f0"
FETCH NEXT 100 ROWS ONLY
