SELECT "t2"."$f108", "t2"."SM_TYPE0" AS "SM_TYPE", "t2"."WEB_NAME0" AS "WEB_NAME", "t2"."$f3" AS "30 days", "t2"."$f4" AS "31-60 days", "t2"."$f5" AS "61-90 days", "t2"."$f6" AS "91-120 days", "t2"."$f7" AS ">120 days"
FROM (SELECT SUBSTRING("WAREHOUSE"."W_WAREHOUSE_NAME", 1, 20) AS "$f108", "SHIP_MODE"."SM_TYPE" AS "SM_TYPE0", "WEB_SITE"."WEB_NAME" AS "WEB_NAME0", SUM(CASE WHEN "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" <= 30 THEN 1 ELSE 0 END) AS "$f3", SUM(CASE WHEN "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" > 30 AND "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" <= 60 THEN 1 ELSE 0 END) AS "$f4", SUM(CASE WHEN "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" > 60 AND "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" <= 90 THEN 1 ELSE 0 END) AS "$f5", SUM(CASE WHEN "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" > 90 AND "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" <= 120 THEN 1 ELSE 0 END) AS "$f6", SUM(CASE WHEN "WEB_SALES"."WS_SHIP_DATE_SK" - "WEB_SALES"."WS_SOLD_DATE_SK" > 120 THEN 1 ELSE 0 END) AS "$f7"
FROM "tpcds"."WEB_SALES",
"tpcds"."WAREHOUSE",
"tpcds"."SHIP_MODE",
"tpcds"."WEB_SITE",
"tpcds"."DATE_DIM"
WHERE "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND ("DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11 AND "WEB_SALES"."WS_SHIP_DATE_SK" = "DATE_DIM"."D_DATE_SK") AND ("WEB_SALES"."WS_WAREHOUSE_SK" = "WAREHOUSE"."W_WAREHOUSE_SK" AND ("WEB_SALES"."WS_SHIP_MODE_SK" = "SHIP_MODE"."SM_SHIP_MODE_SK" AND "WEB_SALES"."WS_WEB_SITE_SK" = "WEB_SITE"."WEB_SITE_SK"))
GROUP BY SUBSTRING("WAREHOUSE"."W_WAREHOUSE_NAME", 1, 20), "SHIP_MODE"."SM_TYPE", "WEB_SITE"."WEB_NAME"
ORDER BY 1, "SHIP_MODE"."SM_TYPE", "WEB_SITE"."WEB_NAME"
FETCH NEXT 100 ROWS ONLY) AS "t2"
