SELECT "I_MANAGER_ID00" AS "I_MANAGER_ID", "$f20" AS "SUM_SALES", "$f5" AS "AVG_MONTHLY_SALES"
FROM (SELECT "ITEM"."I_MANAGER_ID" AS "I_MANAGER_ID00", SUM("STORE_SALES"."SS_SALES_PRICE") AS "$f20", AVG(SUM("STORE_SALES"."SS_SALES_PRICE")) OVER (PARTITION BY "ITEM"."I_MANAGER_ID" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f5"
FROM "tpcds"."ITEM",
"tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE"
WHERE "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND ("DATE_DIM"."D_MONTH_SEQ" = 1220 OR ("DATE_DIM"."D_MONTH_SEQ" = 1220 + 1 OR "DATE_DIM"."D_MONTH_SEQ" = 1220 + 2) OR ("DATE_DIM"."D_MONTH_SEQ" = 1220 + 3 OR ("DATE_DIM"."D_MONTH_SEQ" = 1220 + 4 OR "DATE_DIM"."D_MONTH_SEQ" = 1220 + 5)) OR ("DATE_DIM"."D_MONTH_SEQ" = 1220 + 6 OR ("DATE_DIM"."D_MONTH_SEQ" = 1220 + 7 OR "DATE_DIM"."D_MONTH_SEQ" = 1220 + 8) OR ("DATE_DIM"."D_MONTH_SEQ" = 1220 + 9 OR ("DATE_DIM"."D_MONTH_SEQ" = 1220 + 10 OR "DATE_DIM"."D_MONTH_SEQ" = 1220 + 11)))) AND (CAST("ITEM"."I_CATEGORY" AS VARCHAR(50)) IN ('Books', 'Children', 'Electronics') AND CAST("ITEM"."I_CLASS" AS VARCHAR(50)) IN ('personal', 'portable', 'refernece', 'self-help') AND CAST("ITEM"."I_BRAND" AS VARCHAR(50)) IN ('exportiunivamalg #9', 'scholaramalgamalg #14', 'scholaramalgamalg #7', 'scholaramalgamalg #9') OR CAST("ITEM"."I_CATEGORY" AS VARCHAR(50)) IN ('Men', 'Music', 'Women') AND CAST("ITEM"."I_CLASS" AS VARCHAR(50)) IN ('accessories', 'classical', 'fragrances', 'pants') AND CAST("ITEM"."I_BRAND" AS VARCHAR(50)) IN ('amalgimporto #1', 'edu packscholar #1', 'exportiimporto #1', 'importoamalg #1'))
GROUP BY "ITEM"."I_MANAGER_ID", "DATE_DIM"."D_MOY") AS "t2"
WHERE CASE WHEN CAST("t2"."$f5" AS DECIMAL(12, 2)) > 0.00 THEN ABS("t2"."$f20" - "t2"."$f5") / "t2"."$f5" ELSE NULL END > 0.100000
ORDER BY "I_MANAGER_ID00", "$f5", "$f20"
FETCH NEXT 100 ROWS ONLY
