SELECT "t5"."I_PRODUCT_NAME0" AS "PRODUCT_NAME", "t5"."S_STORE_NAME0" AS "STORE_NAME", "t5"."S_ZIP0" AS "STORE_ZIP", "t5"."CA_STREET_NUMBER1" AS "B_STREET_NUMBER", "t5"."CA_STREET_NAME1" AS "B_STREEN_NAME", "t5"."CA_CITY1" AS "B_CITY", "t5"."CA_ZIP1" AS "B_ZIP", "t5"."CA_STREET_NUMBER00" AS "C_STREET_NUMBER", "t5"."CA_STREET_NAME00" AS "C_STREET_NAME", "t5"."CA_CITY00" AS "C_CITY", "t5"."CA_ZIP00" AS "C_ZIP", "t5"."D_YEAR2" AS "SYEAR", "t5"."$f15" AS "CNT", "t5"."$f16" AS "S1", "t5"."$f17" AS "S2", "t5"."$f18" AS "S3", "t12"."$f16" AS "S116", "t12"."$f17" AS "S217", "t12"."$f18" AS "S318", "t12"."D_YEAR2" AS "SYEAR19", "t12"."$f15" AS "CNT20"
FROM (SELECT "ITEM"."I_PRODUCT_NAME" AS "I_PRODUCT_NAME0", "ITEM"."I_ITEM_SK" AS "I_ITEM_SK0", "STORE"."S_STORE_NAME" AS "S_STORE_NAME0", "STORE"."S_ZIP" AS "S_ZIP0", "CUSTOMER_ADDRESS"."CA_STREET_NUMBER" AS "CA_STREET_NUMBER1", "CUSTOMER_ADDRESS"."CA_STREET_NAME" AS "CA_STREET_NAME1", "CUSTOMER_ADDRESS"."CA_CITY" AS "CA_CITY1", "CUSTOMER_ADDRESS"."CA_ZIP" AS "CA_ZIP1", "CUSTOMER_ADDRESS0"."CA_STREET_NUMBER" AS "CA_STREET_NUMBER00", "CUSTOMER_ADDRESS0"."CA_STREET_NAME" AS "CA_STREET_NAME00", "CUSTOMER_ADDRESS0"."CA_CITY" AS "CA_CITY00", "CUSTOMER_ADDRESS0"."CA_ZIP" AS "CA_ZIP00", "DATE_DIM"."D_YEAR" AS "D_YEAR2", "DATE_DIM0"."D_YEAR" AS "D_YEAR00", "DATE_DIM1"."D_YEAR" AS "D_YEAR10", COUNT(*) AS "$f15", SUM("STORE_SALES"."SS_WHOLESALE_COST") AS "$f16", SUM("STORE_SALES"."SS_LIST_PRICE") AS "$f17", SUM("STORE_SALES"."SS_COUPON_AMT") AS "$f18"
FROM "tpcds"."STORE_SALES",
"tpcds"."STORE_RETURNS",
(SELECT "CATALOG_SALES"."CS_ITEM_SK" AS "CS_ITEM_SK0", SUM("CATALOG_SALES"."CS_EXT_LIST_PRICE") AS "$f1", SUM("CATALOG_RETURNS"."CR_REFUNDED_CASH" + "CATALOG_RETURNS"."CR_REVERSED_CHARGE" + "CATALOG_RETURNS"."CR_STORE_CREDIT") AS "$f2"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."CATALOG_RETURNS"
WHERE "CATALOG_SALES"."CS_ITEM_SK" = "CATALOG_RETURNS"."CR_ITEM_SK" AND "CATALOG_SALES"."CS_ORDER_NUMBER" = "CATALOG_RETURNS"."CR_ORDER_NUMBER"
GROUP BY "CATALOG_SALES"."CS_ITEM_SK"
HAVING CAST(SUM("CATALOG_SALES"."CS_EXT_LIST_PRICE") AS DECIMAL(19, 2)) > 2.00 * SUM("CATALOG_RETURNS"."CR_REFUNDED_CASH" + "CATALOG_RETURNS"."CR_REVERSED_CHARGE" + "CATALOG_RETURNS"."CR_STORE_CREDIT")) AS "t2",
"tpcds"."DATE_DIM",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."STORE",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_DEMOGRAPHICS",
"tpcds"."CUSTOMER_DEMOGRAPHICS" AS "CUSTOMER_DEMOGRAPHICS0",
"tpcds"."PROMOTION",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS0",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0",
"tpcds"."INCOME_BAND",
"tpcds"."INCOME_BAND" AS "INCOME_BAND0",
"tpcds"."ITEM"
WHERE "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND ("STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK") AND ("STORE_SALES"."SS_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" AND ("STORE_SALES"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" AND "STORE_SALES"."SS_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK")) AND ("STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND ("STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK" AND "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER") AND ("STORE_SALES"."SS_ITEM_SK" = "t2"."CS_ITEM_SK0" AND ("CUSTOMER"."C_CURRENT_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS0"."CD_DEMO_SK" AND "CUSTOMER"."C_CURRENT_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS0"."HD_DEMO_SK"))) AND ("CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS0"."CA_ADDRESS_SK" AND ("CUSTOMER"."C_FIRST_SALES_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "CUSTOMER"."C_FIRST_SHIPTO_DATE_SK" = "DATE_DIM1"."D_DATE_SK") AND ("STORE_SALES"."SS_PROMO_SK" = "PROMOTION"."P_PROMO_SK" AND ("HOUSEHOLD_DEMOGRAPHICS"."HD_INCOME_BAND_SK" = "INCOME_BAND"."IB_INCOME_BAND_SK" AND "HOUSEHOLD_DEMOGRAPHICS0"."HD_INCOME_BAND_SK" = "INCOME_BAND0"."IB_INCOME_BAND_SK")) AND ("CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS" <> "CUSTOMER_DEMOGRAPHICS0"."CD_MARITAL_STATUS" AND (CAST("ITEM"."I_COLOR" AS VARCHAR(20)) IN ('[COLOR.1]', '[COLOR.2]', '[COLOR.3]', '[COLOR.4]', '[COLOR.5]', '[COLOR.6]') AND CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) >= 44.00) AND (CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) <= CAST(44 + 10 AS DECIMAL(12, 2)) AND (CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) >= CAST(44 + 1 AS DECIMAL(12, 2)) AND CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) <= CAST(44 + 15 AS DECIMAL(12, 2))))))
GROUP BY "ITEM"."I_PRODUCT_NAME", "ITEM"."I_ITEM_SK", "STORE"."S_STORE_NAME", "STORE"."S_ZIP", "CUSTOMER_ADDRESS"."CA_STREET_NUMBER", "CUSTOMER_ADDRESS"."CA_STREET_NAME", "CUSTOMER_ADDRESS"."CA_CITY", "CUSTOMER_ADDRESS"."CA_ZIP", "CUSTOMER_ADDRESS0"."CA_STREET_NUMBER", "CUSTOMER_ADDRESS0"."CA_STREET_NAME", "CUSTOMER_ADDRESS0"."CA_CITY", "CUSTOMER_ADDRESS0"."CA_ZIP", "DATE_DIM"."D_YEAR", "DATE_DIM0"."D_YEAR", "DATE_DIM1"."D_YEAR") AS "t5",
(SELECT "ITEM0"."I_PRODUCT_NAME" AS "I_PRODUCT_NAME0", "ITEM0"."I_ITEM_SK" AS "I_ITEM_SK0", "STORE0"."S_STORE_NAME" AS "S_STORE_NAME0", "STORE0"."S_ZIP" AS "S_ZIP0", "CUSTOMER_ADDRESS1"."CA_STREET_NUMBER" AS "CA_STREET_NUMBER1", "CUSTOMER_ADDRESS1"."CA_STREET_NAME" AS "CA_STREET_NAME1", "CUSTOMER_ADDRESS1"."CA_CITY" AS "CA_CITY1", "CUSTOMER_ADDRESS1"."CA_ZIP" AS "CA_ZIP1", "CUSTOMER_ADDRESS2"."CA_STREET_NUMBER" AS "CA_STREET_NUMBER00", "CUSTOMER_ADDRESS2"."CA_STREET_NAME" AS "CA_STREET_NAME00", "CUSTOMER_ADDRESS2"."CA_CITY" AS "CA_CITY00", "CUSTOMER_ADDRESS2"."CA_ZIP" AS "CA_ZIP00", "DATE_DIM2"."D_YEAR" AS "D_YEAR2", "DATE_DIM3"."D_YEAR" AS "D_YEAR00", "DATE_DIM4"."D_YEAR" AS "D_YEAR10", COUNT(*) AS "$f15", SUM("STORE_SALES0"."SS_WHOLESALE_COST") AS "$f16", SUM("STORE_SALES0"."SS_LIST_PRICE") AS "$f17", SUM("STORE_SALES0"."SS_COUPON_AMT") AS "$f18"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."STORE_RETURNS" AS "STORE_RETURNS0",
(SELECT "CATALOG_SALES0"."CS_ITEM_SK" AS "CS_ITEM_SK0", SUM("CATALOG_SALES0"."CS_EXT_LIST_PRICE") AS "$f1", SUM("CATALOG_RETURNS0"."CR_REFUNDED_CASH" + "CATALOG_RETURNS0"."CR_REVERSED_CHARGE" + "CATALOG_RETURNS0"."CR_STORE_CREDIT") AS "$f2"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES0",
"tpcds"."CATALOG_RETURNS" AS "CATALOG_RETURNS0"
WHERE "CATALOG_SALES0"."CS_ITEM_SK" = "CATALOG_RETURNS0"."CR_ITEM_SK" AND "CATALOG_SALES0"."CS_ORDER_NUMBER" = "CATALOG_RETURNS0"."CR_ORDER_NUMBER"
GROUP BY "CATALOG_SALES0"."CS_ITEM_SK"
HAVING CAST(SUM("CATALOG_SALES0"."CS_EXT_LIST_PRICE") AS DECIMAL(19, 2)) > 2.00 * SUM("CATALOG_RETURNS0"."CR_REFUNDED_CASH" + "CATALOG_RETURNS0"."CR_REVERSED_CHARGE" + "CATALOG_RETURNS0"."CR_STORE_CREDIT")) AS "t9",
"tpcds"."DATE_DIM" AS "DATE_DIM2",
"tpcds"."DATE_DIM" AS "DATE_DIM3",
"tpcds"."DATE_DIM" AS "DATE_DIM4",
"tpcds"."STORE" AS "STORE0",
"tpcds"."CUSTOMER" AS "CUSTOMER0",
"tpcds"."CUSTOMER_DEMOGRAPHICS" AS "CUSTOMER_DEMOGRAPHICS1",
"tpcds"."CUSTOMER_DEMOGRAPHICS" AS "CUSTOMER_DEMOGRAPHICS2",
"tpcds"."PROMOTION" AS "PROMOTION0",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS1",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS2",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS1",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS2",
"tpcds"."INCOME_BAND" AS "INCOME_BAND1",
"tpcds"."INCOME_BAND" AS "INCOME_BAND2",
"tpcds"."ITEM" AS "ITEM0"
WHERE "STORE_SALES0"."SS_STORE_SK" = "STORE0"."S_STORE_SK" AND ("STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM2"."D_DATE_SK" AND "STORE_SALES0"."SS_CUSTOMER_SK" = "CUSTOMER0"."C_CUSTOMER_SK") AND ("STORE_SALES0"."SS_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS1"."CD_DEMO_SK" AND ("STORE_SALES0"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS1"."HD_DEMO_SK" AND "STORE_SALES0"."SS_ADDR_SK" = "CUSTOMER_ADDRESS1"."CA_ADDRESS_SK")) AND ("STORE_SALES0"."SS_ITEM_SK" = "ITEM0"."I_ITEM_SK" AND ("STORE_SALES0"."SS_ITEM_SK" = "STORE_RETURNS0"."SR_ITEM_SK" AND "STORE_SALES0"."SS_TICKET_NUMBER" = "STORE_RETURNS0"."SR_TICKET_NUMBER") AND ("STORE_SALES0"."SS_ITEM_SK" = "t9"."CS_ITEM_SK0" AND ("CUSTOMER0"."C_CURRENT_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS2"."CD_DEMO_SK" AND "CUSTOMER0"."C_CURRENT_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS2"."HD_DEMO_SK"))) AND ("CUSTOMER0"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS2"."CA_ADDRESS_SK" AND ("CUSTOMER0"."C_FIRST_SALES_DATE_SK" = "DATE_DIM3"."D_DATE_SK" AND "CUSTOMER0"."C_FIRST_SHIPTO_DATE_SK" = "DATE_DIM4"."D_DATE_SK") AND ("STORE_SALES0"."SS_PROMO_SK" = "PROMOTION0"."P_PROMO_SK" AND ("HOUSEHOLD_DEMOGRAPHICS1"."HD_INCOME_BAND_SK" = "INCOME_BAND1"."IB_INCOME_BAND_SK" AND "HOUSEHOLD_DEMOGRAPHICS2"."HD_INCOME_BAND_SK" = "INCOME_BAND2"."IB_INCOME_BAND_SK")) AND ("CUSTOMER_DEMOGRAPHICS1"."CD_MARITAL_STATUS" <> "CUSTOMER_DEMOGRAPHICS2"."CD_MARITAL_STATUS" AND (CAST("ITEM0"."I_COLOR" AS VARCHAR(20)) IN ('[COLOR.1]', '[COLOR.2]', '[COLOR.3]', '[COLOR.4]', '[COLOR.5]', '[COLOR.6]') AND CAST("ITEM0"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) >= 44.00) AND (CAST("ITEM0"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) <= CAST(44 + 10 AS DECIMAL(12, 2)) AND (CAST("ITEM0"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) >= CAST(44 + 1 AS DECIMAL(12, 2)) AND CAST("ITEM0"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) <= CAST(44 + 15 AS DECIMAL(12, 2))))))
GROUP BY "ITEM0"."I_PRODUCT_NAME", "ITEM0"."I_ITEM_SK", "STORE0"."S_STORE_NAME", "STORE0"."S_ZIP", "CUSTOMER_ADDRESS1"."CA_STREET_NUMBER", "CUSTOMER_ADDRESS1"."CA_STREET_NAME", "CUSTOMER_ADDRESS1"."CA_CITY", "CUSTOMER_ADDRESS1"."CA_ZIP", "CUSTOMER_ADDRESS2"."CA_STREET_NUMBER", "CUSTOMER_ADDRESS2"."CA_STREET_NAME", "CUSTOMER_ADDRESS2"."CA_CITY", "CUSTOMER_ADDRESS2"."CA_ZIP", "DATE_DIM2"."D_YEAR", "DATE_DIM3"."D_YEAR", "DATE_DIM4"."D_YEAR") AS "t12"
WHERE "t5"."I_ITEM_SK0" = "t12"."I_ITEM_SK0" AND ("t5"."D_YEAR2" = 2000 AND "t12"."D_YEAR2" = 2000 + 1) AND ("t12"."$f15" <= "t5"."$f15" AND ("t5"."S_STORE_NAME0" = "t12"."S_STORE_NAME0" AND "t5"."S_ZIP0" = "t12"."S_ZIP0"))
ORDER BY "t5"."I_PRODUCT_NAME0", "t5"."S_STORE_NAME0", "t12"."$f15"
