SELECT "STORE"."S_STORE_NAME", "ITEM"."I_ITEM_DESC", "t6"."$f2" AS "REVENUE", "ITEM"."I_CURRENT_PRICE", "ITEM"."I_WHOLESALE_COST", "ITEM"."I_BRAND"
FROM "tpcds"."STORE",
"tpcds"."ITEM",
(SELECT "t2"."SS_STORE_SK00", AVG("t2"."$f20") AS "$f1"
FROM (SELECT "STORE_SALES"."SS_STORE_SK" AS "SS_STORE_SK00", SUM("STORE_SALES"."SS_SALES_PRICE") AS "$f20"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "STORE_SALES"."SS_STORE_SK", "STORE_SALES"."SS_ITEM_SK") AS "t2"
GROUP BY "t2"."SS_STORE_SK00") AS "t3",
(SELECT "STORE_SALES0"."SS_STORE_SK" AS "SS_STORE_SK0", "STORE_SALES0"."SS_ITEM_SK" AS "SS_ITEM_SK0", SUM("STORE_SALES0"."SS_SALES_PRICE") AS "$f2"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM0"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "STORE_SALES0"."SS_STORE_SK", "STORE_SALES0"."SS_ITEM_SK") AS "t6"
WHERE "t3"."SS_STORE_SK00" = "t6"."SS_STORE_SK0" AND CAST("t6"."$f2" AS DECIMAL(9, 3)) <= 0.1 * "t3"."$f1" AND "STORE"."S_STORE_SK" = "t6"."SS_STORE_SK0" AND "ITEM"."I_ITEM_SK" = "t6"."SS_ITEM_SK0"
ORDER BY "STORE"."S_STORE_NAME", "ITEM"."I_ITEM_DESC"
FETCH NEXT 100 ROWS ONLY
