SELECT "I_CATEGORY00" AS "I_CATEGORY", "I_CLASS00" AS "I_CLASS", "I_BRAND00" AS "I_BRAND", "I_PRODUCT_NAME00" AS "I_PRODUCT_NAME", "D_YEAR00" AS "D_YEAR", "D_QOY00" AS "D_QOY", "D_MOY00" AS "D_MOY", "S_STORE_ID00" AS "S_STORE_ID", "$f80" AS "SUMSALES", "$f18" AS "RK"
FROM (SELECT "ITEM"."I_CATEGORY" AS "I_CATEGORY00", "ITEM"."I_CLASS" AS "I_CLASS00", "ITEM"."I_BRAND" AS "I_BRAND00", "ITEM"."I_PRODUCT_NAME" AS "I_PRODUCT_NAME00", "DATE_DIM"."D_YEAR" AS "D_YEAR00", "DATE_DIM"."D_QOY" AS "D_QOY00", "DATE_DIM"."D_MOY" AS "D_MOY00", "STORE"."S_STORE_ID" AS "S_STORE_ID00", SUM(CAST("STORE_SALES"."SS_SALES_PRICE" * CAST("STORE_SALES"."SS_QUANTITY" AS DECIMAL(12, 2)) AS DECIMAL(17, 2))) AS "$f80", RANK() OVER (PARTITION BY "ITEM"."I_CATEGORY" ORDER BY SUM(CAST("STORE_SALES"."SS_SALES_PRICE" * CAST("STORE_SALES"."SS_QUANTITY" AS DECIMAL(12, 2)) AS DECIMAL(17, 2))) DESC) AS "$f18"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE",
"tpcds"."ITEM"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY ROLLUP("ITEM"."I_CATEGORY", "ITEM"."I_CLASS", "ITEM"."I_BRAND", "ITEM"."I_PRODUCT_NAME", "DATE_DIM"."D_YEAR", "DATE_DIM"."D_QOY", "DATE_DIM"."D_MOY", "STORE"."S_STORE_ID")) AS "t2"
WHERE "t2"."$f18" <= 100
ORDER BY "I_CATEGORY00", "I_CLASS00", "I_BRAND00", "I_PRODUCT_NAME00", "D_YEAR00", "D_QOY00", "D_MOY00", "S_STORE_ID00", "$f80", "$f18"
FETCH NEXT 100 ROWS ONLY
