SELECT "$f200" AS "TOTAL_SUM", "S_STATE000" AS "S_STATE", "S_COUNTY000" AS "S_COUNTY", "$f80" AS "LOCHIERARCHY", "$f10" AS "RANK_WITHIN_PARENT"
FROM (SELECT "$f20" AS "$f200", "S_STATE00" AS "S_STATE000", "S_COUNTY00" AS "S_COUNTY000", "$f8" AS "$f80", RANK() OVER (PARTITION BY "$f8", CASE WHEN "$f7" = 0 THEN "S_STATE00" ELSE NULL END ORDER BY "$f20" DESC) AS "$f10", CASE WHEN "$f8" = 0 THEN "S_STATE00" ELSE NULL END AS "$f11"
FROM (SELECT *
FROM (SELECT SUM("STORE_SALES"."SS_NET_PROFIT") AS "$f20", "STORE"."S_STATE" AS "S_STATE00", "STORE"."S_COUNTY" AS "S_COUNTY00", 0 AS "$f6", 0 AS "$f7", 0 AS "$f8"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE"
WHERE "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "STORE"."S_STORE_SK" = "STORE_SALES"."SS_STORE_SK" AND "STORE"."S_STATE" IN (SELECT "S_STATE00" AS "S_STATE000"
FROM (SELECT "STORE0"."S_STATE" AS "S_STATE00", RANK() OVER (PARTITION BY "STORE0"."S_STATE" ORDER BY SUM("STORE_SALES0"."SS_NET_PROFIT") DESC) AS "$f3"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."STORE" AS "STORE0",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "DATE_DIM0"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM0"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM0"."D_DATE_SK" = "STORE_SALES0"."SS_SOLD_DATE_SK" AND "STORE0"."S_STORE_SK" = "STORE_SALES0"."SS_STORE_SK"
GROUP BY "STORE0"."S_STATE") AS "t2"
WHERE "t2"."$f3" <= 5)
GROUP BY "STORE"."S_STATE", "STORE"."S_COUNTY"
UNION
SELECT SUM("t18"."$f20") AS "$f10", "t18"."S_STATE00" AS "S_STATE000", CAST(NULL AS VARCHAR(30)) AS "$f4", 0 AS "$f5", 1 AS "$f6", 1 AS "$f7"
FROM (SELECT "STORE1"."S_STATE" AS "S_STATE00", SUM("STORE_SALES1"."SS_NET_PROFIT") AS "$f20"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."STORE" AS "STORE1"
WHERE "DATE_DIM1"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM1"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM1"."D_DATE_SK" = "STORE_SALES1"."SS_SOLD_DATE_SK" AND "STORE1"."S_STORE_SK" = "STORE_SALES1"."SS_STORE_SK" AND "STORE1"."S_STATE" IN (SELECT "S_STATE00" AS "S_STATE000"
FROM (SELECT "STORE2"."S_STATE" AS "S_STATE00", RANK() OVER (PARTITION BY "STORE2"."S_STATE" ORDER BY SUM("STORE_SALES2"."SS_NET_PROFIT") DESC) AS "$f3"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES2",
"tpcds"."STORE" AS "STORE2",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "DATE_DIM2"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM2"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM2"."D_DATE_SK" = "STORE_SALES2"."SS_SOLD_DATE_SK" AND "STORE2"."S_STORE_SK" = "STORE_SALES2"."SS_STORE_SK"
GROUP BY "STORE2"."S_STATE") AS "t12"
WHERE "t12"."$f3" <= 5)
GROUP BY "STORE1"."S_STATE", "STORE1"."S_COUNTY") AS "t18"
GROUP BY "t18"."S_STATE00")
UNION
SELECT SUM(SUM("STORE_SALES3"."SS_NET_PROFIT")) AS "$f00", CAST(NULL AS CHAR(2)) AS "$f2", CAST(NULL AS VARCHAR(30)) AS "$f3", 1 AS "$f4", 1 AS "$f5", 2 AS "$f6"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES3",
"tpcds"."DATE_DIM" AS "DATE_DIM3",
"tpcds"."STORE" AS "STORE3"
WHERE "DATE_DIM3"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM3"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM3"."D_DATE_SK" = "STORE_SALES3"."SS_SOLD_DATE_SK" AND "STORE3"."S_STORE_SK" = "STORE_SALES3"."SS_STORE_SK" AND "STORE3"."S_STATE" IN (SELECT "S_STATE00" AS "S_STATE000"
FROM (SELECT "STORE4"."S_STATE" AS "S_STATE00", RANK() OVER (PARTITION BY "STORE4"."S_STATE" ORDER BY SUM("STORE_SALES4"."SS_NET_PROFIT") DESC) AS "$f3"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES4",
"tpcds"."STORE" AS "STORE4",
"tpcds"."DATE_DIM" AS "DATE_DIM4"
WHERE "DATE_DIM4"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM4"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM4"."D_DATE_SK" = "STORE_SALES4"."SS_SOLD_DATE_SK" AND "STORE4"."S_STORE_SK" = "STORE_SALES4"."SS_STORE_SK"
GROUP BY "STORE4"."S_STATE") AS "t25"
WHERE "t25"."$f3" <= 5)
GROUP BY "STORE3"."S_STATE", "STORE3"."S_COUNTY") AS "t34"
ORDER BY "$f8" DESC, 6, 5
FETCH NEXT 100 ROWS ONLY) AS "t36"
