SELECT "t11"."I_BRAND_ID00" AS "BRAND_ID", "t11"."I_BRAND00" AS "BRAND", "t11"."T_HOUR00" AS "T_HOUR", "t11"."T_MINUTE00" AS "T_MINUTE", "t11"."$f40" AS "EXT_PRICE"
FROM (SELECT "ITEM"."I_BRAND_ID" AS "I_BRAND_ID00", "ITEM"."I_BRAND" AS "I_BRAND00", "TIME_DIM"."T_HOUR" AS "T_HOUR00", "TIME_DIM"."T_MINUTE" AS "T_MINUTE00", SUM("t6"."WS_EXT_SALES_PRICE0") AS "$f40"
FROM "tpcds"."ITEM",
(SELECT *
FROM (SELECT "WEB_SALES"."WS_EXT_SALES_PRICE" AS "WS_EXT_SALES_PRICE0", "WEB_SALES"."WS_SOLD_DATE_SK" AS "WS_SOLD_DATE_SK0", "WEB_SALES"."WS_ITEM_SK" AS "WS_ITEM_SK0", "WEB_SALES"."WS_SOLD_TIME_SK" AS "WS_SOLD_TIME_SK0"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM"
WHERE "DATE_DIM"."D_DATE_SK" = "WEB_SALES"."WS_SOLD_DATE_SK" AND "DATE_DIM"."D_MOY" = 12 AND "DATE_DIM"."D_YEAR" = 1998
UNION ALL
SELECT "CATALOG_SALES"."CS_EXT_SALES_PRICE" AS "CS_EXT_SALES_PRICE0", "CATALOG_SALES"."CS_SOLD_DATE_SK" AS "CS_SOLD_DATE_SK0", "CATALOG_SALES"."CS_ITEM_SK" AS "CS_ITEM_SK0", "CATALOG_SALES"."CS_SOLD_TIME_SK" AS "CS_SOLD_TIME_SK0"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "DATE_DIM0"."D_DATE_SK" = "CATALOG_SALES"."CS_SOLD_DATE_SK" AND "DATE_DIM0"."D_MOY" = 12 AND "DATE_DIM0"."D_YEAR" = 1998)
UNION ALL
SELECT "STORE_SALES"."SS_EXT_SALES_PRICE" AS "SS_EXT_SALES_PRICE0", "STORE_SALES"."SS_SOLD_DATE_SK" AS "SS_SOLD_DATE_SK0", "STORE_SALES"."SS_ITEM_SK" AS "SS_ITEM_SK0", "STORE_SALES"."SS_SOLD_TIME_SK" AS "SS_SOLD_TIME_SK0"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "DATE_DIM1"."D_DATE_SK" = "STORE_SALES"."SS_SOLD_DATE_SK" AND "DATE_DIM1"."D_MOY" = 12 AND "DATE_DIM1"."D_YEAR" = 1998) AS "t6",
"tpcds"."TIME_DIM"
WHERE "t6"."WS_ITEM_SK0" = "ITEM"."I_ITEM_SK" AND "ITEM"."I_MANAGER_ID" = 1 AND "t6"."WS_SOLD_TIME_SK0" = "TIME_DIM"."T_TIME_SK" AND CAST("TIME_DIM"."T_MEAL_TIME" AS VARCHAR(20)) IN ('breakfast', 'dinner')
GROUP BY "ITEM"."I_BRAND", "ITEM"."I_BRAND_ID", "TIME_DIM"."T_HOUR", "TIME_DIM"."T_MINUTE"
ORDER BY 5 DESC, "ITEM"."I_BRAND_ID") AS "t11"
