SELECT "t19"."D_YEAR000" AS "PREV_YEAR", "t19"."D_YEAR01" AS "YEAR_VAL", "t19"."I_BRAND_ID01" AS "I_BRAND_ID", "t19"."I_CLASS_ID01" AS "I_CLASS_ID", "t19"."I_CATEGORY_ID01" AS "I_CATEGORY_ID", "t19"."I_MANUFACT_ID01" AS "I_MANUFACT_ID", "t19"."$f500" AS "PREV_YR_CNT", "t19"."$f51" AS "CURR_YR_CNT", "t19"."$f22" AS "SALES_CNT_DIFF", "t19"."$f23" AS "SALES_AMT_DIFF"
FROM (SELECT "t16"."D_YEAR0" AS "D_YEAR000", "t7"."D_YEAR0" AS "D_YEAR01", "t7"."I_BRAND_ID0" AS "I_BRAND_ID01", "t7"."I_CLASS_ID0" AS "I_CLASS_ID01", "t7"."I_CATEGORY_ID0" AS "I_CATEGORY_ID01", "t7"."I_MANUFACT_ID0" AS "I_MANUFACT_ID01", "t16"."$f5" AS "$f500", "t7"."$f5" AS "$f51", "t7"."$f5" - "t16"."$f5" AS "$f22", "t7"."$f6" - "t16"."$f6" AS "$f23"
FROM (SELECT "D_YEAR0", "I_BRAND_ID0", "I_CLASS_ID0", "I_CATEGORY_ID0", "I_MANUFACT_ID0", SUM("$f116") AS "$f5", SUM("$f117") AS "$f6"
FROM (SELECT *
FROM (SELECT "DATE_DIM"."D_YEAR" AS "D_YEAR0", "ITEM"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM"."I_CATEGORY_ID" AS "I_CATEGORY_ID0", "ITEM"."I_MANUFACT_ID" AS "I_MANUFACT_ID0", "CATALOG_SALES"."CS_QUANTITY" - CASE WHEN "CATALOG_RETURNS"."CR_RETURN_QUANTITY" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END AS "$f116", "CATALOG_SALES"."CS_EXT_SALES_PRICE" - CASE WHEN "CATALOG_RETURNS"."CR_RETURN_AMOUNT" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_RETURN_AMOUNT" AS DECIMAL(7, 2)) ELSE 0.00 END AS "$f117"
FROM "tpcds"."CATALOG_SALES"
INNER JOIN "tpcds"."ITEM" ON "CATALOG_SALES"."CS_ITEM_SK" = "ITEM"."I_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" ON "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK"
LEFT JOIN "tpcds"."CATALOG_RETURNS" ON "CATALOG_SALES"."CS_ORDER_NUMBER" = "CATALOG_RETURNS"."CR_ORDER_NUMBER" AND "CATALOG_SALES"."CS_ITEM_SK" = "CATALOG_RETURNS"."CR_ITEM_SK"
WHERE "ITEM"."I_CATEGORY" = 'distmember(categories,61,1)'
UNION
SELECT "DATE_DIM0"."D_YEAR" AS "D_YEAR0", "ITEM0"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM0"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM0"."I_CATEGORY_ID" AS "I_CATEGORY_ID0", "ITEM0"."I_MANUFACT_ID" AS "I_MANUFACT_ID0", "STORE_SALES"."SS_QUANTITY" - CASE WHEN "STORE_RETURNS"."SR_RETURN_QUANTITY" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END AS "$f98", "STORE_SALES"."SS_EXT_SALES_PRICE" - CASE WHEN "STORE_RETURNS"."SR_RETURN_AMT" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_RETURN_AMT" AS DECIMAL(7, 2)) ELSE 0.00 END AS "$f99"
FROM "tpcds"."STORE_SALES"
INNER JOIN "tpcds"."ITEM" AS "ITEM0" ON "STORE_SALES"."SS_ITEM_SK" = "ITEM0"."I_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" AS "DATE_DIM0" ON "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK"
LEFT JOIN "tpcds"."STORE_RETURNS" ON "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER" AND "STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK"
WHERE "ITEM0"."I_CATEGORY" = 'distmember(categories,61,1)')
UNION
SELECT "DATE_DIM1"."D_YEAR" AS "D_YEAR0", "ITEM1"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM1"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM1"."I_CATEGORY_ID" AS "I_CATEGORY_ID0", "ITEM1"."I_MANUFACT_ID" AS "I_MANUFACT_ID0", "WEB_SALES"."WS_QUANTITY" - CASE WHEN "WEB_RETURNS"."WR_RETURN_QUANTITY" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END AS "$f113", "WEB_SALES"."WS_EXT_SALES_PRICE" - CASE WHEN "WEB_RETURNS"."WR_RETURN_AMT" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_RETURN_AMT" AS DECIMAL(7, 2)) ELSE 0.00 END AS "$f114"
FROM "tpcds"."WEB_SALES"
INNER JOIN "tpcds"."ITEM" AS "ITEM1" ON "WEB_SALES"."WS_ITEM_SK" = "ITEM1"."I_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" AS "DATE_DIM1" ON "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK"
LEFT JOIN "tpcds"."WEB_RETURNS" ON "WEB_SALES"."WS_ORDER_NUMBER" = "WEB_RETURNS"."WR_ORDER_NUMBER" AND "WEB_SALES"."WS_ITEM_SK" = "WEB_RETURNS"."WR_ITEM_SK"
WHERE "ITEM1"."I_CATEGORY" = 'distmember(categories,61,1)') AS "t6"
GROUP BY "D_YEAR0", "I_BRAND_ID0", "I_CLASS_ID0", "I_CATEGORY_ID0", "I_MANUFACT_ID0") AS "t7",
(SELECT "D_YEAR0", "I_BRAND_ID0", "I_CLASS_ID0", "I_CATEGORY_ID0", "I_MANUFACT_ID0", SUM("$f116") AS "$f5", SUM("$f117") AS "$f6"
FROM (SELECT *
FROM (SELECT "DATE_DIM2"."D_YEAR" AS "D_YEAR0", "ITEM2"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM2"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM2"."I_CATEGORY_ID" AS "I_CATEGORY_ID0", "ITEM2"."I_MANUFACT_ID" AS "I_MANUFACT_ID0", "CATALOG_SALES0"."CS_QUANTITY" - CASE WHEN "CATALOG_RETURNS0"."CR_RETURN_QUANTITY" IS NOT NULL THEN CAST("CATALOG_RETURNS0"."CR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END AS "$f116", "CATALOG_SALES0"."CS_EXT_SALES_PRICE" - CASE WHEN "CATALOG_RETURNS0"."CR_RETURN_AMOUNT" IS NOT NULL THEN CAST("CATALOG_RETURNS0"."CR_RETURN_AMOUNT" AS DECIMAL(7, 2)) ELSE 0.00 END AS "$f117"
FROM "tpcds"."CATALOG_SALES" AS "CATALOG_SALES0"
INNER JOIN "tpcds"."ITEM" AS "ITEM2" ON "CATALOG_SALES0"."CS_ITEM_SK" = "ITEM2"."I_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" AS "DATE_DIM2" ON "CATALOG_SALES0"."CS_SOLD_DATE_SK" = "DATE_DIM2"."D_DATE_SK"
LEFT JOIN "tpcds"."CATALOG_RETURNS" AS "CATALOG_RETURNS0" ON "CATALOG_SALES0"."CS_ORDER_NUMBER" = "CATALOG_RETURNS0"."CR_ORDER_NUMBER" AND "CATALOG_SALES0"."CS_ITEM_SK" = "CATALOG_RETURNS0"."CR_ITEM_SK"
WHERE "ITEM2"."I_CATEGORY" = 'distmember(categories,61,1)'
UNION
SELECT "DATE_DIM3"."D_YEAR" AS "D_YEAR0", "ITEM3"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM3"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM3"."I_CATEGORY_ID" AS "I_CATEGORY_ID0", "ITEM3"."I_MANUFACT_ID" AS "I_MANUFACT_ID0", "STORE_SALES0"."SS_QUANTITY" - CASE WHEN "STORE_RETURNS0"."SR_RETURN_QUANTITY" IS NOT NULL THEN CAST("STORE_RETURNS0"."SR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END AS "$f98", "STORE_SALES0"."SS_EXT_SALES_PRICE" - CASE WHEN "STORE_RETURNS0"."SR_RETURN_AMT" IS NOT NULL THEN CAST("STORE_RETURNS0"."SR_RETURN_AMT" AS DECIMAL(7, 2)) ELSE 0.00 END AS "$f99"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0"
INNER JOIN "tpcds"."ITEM" AS "ITEM3" ON "STORE_SALES0"."SS_ITEM_SK" = "ITEM3"."I_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" AS "DATE_DIM3" ON "STORE_SALES0"."SS_SOLD_DATE_SK" = "DATE_DIM3"."D_DATE_SK"
LEFT JOIN "tpcds"."STORE_RETURNS" AS "STORE_RETURNS0" ON "STORE_SALES0"."SS_TICKET_NUMBER" = "STORE_RETURNS0"."SR_TICKET_NUMBER" AND "STORE_SALES0"."SS_ITEM_SK" = "STORE_RETURNS0"."SR_ITEM_SK"
WHERE "ITEM3"."I_CATEGORY" = 'distmember(categories,61,1)')
UNION
SELECT "DATE_DIM4"."D_YEAR" AS "D_YEAR0", "ITEM4"."I_BRAND_ID" AS "I_BRAND_ID0", "ITEM4"."I_CLASS_ID" AS "I_CLASS_ID0", "ITEM4"."I_CATEGORY_ID" AS "I_CATEGORY_ID0", "ITEM4"."I_MANUFACT_ID" AS "I_MANUFACT_ID0", "WEB_SALES0"."WS_QUANTITY" - CASE WHEN "WEB_RETURNS0"."WR_RETURN_QUANTITY" IS NOT NULL THEN CAST("WEB_RETURNS0"."WR_RETURN_QUANTITY" AS INTEGER) ELSE 0 END AS "$f113", "WEB_SALES0"."WS_EXT_SALES_PRICE" - CASE WHEN "WEB_RETURNS0"."WR_RETURN_AMT" IS NOT NULL THEN CAST("WEB_RETURNS0"."WR_RETURN_AMT" AS DECIMAL(7, 2)) ELSE 0.00 END AS "$f114"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES0"
INNER JOIN "tpcds"."ITEM" AS "ITEM4" ON "WEB_SALES0"."WS_ITEM_SK" = "ITEM4"."I_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" AS "DATE_DIM4" ON "WEB_SALES0"."WS_SOLD_DATE_SK" = "DATE_DIM4"."D_DATE_SK"
LEFT JOIN "tpcds"."WEB_RETURNS" AS "WEB_RETURNS0" ON "WEB_SALES0"."WS_ORDER_NUMBER" = "WEB_RETURNS0"."WR_ORDER_NUMBER" AND "WEB_SALES0"."WS_ITEM_SK" = "WEB_RETURNS0"."WR_ITEM_SK"
WHERE "ITEM4"."I_CATEGORY" = 'distmember(categories,61,1)') AS "t15"
GROUP BY "D_YEAR0", "I_BRAND_ID0", "I_CLASS_ID0", "I_CATEGORY_ID0", "I_MANUFACT_ID0") AS "t16"
WHERE "t7"."I_BRAND_ID0" = "t16"."I_BRAND_ID0" AND ("t7"."I_CLASS_ID0" = "t16"."I_CLASS_ID0" AND "t7"."I_CATEGORY_ID0" = "t16"."I_CATEGORY_ID0") AND ("t7"."I_MANUFACT_ID0" = "t16"."I_MANUFACT_ID0" AND "t7"."D_YEAR0" = 2002 AND ("t16"."D_YEAR0" = 2002 - 1 AND CAST("t7"."$f5" AS DECIMAL(17, 2)) / CAST("t16"."$f5" AS DECIMAL(17, 2)) < 0.900000))
ORDER BY 9
FETCH NEXT 100 ROWS ONLY) AS "t19"
