SELECT "$f6" AS "CHANNEL", "S_STORE_SK01" AS "ID", SUM("$f11") AS "SALES", SUM("$f9") AS "RETS", SUM("$f12") AS "PROFIT"
FROM (SELECT *
FROM (SELECT 'store channel' AS "$f6", "t1"."S_STORE_SK0" AS "S_STORE_SK01", "t1"."$f1" AS "$f11", CASE WHEN "t4"."$f1" IS NOT NULL THEN CAST("t4"."$f1" AS DECIMAL(12, 2)) ELSE 0.00 END AS "$f9", "t1"."$f2" - CASE WHEN "t4"."$f2" IS NOT NULL THEN CAST("t4"."$f2" AS DECIMAL(12, 2)) ELSE 0.00 END AS "$f12"
FROM (SELECT "STORE"."S_STORE_SK" AS "S_STORE_SK0", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f1", SUM("STORE_SALES"."SS_NET_PROFIT") AS "$f2"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_DATE" >= DATE '2000-08-23' AND "DATE_DIM"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days') AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK"
GROUP BY "STORE"."S_STORE_SK") AS "t1"
LEFT JOIN (SELECT "STORE0"."S_STORE_SK" AS "S_STORE_SK0", SUM("STORE_RETURNS"."SR_RETURN_AMT") AS "$f1", SUM("STORE_RETURNS"."SR_NET_LOSS") AS "$f2"
FROM "tpcds"."STORE_RETURNS",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."STORE" AS "STORE0"
WHERE "STORE_RETURNS"."SR_RETURNED_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_DATE" >= DATE '2000-08-23' AND "DATE_DIM0"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days') AND "STORE_RETURNS"."SR_STORE_SK" = "STORE0"."S_STORE_SK"
GROUP BY "STORE0"."S_STORE_SK") AS "t4" ON "t1"."S_STORE_SK0" = "t4"."S_STORE_SK0"
UNION ALL
SELECT 'catalog channel' AS "$f5", "t8"."CS_CALL_CENTER_SK0" AS "CS_CALL_CENTER_SK00", "t8"."$f1" AS "$f11", CAST("t11"."$f0" AS DECIMAL(12, 2)) AS "$f00", CAST("t8"."$f2" - "t11"."$f1" AS DECIMAL(13, 2)) AS "$f9"
FROM (SELECT "CATALOG_SALES"."CS_CALL_CENTER_SK" AS "CS_CALL_CENTER_SK0", SUM("CATALOG_SALES"."CS_EXT_SALES_PRICE") AS "$f1", SUM("CATALOG_SALES"."CS_NET_PROFIT") AS "$f2"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM1"
WHERE "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "DATE_DIM1"."D_DATE" >= DATE '2000-08-23' AND "DATE_DIM1"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days')
GROUP BY "CATALOG_SALES"."CS_CALL_CENTER_SK") AS "t8",
(SELECT SUM("CATALOG_RETURNS"."CR_RETURN_AMOUNT") AS "$f0", SUM("CATALOG_RETURNS"."CR_NET_LOSS") AS "$f1"
FROM "tpcds"."CATALOG_RETURNS",
"tpcds"."DATE_DIM" AS "DATE_DIM2"
WHERE "CATALOG_RETURNS"."CR_RETURNED_DATE_SK" = "DATE_DIM2"."D_DATE_SK" AND "DATE_DIM2"."D_DATE" >= DATE '2000-08-23' AND "DATE_DIM2"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days')) AS "t11")
UNION ALL
SELECT 'web channel' AS "$f6", "t16"."WP_WEB_PAGE_SK0" AS "WP_WEB_PAGE_SK01", "t16"."$f1" AS "$f11", CASE WHEN "t19"."$f1" IS NOT NULL THEN CAST("t19"."$f1" AS DECIMAL(12, 2)) ELSE 0.00 END AS "$f9", "t16"."$f2" - CASE WHEN "t19"."$f2" IS NOT NULL THEN CAST("t19"."$f2" AS DECIMAL(12, 2)) ELSE 0.00 END AS "$f12"
FROM (SELECT "WEB_PAGE"."WP_WEB_PAGE_SK" AS "WP_WEB_PAGE_SK0", SUM("WEB_SALES"."WS_EXT_SALES_PRICE") AS "$f1", SUM("WEB_SALES"."WS_NET_PROFIT") AS "$f2"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM3",
"tpcds"."WEB_PAGE"
WHERE "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM3"."D_DATE_SK" AND "DATE_DIM3"."D_DATE" >= DATE '2000-08-23' AND "DATE_DIM3"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days') AND "WEB_SALES"."WS_WEB_PAGE_SK" = "WEB_PAGE"."WP_WEB_PAGE_SK"
GROUP BY "WEB_PAGE"."WP_WEB_PAGE_SK") AS "t16"
LEFT JOIN (SELECT "WEB_PAGE0"."WP_WEB_PAGE_SK" AS "WP_WEB_PAGE_SK0", SUM("WEB_RETURNS"."WR_RETURN_AMT") AS "$f1", SUM("WEB_RETURNS"."WR_NET_LOSS") AS "$f2"
FROM "tpcds"."WEB_RETURNS",
"tpcds"."DATE_DIM" AS "DATE_DIM4",
"tpcds"."WEB_PAGE" AS "WEB_PAGE0"
WHERE "WEB_RETURNS"."WR_RETURNED_DATE_SK" = "DATE_DIM4"."D_DATE_SK" AND "DATE_DIM4"."D_DATE" >= DATE '2000-08-23' AND "DATE_DIM4"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days') AND "WEB_RETURNS"."WR_WEB_PAGE_SK" = "WEB_PAGE0"."WP_WEB_PAGE_SK"
GROUP BY "WEB_PAGE0"."WP_WEB_PAGE_SK") AS "t19" ON "t16"."WP_WEB_PAGE_SK0" = "t19"."WP_WEB_PAGE_SK0") AS "t21"
GROUP BY ROLLUP("$f6", "S_STORE_SK01")
ORDER BY "$f6", "S_STORE_SK01"
FETCH NEXT 100 ROWS ONLY
