SELECT "t10"."SS_CUSTOMER_SK00" AS "SS_CUSTOMER_SK", "t10"."$f19" AS "RATIO", "t10"."$f32" AS "STORE_QTY", "t10"."$f42" AS "STORE_WHOLESALE_COST", "t10"."$f52" AS "STORE_SALES_PRICE", "t10"."$f23" AS "OTHER_CHAN_QTY", "t10"."$f24" AS "OTHER_CHAN_WHOLESALE_COST", "t10"."$f25" AS "OTHER_CHAN_SALES_PRICE"
FROM (SELECT "t1"."SS_CUSTOMER_SK0" AS "SS_CUSTOMER_SK00", ROUND("t1"."$f3" / CASE WHEN "t4"."$f3" IS NOT NULL AND "t7"."$f3" IS NOT NULL THEN CAST("t4"."$f3" + "t7"."$f3" AS INTEGER) ELSE 1 END, 2) AS "$f19", "t1"."$f3" AS "$f32", "t1"."$f4" AS "$f42", "t1"."$f5" AS "$f52", CASE WHEN "t4"."$f3" IS NOT NULL THEN CAST("t4"."$f3" AS INTEGER) ELSE 0 END + CASE WHEN "t7"."$f3" IS NOT NULL THEN CAST("t7"."$f3" AS INTEGER) ELSE 0 END AS "$f23", CASE WHEN "t4"."$f4" IS NOT NULL THEN CAST("t4"."$f4" AS DECIMAL(12, 2)) ELSE 0.00 END + CASE WHEN "t7"."$f4" IS NOT NULL THEN CAST("t7"."$f4" AS DECIMAL(12, 2)) ELSE 0.00 END AS "$f24", CASE WHEN "t4"."$f5" IS NOT NULL THEN CAST("t4"."$f5" AS DECIMAL(12, 2)) ELSE 0.00 END + CASE WHEN "t7"."$f5" IS NOT NULL THEN CAST("t7"."$f5" AS DECIMAL(12, 2)) ELSE 0.00 END AS "$f25"
FROM (SELECT "DATE_DIM"."D_YEAR" AS "D_YEAR0", "STORE_SALES"."SS_ITEM_SK" AS "SS_ITEM_SK0", "STORE_SALES"."SS_CUSTOMER_SK" AS "SS_CUSTOMER_SK0", SUM("STORE_SALES"."SS_QUANTITY") AS "$f3", SUM("STORE_SALES"."SS_WHOLESALE_COST") AS "$f4", SUM("STORE_SALES"."SS_SALES_PRICE") AS "$f5"
FROM "tpcds"."STORE_SALES"
LEFT JOIN "tpcds"."STORE_RETURNS" ON "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER" AND "STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" ON "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK"
WHERE "STORE_RETURNS"."SR_TICKET_NUMBER" IS NULL
GROUP BY "DATE_DIM"."D_YEAR", "STORE_SALES"."SS_ITEM_SK", "STORE_SALES"."SS_CUSTOMER_SK") AS "t1"
LEFT JOIN (SELECT "DATE_DIM0"."D_YEAR" AS "D_YEAR0", "WEB_SALES"."WS_ITEM_SK" AS "WS_ITEM_SK0", "WEB_SALES"."WS_BILL_CUSTOMER_SK" AS "WS_BILL_CUSTOMER_SK0", SUM("WEB_SALES"."WS_QUANTITY") AS "$f3", SUM("WEB_SALES"."WS_WHOLESALE_COST") AS "$f4", SUM("WEB_SALES"."WS_SALES_PRICE") AS "$f5"
FROM "tpcds"."WEB_SALES"
LEFT JOIN "tpcds"."WEB_RETURNS" ON "WEB_SALES"."WS_ORDER_NUMBER" = "WEB_RETURNS"."WR_ORDER_NUMBER" AND "WEB_SALES"."WS_ITEM_SK" = "WEB_RETURNS"."WR_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" AS "DATE_DIM0" ON "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK"
WHERE "WEB_RETURNS"."WR_ORDER_NUMBER" IS NULL
GROUP BY "DATE_DIM0"."D_YEAR", "WEB_SALES"."WS_ITEM_SK", "WEB_SALES"."WS_BILL_CUSTOMER_SK") AS "t4" ON "t1"."D_YEAR0" = "t4"."D_YEAR0" AND "t1"."SS_ITEM_SK0" = "t4"."WS_ITEM_SK0" AND "t1"."SS_CUSTOMER_SK0" = "t4"."WS_BILL_CUSTOMER_SK0"
LEFT JOIN (SELECT "DATE_DIM1"."D_YEAR" AS "D_YEAR0", "CATALOG_SALES"."CS_ITEM_SK" AS "CS_ITEM_SK0", "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" AS "CS_BILL_CUSTOMER_SK0", SUM("CATALOG_SALES"."CS_QUANTITY") AS "$f3", SUM("CATALOG_SALES"."CS_WHOLESALE_COST") AS "$f4", SUM("CATALOG_SALES"."CS_SALES_PRICE") AS "$f5"
FROM "tpcds"."CATALOG_SALES"
LEFT JOIN "tpcds"."CATALOG_RETURNS" ON "CATALOG_SALES"."CS_ORDER_NUMBER" = "CATALOG_RETURNS"."CR_ORDER_NUMBER" AND "CATALOG_SALES"."CS_ITEM_SK" = "CATALOG_RETURNS"."CR_ITEM_SK"
INNER JOIN "tpcds"."DATE_DIM" AS "DATE_DIM1" ON "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK"
WHERE "CATALOG_RETURNS"."CR_ORDER_NUMBER" IS NULL
GROUP BY "DATE_DIM1"."D_YEAR", "CATALOG_SALES"."CS_ITEM_SK", "CATALOG_SALES"."CS_BILL_CUSTOMER_SK") AS "t7" ON "t1"."D_YEAR0" = "t7"."D_YEAR0" AND "t1"."SS_CUSTOMER_SK0" = "t7"."CS_BILL_CUSTOMER_SK0"
WHERE CASE WHEN "t4"."$f3" IS NOT NULL THEN CAST("t4"."$f3" AS INTEGER) ELSE 0 END > 0 AND CASE WHEN "t7"."$f3" IS NOT NULL THEN CAST("t7"."$f3" AS INTEGER) ELSE 0 END > 0 AND "t1"."D_YEAR0" = 1998
ORDER BY "t1"."SS_CUSTOMER_SK0", "t1"."$f3" DESC, "t1"."$f4" DESC, "t1"."$f5" DESC, 6, 7, 8, 2
FETCH NEXT 100 ROWS ONLY) AS "t10"
