SELECT "t5"."C_LAST_NAME0" AS "C_LAST_NAME", "t5"."C_FIRST_NAME0" AS "C_FIRST_NAME", "t5"."$f25", "t5"."SS_TICKET_NUMBER000" AS "SS_TICKET_NUMBER", "t5"."$f400" AS "AMT", "t5"."$f500" AS "PROFIT"
FROM (SELECT "CUSTOMER"."C_LAST_NAME" AS "C_LAST_NAME0", "CUSTOMER"."C_FIRST_NAME" AS "C_FIRST_NAME0", SUBSTRING("t2"."S_CITY00", 1, 30) AS "$f25", "t2"."SS_TICKET_NUMBER00" AS "SS_TICKET_NUMBER000", "t2"."$f40" AS "$f400", "t2"."$f50" AS "$f500"
FROM (SELECT "STORE_SALES"."SS_TICKET_NUMBER" AS "SS_TICKET_NUMBER00", "STORE_SALES"."SS_CUSTOMER_SK" AS "SS_CUSTOMER_SK00", "STORE"."S_CITY" AS "S_CITY00", SUM("STORE_SALES"."SS_COUPON_AMT") AS "$f40", SUM("STORE_SALES"."SS_NET_PROFIT") AS "$f50"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND "STORE_SALES"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK") AND (("HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" = 0 OR "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" > 0) AND "DATE_DIM"."D_DOW" = 1 AND (("DATE_DIM"."D_YEAR" = 1999 OR "DATE_DIM"."D_YEAR" = 1999 + 1 OR "DATE_DIM"."D_YEAR" = 1999 + 2) AND ("STORE"."S_NUMBER_EMPLOYEES" >= 200 AND "STORE"."S_NUMBER_EMPLOYEES" <= 295)))
GROUP BY "STORE_SALES"."SS_TICKET_NUMBER", "STORE_SALES"."SS_CUSTOMER_SK", "STORE_SALES"."SS_ADDR_SK", "STORE"."S_CITY") AS "t2",
"tpcds"."CUSTOMER"
WHERE "t2"."SS_CUSTOMER_SK00" = "CUSTOMER"."C_CUSTOMER_SK"
ORDER BY "CUSTOMER"."C_LAST_NAME", "CUSTOMER"."C_FIRST_NAME", 3, "t2"."$f50"
FETCH NEXT 100 ROWS ONLY) AS "t5"
