SELECT "$f4" AS "CHANNEL", "$f5" AS "ID", SUM("$f10") AS "SALES", SUM("$f20") AS "RETS", SUM("$f30") AS "PROFIT"
FROM (SELECT *
FROM (SELECT 'store channel' AS "$f4", CAST('store' || CAST("STORE"."S_STORE_ID" AS VARCHAR(16)) AS VARCHAR(28)) AS "$f5", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f10", SUM(CASE WHEN "STORE_RETURNS"."SR_RETURN_AMT" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_RETURN_AMT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS "$f20", SUM("STORE_SALES"."SS_NET_PROFIT" - CASE WHEN "STORE_RETURNS"."SR_NET_LOSS" IS NOT NULL THEN CAST("STORE_RETURNS"."SR_NET_LOSS" AS DECIMAL(12, 2)) ELSE 0.00 END) AS "$f30"
FROM "tpcds"."STORE_SALES"
LEFT JOIN "tpcds"."STORE_RETURNS" ON "STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK" AND "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER"
CROSS JOIN "tpcds"."DATE_DIM"
CROSS JOIN "tpcds"."STORE"
CROSS JOIN "tpcds"."ITEM"
CROSS JOIN "tpcds"."PROMOTION"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_DATE" >= DATE '2000-08-23' AND ("DATE_DIM"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days') AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK") AND ("STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) > 50.00 AND ("STORE_SALES"."SS_PROMO_SK" = "PROMOTION"."P_PROMO_SK" AND "PROMOTION"."P_CHANNEL_TV" = 'N'))
GROUP BY "STORE"."S_STORE_ID"
UNION ALL
SELECT 'catalog channel' AS "$f4", CAST('catalog_page' || CAST("CATALOG_PAGE"."CP_CATALOG_PAGE_ID" AS VARCHAR(16)) AS VARCHAR(28)) AS "$f5", SUM("CATALOG_SALES"."CS_EXT_SALES_PRICE") AS "$f10", SUM(CASE WHEN "CATALOG_RETURNS"."CR_RETURN_AMOUNT" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_RETURN_AMOUNT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS "$f20", SUM("CATALOG_SALES"."CS_NET_PROFIT" - CASE WHEN "CATALOG_RETURNS"."CR_NET_LOSS" IS NOT NULL THEN CAST("CATALOG_RETURNS"."CR_NET_LOSS" AS DECIMAL(12, 2)) ELSE 0.00 END) AS "$f30"
FROM "tpcds"."CATALOG_SALES"
LEFT JOIN "tpcds"."CATALOG_RETURNS" ON "CATALOG_SALES"."CS_ITEM_SK" = "CATALOG_RETURNS"."CR_ITEM_SK" AND "CATALOG_SALES"."CS_ORDER_NUMBER" = "CATALOG_RETURNS"."CR_ORDER_NUMBER"
CROSS JOIN "tpcds"."DATE_DIM" AS "DATE_DIM0"
CROSS JOIN "tpcds"."CATALOG_PAGE"
CROSS JOIN "tpcds"."ITEM" AS "ITEM0"
CROSS JOIN "tpcds"."PROMOTION" AS "PROMOTION0"
WHERE "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_DATE" >= DATE '2000-08-23' AND ("DATE_DIM0"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days') AND "CATALOG_SALES"."CS_CATALOG_PAGE_SK" = "CATALOG_PAGE"."CP_CATALOG_PAGE_SK") AND ("CATALOG_SALES"."CS_ITEM_SK" = "ITEM0"."I_ITEM_SK" AND CAST("ITEM0"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) > 50.00 AND ("CATALOG_SALES"."CS_PROMO_SK" = "PROMOTION0"."P_PROMO_SK" AND "PROMOTION0"."P_CHANNEL_TV" = 'N'))
GROUP BY "CATALOG_PAGE"."CP_CATALOG_PAGE_ID")
UNION ALL
SELECT 'web channel' AS "$f4", CAST('web_site' || CAST("WEB_SITE"."WEB_SITE_ID" AS VARCHAR(16)) AS VARCHAR(28)) AS "$f5", SUM("WEB_SALES"."WS_EXT_SALES_PRICE") AS "$f10", SUM(CASE WHEN "WEB_RETURNS"."WR_RETURN_AMT" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_RETURN_AMT" AS DECIMAL(12, 2)) ELSE 0.00 END) AS "$f20", SUM("WEB_SALES"."WS_NET_PROFIT" - CASE WHEN "WEB_RETURNS"."WR_NET_LOSS" IS NOT NULL THEN CAST("WEB_RETURNS"."WR_NET_LOSS" AS DECIMAL(12, 2)) ELSE 0.00 END) AS "$f30"
FROM "tpcds"."WEB_SALES"
LEFT JOIN "tpcds"."WEB_RETURNS" ON "WEB_SALES"."WS_ITEM_SK" = "WEB_RETURNS"."WR_ITEM_SK" AND "WEB_SALES"."WS_ORDER_NUMBER" = "WEB_RETURNS"."WR_ORDER_NUMBER"
CROSS JOIN "tpcds"."DATE_DIM" AS "DATE_DIM1"
CROSS JOIN "tpcds"."WEB_SITE"
CROSS JOIN "tpcds"."ITEM" AS "ITEM1"
CROSS JOIN "tpcds"."PROMOTION" AS "PROMOTION1"
WHERE "WEB_SALES"."WS_SOLD_DATE_SK" = "DATE_DIM1"."D_DATE_SK" AND "DATE_DIM1"."D_DATE" >= DATE '2000-08-23' AND ("DATE_DIM1"."D_DATE" <= (DATE '2000-08-23' + INTERVAL '30 days') AND "WEB_SALES"."WS_WEB_SITE_SK" = "WEB_SITE"."WEB_SITE_SK") AND ("WEB_SALES"."WS_ITEM_SK" = "ITEM1"."I_ITEM_SK" AND CAST("ITEM1"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) > 50.00 AND ("WEB_SALES"."WS_PROMO_SK" = "PROMOTION1"."P_PROMO_SK" AND "PROMOTION1"."P_CHANNEL_TV" = 'N'))
GROUP BY "WEB_SITE"."WEB_SITE_ID") AS "t12"
GROUP BY ROLLUP("$f4", "$f5")
ORDER BY "$f4", "$f5"
FETCH NEXT 100 ROWS ONLY
