SELECT "CUSTOMER"."C_CUSTOMER_ID", "CUSTOMER"."C_SALUTATION", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_LAST_NAME", "CUSTOMER_ADDRESS0"."CA_STREET_NUMBER", "CUSTOMER_ADDRESS0"."CA_STREET_NAME", "CUSTOMER_ADDRESS0"."CA_STREET_TYPE", "CUSTOMER_ADDRESS0"."CA_SUITE_NUMBER", "CUSTOMER_ADDRESS0"."CA_CITY", "CUSTOMER_ADDRESS0"."CA_COUNTY", "CUSTOMER_ADDRESS0"."CA_STATE", "CUSTOMER_ADDRESS0"."CA_ZIP", "CUSTOMER_ADDRESS0"."CA_COUNTRY", "CUSTOMER_ADDRESS0"."CA_GMT_OFFSET", "CUSTOMER_ADDRESS0"."CA_LOCATION_TYPE", "t1"."$f2" AS "CTR_TOTAL_RETURN"
FROM (SELECT "CATALOG_RETURNS"."CR_RETURNING_CUSTOMER_SK" AS "CR_RETURNING_CUSTOMER_SK0", "CUSTOMER_ADDRESS"."CA_STATE" AS "CA_STATE0", SUM("CATALOG_RETURNS"."CR_RETURN_AMT_INC_TAX") AS "$f2"
FROM "tpcds"."CATALOG_RETURNS",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER_ADDRESS"
WHERE "CATALOG_RETURNS"."CR_RETURNED_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_YEAR" = 1998 AND "CATALOG_RETURNS"."CR_RETURNING_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK"
GROUP BY "CATALOG_RETURNS"."CR_RETURNING_CUSTOMER_SK", "CUSTOMER_ADDRESS"."CA_STATE") AS "t1",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS0",
"tpcds"."CUSTOMER"
WHERE CAST("t1"."$f2" AS DECIMAL(9, 3)) > (((SELECT AVG(SUM("CATALOG_RETURNS0"."CR_RETURN_AMT_INC_TAX")) * 1.2 AS "$f1"
FROM "tpcds"."CATALOG_RETURNS" AS "CATALOG_RETURNS0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."CUSTOMER_ADDRESS" AS "CUSTOMER_ADDRESS1"
WHERE "CATALOG_RETURNS0"."CR_RETURNED_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_YEAR" = 1998 AND "CATALOG_RETURNS0"."CR_RETURNING_ADDR_SK" = "CUSTOMER_ADDRESS1"."CA_ADDRESS_SK"
GROUP BY "CATALOG_RETURNS0"."CR_RETURNING_CUSTOMER_SK", "CUSTOMER_ADDRESS1"."CA_STATE"
HAVING "t1"."CA_STATE0" = "CUSTOMER_ADDRESS1"."CA_STATE"))) AND "CUSTOMER_ADDRESS0"."CA_ADDRESS_SK" = "CUSTOMER"."C_CURRENT_ADDR_SK" AND "CUSTOMER_ADDRESS0"."CA_STATE" = 'dist(fips_county, 3, 1)' AND "t1"."CR_RETURNING_CUSTOMER_SK0" = "CUSTOMER"."C_CUSTOMER_SK"
ORDER BY "CUSTOMER"."C_CUSTOMER_ID", "CUSTOMER"."C_SALUTATION", "CUSTOMER"."C_FIRST_NAME", "CUSTOMER"."C_LAST_NAME", "CUSTOMER_ADDRESS0"."CA_STREET_NUMBER", "CUSTOMER_ADDRESS0"."CA_STREET_NAME", "CUSTOMER_ADDRESS0"."CA_STREET_TYPE", "CUSTOMER_ADDRESS0"."CA_SUITE_NUMBER", "CUSTOMER_ADDRESS0"."CA_CITY", "CUSTOMER_ADDRESS0"."CA_COUNTY", "CUSTOMER_ADDRESS0"."CA_STATE", "CUSTOMER_ADDRESS0"."CA_ZIP", "CUSTOMER_ADDRESS0"."CA_COUNTRY", "CUSTOMER_ADDRESS0"."CA_GMT_OFFSET", "CUSTOMER_ADDRESS0"."CA_LOCATION_TYPE", "t1"."$f2"
FETCH NEXT 100 ROWS ONLY
