SELECT "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "ITEM"."I_CURRENT_PRICE"
FROM "tpcds"."ITEM",
"tpcds"."INVENTORY",
"tpcds"."DATE_DIM",
"tpcds"."STORE_SALES"
WHERE CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) >= 44.00 AND CAST("ITEM"."I_CURRENT_PRICE" AS DECIMAL(12, 2)) <= CAST(44 + 30 AS DECIMAL(12, 2)) AND ("INVENTORY"."INV_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "DATE_DIM"."D_DATE_SK" = "INVENTORY"."INV_DATE_SK") AND ("DATE_DIM"."D_DATE" >= DATE '2000-05-25' AND "DATE_DIM"."D_DATE" <= (DATE '2000-05-25' + INTERVAL '60 days') AND ("ITEM"."I_MANUFACT_ID" IN (129, 270, 423, 821) AND ("INVENTORY"."INV_QUANTITY_ON_HAND" >= 100 AND "INVENTORY"."INV_QUANTITY_ON_HAND" <= 500 AND "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK")))
GROUP BY "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "ITEM"."I_CURRENT_PRICE"
ORDER BY "ITEM"."I_ITEM_ID"
FETCH NEXT 100 ROWS ONLY
