SELECT "CUSTOMER"."C_CUSTOMER_ID" AS "CUSTOMER_ID", CAST(CAST("CUSTOMER"."C_LAST_NAME" AS VARCHAR(30)) || ', ' AS VARCHAR(32)) || CAST("CUSTOMER"."C_FIRST_NAME" AS VARCHAR(32)) AS "CUSTOMERNAME"
FROM "tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."CUSTOMER_DEMOGRAPHICS",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS",
"tpcds"."INCOME_BAND",
"tpcds"."STORE_RETURNS"
WHERE "CUSTOMER_ADDRESS"."CA_CITY" = 'dist(cities, 1, large)' AND "CUSTOMER"."C_CURRENT_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK" AND ("INCOME_BAND"."IB_LOWER_BOUND" >= 38936 AND "INCOME_BAND"."IB_UPPER_BOUND" <= 38936 + 50000) AND ("INCOME_BAND"."IB_INCOME_BAND_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_INCOME_BAND_SK" AND "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" = "CUSTOMER"."C_CURRENT_CDEMO_SK" AND ("HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" = "CUSTOMER"."C_CURRENT_HDEMO_SK" AND "STORE_RETURNS"."SR_CDEMO_SK" = "CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK"))
ORDER BY "CUSTOMER"."C_CUSTOMER_ID"
FETCH NEXT 100 ROWS ONLY
