SELECT "$f200" AS "TOTAL_SUM", "I_CATEGORY000" AS "I_CATEGORY", "I_CLASS000" AS "I_CLASS", "$f80" AS "LOCHIERARCHY", "$f10" AS "RANK_WITHIN_PARENT"
FROM (SELECT "$f20" AS "$f200", "I_CATEGORY00" AS "I_CATEGORY000", "I_CLASS00" AS "I_CLASS000", "$f8" AS "$f80", RANK() OVER (PARTITION BY "$f8", CASE WHEN "$f7" = 0 THEN "I_CATEGORY00" ELSE NULL END ORDER BY "$f20" DESC) AS "$f10", CASE WHEN "$f8" = 0 THEN "I_CATEGORY00" ELSE NULL END AS "$f11"
FROM (SELECT *
FROM (SELECT SUM("WEB_SALES"."WS_NET_PAID") AS "$f20", "ITEM"."I_CATEGORY" AS "I_CATEGORY00", "ITEM"."I_CLASS" AS "I_CLASS00", 0 AS "$f6", 0 AS "$f7", 0 AS "$f8"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM",
"tpcds"."ITEM"
WHERE "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM"."D_DATE_SK" = "WEB_SALES"."WS_SOLD_DATE_SK" AND "ITEM"."I_ITEM_SK" = "WEB_SALES"."WS_ITEM_SK"
GROUP BY "ITEM"."I_CATEGORY", "ITEM"."I_CLASS"
UNION
SELECT SUM("t6"."$f20") AS "$f10", "t6"."I_CATEGORY00" AS "I_CATEGORY000", CAST(NULL AS CHAR(50)) AS "$f4", 0 AS "$f5", 1 AS "$f6", 1 AS "$f7"
FROM (SELECT "ITEM0"."I_CATEGORY" AS "I_CATEGORY00", SUM("WEB_SALES0"."WS_NET_PAID") AS "$f20"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0",
"tpcds"."ITEM" AS "ITEM0"
WHERE "DATE_DIM0"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM0"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM0"."D_DATE_SK" = "WEB_SALES0"."WS_SOLD_DATE_SK" AND "ITEM0"."I_ITEM_SK" = "WEB_SALES0"."WS_ITEM_SK"
GROUP BY "ITEM0"."I_CATEGORY", "ITEM0"."I_CLASS") AS "t6"
GROUP BY "t6"."I_CATEGORY00")
UNION
SELECT SUM(SUM("WEB_SALES1"."WS_NET_PAID")) AS "$f00", CAST(NULL AS CHAR(50)) AS "$f2", CAST(NULL AS CHAR(50)) AS "$f3", 1 AS "$f4", 1 AS "$f5", 2 AS "$f6"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES1",
"tpcds"."DATE_DIM" AS "DATE_DIM1",
"tpcds"."ITEM" AS "ITEM1"
WHERE "DATE_DIM1"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM1"."D_MONTH_SEQ" <= 1220 + 11 AND "DATE_DIM1"."D_DATE_SK" = "WEB_SALES1"."WS_SOLD_DATE_SK" AND "ITEM1"."I_ITEM_SK" = "WEB_SALES1"."WS_ITEM_SK"
GROUP BY "ITEM1"."I_CATEGORY", "ITEM1"."I_CLASS") AS "t16"
ORDER BY "$f8" DESC, 6, 5
FETCH NEXT 100 ROWS ONLY) AS "t18"
