SELECT "t0"."$f0" AS "H8_30_TO_9", "t2"."$f0" AS "H9_TO_9_30", "t4"."$f0" AS "H9_30_TO_10", "t6"."$f0" AS "H10_TO_10_30", "t8"."$f0" AS "H10_30_TO_11", "t10"."$f0" AS "H11_TO_11_30", "t12"."$f0" AS "H11_30_TO_12", "t14"."$f0" AS "H12_TO_12_30"
FROM (SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS",
"tpcds"."TIME_DIM",
"tpcds"."STORE"
WHERE "STORE_SALES"."SS_SOLD_TIME_SK" = "TIME_DIM"."T_TIME_SK" AND ("STORE_SALES"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK") AND ("TIME_DIM"."T_HOUR" = 8 AND "TIME_DIM"."T_MINUTE" >= 30 AND (("HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS"."HD_VEHICLE_COUNT" <= 2) AND "STORE"."S_STORE_NAME" = 'ese'))) AS "t0",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES0",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS0",
"tpcds"."TIME_DIM" AS "TIME_DIM0",
"tpcds"."STORE" AS "STORE0"
WHERE "STORE_SALES0"."SS_SOLD_TIME_SK" = "TIME_DIM0"."T_TIME_SK" AND ("STORE_SALES0"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS0"."HD_DEMO_SK" AND "STORE_SALES0"."SS_STORE_SK" = "STORE0"."S_STORE_SK") AND ("TIME_DIM0"."T_HOUR" = 9 AND "TIME_DIM0"."T_MINUTE" < 30 AND (("HOUSEHOLD_DEMOGRAPHICS0"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS0"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS0"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS0"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS0"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS0"."HD_VEHICLE_COUNT" <= 2) AND "STORE0"."S_STORE_NAME" = 'ese'))) AS "t2",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES1",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS1",
"tpcds"."TIME_DIM" AS "TIME_DIM1",
"tpcds"."STORE" AS "STORE1"
WHERE "STORE_SALES1"."SS_SOLD_TIME_SK" = "TIME_DIM1"."T_TIME_SK" AND ("STORE_SALES1"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS1"."HD_DEMO_SK" AND "STORE_SALES1"."SS_STORE_SK" = "STORE1"."S_STORE_SK") AND ("TIME_DIM1"."T_HOUR" = 9 AND "TIME_DIM1"."T_MINUTE" >= 30 AND (("HOUSEHOLD_DEMOGRAPHICS1"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS1"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS1"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS1"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS1"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS1"."HD_VEHICLE_COUNT" <= 2) AND "STORE1"."S_STORE_NAME" = 'ese'))) AS "t4",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES2",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS2",
"tpcds"."TIME_DIM" AS "TIME_DIM2",
"tpcds"."STORE" AS "STORE2"
WHERE "STORE_SALES2"."SS_SOLD_TIME_SK" = "TIME_DIM2"."T_TIME_SK" AND ("STORE_SALES2"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS2"."HD_DEMO_SK" AND "STORE_SALES2"."SS_STORE_SK" = "STORE2"."S_STORE_SK") AND ("TIME_DIM2"."T_HOUR" = 10 AND "TIME_DIM2"."T_MINUTE" < 30 AND (("HOUSEHOLD_DEMOGRAPHICS2"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS2"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS2"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS2"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS2"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS2"."HD_VEHICLE_COUNT" <= 2) AND "STORE2"."S_STORE_NAME" = 'ese'))) AS "t6",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES3",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS3",
"tpcds"."TIME_DIM" AS "TIME_DIM3",
"tpcds"."STORE" AS "STORE3"
WHERE "STORE_SALES3"."SS_SOLD_TIME_SK" = "TIME_DIM3"."T_TIME_SK" AND ("STORE_SALES3"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS3"."HD_DEMO_SK" AND "STORE_SALES3"."SS_STORE_SK" = "STORE3"."S_STORE_SK") AND ("TIME_DIM3"."T_HOUR" = 10 AND "TIME_DIM3"."T_MINUTE" >= 30 AND (("HOUSEHOLD_DEMOGRAPHICS3"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS3"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS3"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS3"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS3"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS3"."HD_VEHICLE_COUNT" <= 2) AND "STORE3"."S_STORE_NAME" = 'ese'))) AS "t8",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES4",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS4",
"tpcds"."TIME_DIM" AS "TIME_DIM4",
"tpcds"."STORE" AS "STORE4"
WHERE "STORE_SALES4"."SS_SOLD_TIME_SK" = "TIME_DIM4"."T_TIME_SK" AND ("STORE_SALES4"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS4"."HD_DEMO_SK" AND "STORE_SALES4"."SS_STORE_SK" = "STORE4"."S_STORE_SK") AND ("TIME_DIM4"."T_HOUR" = 11 AND "TIME_DIM4"."T_MINUTE" < 30 AND (("HOUSEHOLD_DEMOGRAPHICS4"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS4"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS4"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS4"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS4"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS4"."HD_VEHICLE_COUNT" <= 2) AND "STORE4"."S_STORE_NAME" = 'ese'))) AS "t10",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES5",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS5",
"tpcds"."TIME_DIM" AS "TIME_DIM5",
"tpcds"."STORE" AS "STORE5"
WHERE "STORE_SALES5"."SS_SOLD_TIME_SK" = "TIME_DIM5"."T_TIME_SK" AND ("STORE_SALES5"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS5"."HD_DEMO_SK" AND "STORE_SALES5"."SS_STORE_SK" = "STORE5"."S_STORE_SK") AND ("TIME_DIM5"."T_HOUR" = 11 AND "TIME_DIM5"."T_MINUTE" >= 30 AND (("HOUSEHOLD_DEMOGRAPHICS5"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS5"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS5"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS5"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS5"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS5"."HD_VEHICLE_COUNT" <= 2) AND "STORE5"."S_STORE_NAME" = 'ese'))) AS "t12",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES" AS "STORE_SALES6",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS6",
"tpcds"."TIME_DIM" AS "TIME_DIM6",
"tpcds"."STORE" AS "STORE6"
WHERE "STORE_SALES6"."SS_SOLD_TIME_SK" = "TIME_DIM6"."T_TIME_SK" AND ("STORE_SALES6"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS6"."HD_DEMO_SK" AND "STORE_SALES6"."SS_STORE_SK" = "STORE6"."S_STORE_SK") AND ("TIME_DIM6"."T_HOUR" = 12 AND "TIME_DIM6"."T_MINUTE" < 30 AND (("HOUSEHOLD_DEMOGRAPHICS6"."HD_DEP_COUNT" = 4 AND "HOUSEHOLD_DEMOGRAPHICS6"."HD_VEHICLE_COUNT" <= 4 + 2 OR "HOUSEHOLD_DEMOGRAPHICS6"."HD_DEP_COUNT" = 2 AND "HOUSEHOLD_DEMOGRAPHICS6"."HD_VEHICLE_COUNT" <= 2 + 2 OR "HOUSEHOLD_DEMOGRAPHICS6"."HD_DEP_COUNT" = 0 AND "HOUSEHOLD_DEMOGRAPHICS6"."HD_VEHICLE_COUNT" <= 2) AND "STORE6"."S_STORE_NAME" = 'ese'))) AS "t14"
