SELECT "I_CATEGORY000" AS "I_CATEGORY", "I_CLASS000" AS "I_CLASS", "I_BRAND000" AS "I_BRAND", "S_STORE_NAME000" AS "S_STORE_NAME", "S_COMPANY_NAME000" AS "S_COMPANY_NAME", "D_MOY000" AS "D_MOY", "$f600" AS "SUM_SALES", "$f140" AS "AVG_MONTHLY_SALES"
FROM (SELECT "I_CATEGORY00" AS "I_CATEGORY000", "I_CLASS00" AS "I_CLASS000", "I_BRAND00" AS "I_BRAND000", "S_STORE_NAME00" AS "S_STORE_NAME000", "S_COMPANY_NAME00" AS "S_COMPANY_NAME000", "D_MOY00" AS "D_MOY000", "$f60" AS "$f600", "$f14" AS "$f140", "$f60" - "$f14" AS "$f16"
FROM (SELECT "ITEM"."I_CATEGORY" AS "I_CATEGORY00", "ITEM"."I_CLASS" AS "I_CLASS00", "ITEM"."I_BRAND" AS "I_BRAND00", "STORE"."S_STORE_NAME" AS "S_STORE_NAME00", "STORE"."S_COMPANY_NAME" AS "S_COMPANY_NAME00", "DATE_DIM"."D_MOY" AS "D_MOY00", SUM("STORE_SALES"."SS_SALES_PRICE") AS "$f60", AVG(SUM("STORE_SALES"."SS_SALES_PRICE")) OVER (PARTITION BY "ITEM"."I_CATEGORY", "ITEM"."I_BRAND", "STORE"."S_STORE_NAME", "STORE"."S_COMPANY_NAME" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "$f14"
FROM "tpcds"."ITEM",
"tpcds"."STORE_SALES",
"tpcds"."DATE_DIM",
"tpcds"."STORE"
WHERE "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK" AND "DATE_DIM"."D_YEAR" = 1998 AND (CAST("ITEM"."I_CATEGORY" AS VARCHAR(50)) IN ('distmember(categories, [IDX.1], 1)', 'distmember(categories, [IDX.2], 1)', 'distmember(categories, [IDX.3], 1)') AND CAST("ITEM"."I_CLASS" AS VARCHAR(50)) IN ('DIST(distmember(categories, [IDX.1], 2), 1, 1)', 'DIST(distmember(categories, [IDX.2], 2), 1, 1)', 'DIST(distmember(categories, [IDX.3], 2), 1, 1)') OR CAST("ITEM"."I_CATEGORY" AS VARCHAR(50)) IN ('distmember(categories, [IDX.4], 1)', 'distmember(categories, [IDX.5], 1)', 'distmember(categories, [IDX.6], 1)') AND CAST("ITEM"."I_CLASS" AS VARCHAR(50)) IN ('DIST(distmember(categories, [IDX.4], 2), 1, 1)', 'DIST(distmember(categories, [IDX.5], 2), 1, 1)', 'DIST(distmember(categories, [IDX.6], 2), 1, 1)'))
GROUP BY "ITEM"."I_CATEGORY", "ITEM"."I_CLASS", "ITEM"."I_BRAND", "STORE"."S_STORE_NAME", "STORE"."S_COMPANY_NAME", "DATE_DIM"."D_MOY") AS "t2"
WHERE CASE WHEN CAST("t2"."$f14" AS DECIMAL(12, 2)) <> 0.00 THEN ABS("t2"."$f60" - "t2"."$f14") / "t2"."$f14" ELSE NULL END > 0.100000
ORDER BY 9, "S_STORE_NAME00"
FETCH NEXT 100 ROWS ONLY) AS "t5"
