SELECT "t4"."$f2" AS "AM_PM_RATIO"
FROM (SELECT CAST("t0"."$f0" AS DECIMAL(15, 4)) / CAST("t2"."$f0" AS DECIMAL(15, 4)) AS "$f2"
FROM (SELECT COUNT(*) AS "$f0"
FROM "tpcds"."WEB_SALES",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS",
"tpcds"."TIME_DIM",
"tpcds"."WEB_PAGE"
WHERE "WEB_SALES"."WS_SOLD_TIME_SK" = "TIME_DIM"."T_TIME_SK" AND ("WEB_SALES"."WS_SHIP_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" AND "WEB_SALES"."WS_WEB_PAGE_SK" = "WEB_PAGE"."WP_WEB_PAGE_SK") AND ("TIME_DIM"."T_HOUR" >= 8 AND "TIME_DIM"."T_HOUR" <= 8 + 1 AND ("HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" = 0 AND ("WEB_PAGE"."WP_CHAR_COUNT" >= 5000 AND "WEB_PAGE"."WP_CHAR_COUNT" <= 5200)))) AS "t0",
(SELECT COUNT(*) AS "$f0"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS" AS "HOUSEHOLD_DEMOGRAPHICS0",
"tpcds"."TIME_DIM" AS "TIME_DIM0",
"tpcds"."WEB_PAGE" AS "WEB_PAGE0"
WHERE "WEB_SALES0"."WS_SOLD_TIME_SK" = "TIME_DIM0"."T_TIME_SK" AND ("WEB_SALES0"."WS_SHIP_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS0"."HD_DEMO_SK" AND "WEB_SALES0"."WS_WEB_PAGE_SK" = "WEB_PAGE0"."WP_WEB_PAGE_SK") AND ("TIME_DIM0"."T_HOUR" >= 17 AND "TIME_DIM0"."T_HOUR" <= 17 + 1 AND ("HOUSEHOLD_DEMOGRAPHICS0"."HD_DEP_COUNT" = 0 AND ("WEB_PAGE0"."WP_CHAR_COUNT" >= 5000 AND "WEB_PAGE0"."WP_CHAR_COUNT" <= 5200)))) AS "t2"
ORDER BY 1
FETCH NEXT 100 ROWS ONLY) AS "t4"
