SELECT "t3"."CC_CALL_CENTER_ID00" AS "CALL_CENTER", "t3"."CC_NAME00" AS "CALL_CENTER_NAME", "t3"."CC_MANAGER00" AS "MANAGER", "t3"."$f50" AS "RETURNS_LOSS"
FROM (SELECT "CALL_CENTER"."CC_CALL_CENTER_ID" AS "CC_CALL_CENTER_ID00", "CALL_CENTER"."CC_NAME" AS "CC_NAME00", "CALL_CENTER"."CC_MANAGER" AS "CC_MANAGER00", SUM("CATALOG_RETURNS"."CR_NET_LOSS") AS "$f50"
FROM "tpcds"."CALL_CENTER",
"tpcds"."CATALOG_RETURNS",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."CUSTOMER_DEMOGRAPHICS",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS"
WHERE "CATALOG_RETURNS"."CR_CALL_CENTER_SK" = "CALL_CENTER"."CC_CALL_CENTER_SK" AND "CATALOG_RETURNS"."CR_RETURNED_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND ("CATALOG_RETURNS"."CR_RETURNING_CUSTOMER_SK" = "CUSTOMER"."C_CUSTOMER_SK" AND ("CUSTOMER_DEMOGRAPHICS"."CD_DEMO_SK" = "CUSTOMER"."C_CURRENT_CDEMO_SK" AND "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" = "CUSTOMER"."C_CURRENT_HDEMO_SK")) AND ("CUSTOMER_ADDRESS"."CA_ADDRESS_SK" = "CUSTOMER"."C_CURRENT_ADDR_SK" AND ("DATE_DIM"."D_YEAR" = 1998 AND "DATE_DIM"."D_MOY" = 11) AND (("CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS" = 'M' AND "CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS" = 'Unknown' OR "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS" = 'W' AND "CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS" = 'Advanced Degree') AND (CAST("HOUSEHOLD_DEMOGRAPHICS"."HD_BUY_POTENTIAL" AS VARCHAR(15)) LIKE 'Unknown%' AND CAST("CUSTOMER_ADDRESS"."CA_GMT_OFFSET" AS DECIMAL(12, 2)) = -7.00)))
GROUP BY "CALL_CENTER"."CC_CALL_CENTER_ID", "CALL_CENTER"."CC_NAME", "CALL_CENTER"."CC_MANAGER", "CUSTOMER_DEMOGRAPHICS"."CD_MARITAL_STATUS", "CUSTOMER_DEMOGRAPHICS"."CD_EDUCATION_STATUS"
ORDER BY 4 DESC) AS "t3"
