SELECT "t6"."$f0" AS "EXCESS_DISCOUNT_AMOUNT"
FROM (SELECT SUM("WEB_SALES"."WS_EXT_DISCOUNT_AMT") AS "$f0"
FROM "tpcds"."WEB_SALES",
"tpcds"."ITEM",
"tpcds"."DATE_DIM"
WHERE "ITEM"."I_MANUFACT_ID" = 350 AND ("ITEM"."I_ITEM_SK" = "WEB_SALES"."WS_ITEM_SK" AND "DATE_DIM"."D_DATE" >= DATE '2000-01-27') AND ("DATE_DIM"."D_DATE" <= (DATE '2000-01-27' + INTERVAL '90 days') AND ("DATE_DIM"."D_DATE_SK" = "WEB_SALES"."WS_SOLD_DATE_SK" AND CAST("WEB_SALES"."WS_EXT_DISCOUNT_AMT" AS DECIMAL(9, 3)) > (((SELECT 1.3 * AVG("WEB_SALES0"."WS_EXT_DISCOUNT_AMT") AS "$f1"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "WEB_SALES0"."WS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND "DATE_DIM0"."D_DATE" >= DATE '2000-01-27' AND "DATE_DIM0"."D_DATE" <= (DATE '2000-01-27' + INTERVAL '90 days') AND "DATE_DIM0"."D_DATE_SK" = "WEB_SALES0"."WS_SOLD_DATE_SK")))))
ORDER BY 1
FETCH NEXT 100 ROWS ONLY) AS "t6"
