SELECT "t2"."SS_CUSTOMER_SK0" AS "SS_CUSTOMER_SK", "t2"."$f1" AS "SUMSALES"
FROM (SELECT "STORE_SALES"."SS_CUSTOMER_SK" AS "SS_CUSTOMER_SK0", SUM(CASE WHEN "STORE_RETURNS"."SR_RETURN_QUANTITY" IS NOT NULL THEN CAST("STORE_SALES"."SS_QUANTITY" - "STORE_RETURNS"."SR_RETURN_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES"."SS_SALES_PRICE" ELSE CAST(CAST("STORE_SALES"."SS_QUANTITY" AS DECIMAL(12, 2)) * "STORE_SALES"."SS_SALES_PRICE" AS DECIMAL(17, 2)) END) AS "$f1"
FROM "tpcds"."STORE_SALES"
LEFT JOIN "tpcds"."STORE_RETURNS" ON "STORE_SALES"."SS_ITEM_SK" = "STORE_RETURNS"."SR_ITEM_SK" AND "STORE_SALES"."SS_TICKET_NUMBER" = "STORE_RETURNS"."SR_TICKET_NUMBER"
CROSS JOIN "tpcds"."REASON"
WHERE "STORE_RETURNS"."SR_REASON_SK" = "REASON"."R_REASON_SK" AND "REASON"."R_REASON_DESC" = 'dist(return_reasons, 1, 1)'
GROUP BY "STORE_SALES"."SS_CUSTOMER_SK"
ORDER BY 2, "STORE_SALES"."SS_CUSTOMER_SK"
FETCH NEXT 100 ROWS ONLY) AS "t2"
