SELECT "t4"."$f0" AS "order count", "t4"."$f1" AS "total shipping cost", "t4"."$f2" AS "total net profit"
FROM (SELECT COUNT(DISTINCT "WEB_SALES"."WS_ORDER_NUMBER") AS "$f0", SUM("WEB_SALES"."WS_EXT_SHIP_COST") AS "$f1", SUM("WEB_SALES"."WS_NET_PROFIT") AS "$f2"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."WEB_SITE"
WHERE "DATE_DIM"."D_DATE" >= DATE '2001-05-01' AND "DATE_DIM"."D_DATE" <= (DATE '2001-05-01' + INTERVAL '60 days') AND ("WEB_SALES"."WS_SHIP_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "WEB_SALES"."WS_SHIP_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK") AND ("CUSTOMER_ADDRESS"."CA_STATE" = 'dist(fips_county,3,1)' AND "WEB_SALES"."WS_WEB_SITE_SK" = "WEB_SITE"."WEB_SITE_SK" AND ("WEB_SITE"."WEB_COMPANY_NAME" = 'pri' AND (EXISTS (SELECT *
FROM "tpcds"."WEB_SALES"
WHERE "WEB_SALES"."WS_ORDER_NUMBER" = "WS_ORDER_NUMBER" AND "WEB_SALES"."WS_WAREHOUSE_SK" <> "WS_WAREHOUSE_SK") AND NOT EXISTS (SELECT *
FROM "tpcds"."WEB_RETURNS"
WHERE "WEB_SALES"."WS_ORDER_NUMBER" = "WR_ORDER_NUMBER"))))
ORDER BY 1
FETCH NEXT 100 ROWS ONLY) AS "t4"
