SELECT "t8"."$f0" AS "order count", "t8"."$f1" AS "total shipping cost", "t8"."$f2" AS "total net profit"
FROM (SELECT COUNT(DISTINCT "WEB_SALES"."WS_ORDER_NUMBER") AS "$f0", SUM("WEB_SALES"."WS_EXT_SHIP_COST") AS "$f1", SUM("WEB_SALES"."WS_NET_PROFIT") AS "$f2"
FROM "tpcds"."WEB_SALES",
"tpcds"."DATE_DIM",
"tpcds"."CUSTOMER_ADDRESS",
"tpcds"."WEB_SITE"
WHERE "DATE_DIM"."D_DATE" >= DATE '2001-05-01' AND "DATE_DIM"."D_DATE" <= (DATE '2001-05-01' + INTERVAL '60 days') AND ("WEB_SALES"."WS_SHIP_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "WEB_SALES"."WS_SHIP_ADDR_SK" = "CUSTOMER_ADDRESS"."CA_ADDRESS_SK") AND ("CUSTOMER_ADDRESS"."CA_STATE" = 'dist(fips_county,3,1)' AND "WEB_SALES"."WS_WEB_SITE_SK" = "WEB_SITE"."WEB_SITE_SK" AND ("WEB_SITE"."WEB_COMPANY_NAME" = 'pri' AND ("WEB_SALES"."WS_ORDER_NUMBER" IN (SELECT "WEB_SALES0"."WS_ORDER_NUMBER" AS "WS_ORDER_NUMBER1"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES0",
"tpcds"."WEB_SALES" AS "WEB_SALES1"
WHERE "WEB_SALES0"."WS_ORDER_NUMBER" = "WEB_SALES1"."WS_ORDER_NUMBER" AND "WEB_SALES0"."WS_WAREHOUSE_SK" <> "WEB_SALES1"."WS_WAREHOUSE_SK") AND "WEB_SALES"."WS_ORDER_NUMBER" IN (SELECT "WEB_RETURNS"."WR_ORDER_NUMBER" AS "WR_ORDER_NUMBER0"
FROM "tpcds"."WEB_RETURNS",
(SELECT "WEB_SALES2"."WS_ORDER_NUMBER" AS "WS_ORDER_NUMBER1", "WEB_SALES2"."WS_WAREHOUSE_SK" AS "WS_WAREHOUSE_SK1", "WEB_SALES3"."WS_WAREHOUSE_SK" AS "WS_WAREHOUSE_SK00"
FROM "tpcds"."WEB_SALES" AS "WEB_SALES2",
"tpcds"."WEB_SALES" AS "WEB_SALES3"
WHERE "WEB_SALES2"."WS_ORDER_NUMBER" = "WEB_SALES3"."WS_ORDER_NUMBER" AND "WEB_SALES2"."WS_WAREHOUSE_SK" <> "WEB_SALES3"."WS_WAREHOUSE_SK") AS "t2"
WHERE "WEB_RETURNS"."WR_ORDER_NUMBER" = "t2"."WS_ORDER_NUMBER1"))))
ORDER BY 1
FETCH NEXT 100 ROWS ONLY) AS "t8"
