SELECT "t1"."$f0"
FROM (SELECT COUNT(*) AS "$f0"
FROM "tpcds"."STORE_SALES",
"tpcds"."HOUSEHOLD_DEMOGRAPHICS",
"tpcds"."TIME_DIM",
"tpcds"."STORE"
WHERE "STORE_SALES"."SS_SOLD_TIME_SK" = "TIME_DIM"."T_TIME_SK" AND ("STORE_SALES"."SS_HDEMO_SK" = "HOUSEHOLD_DEMOGRAPHICS"."HD_DEMO_SK" AND "STORE_SALES"."SS_STORE_SK" = "STORE"."S_STORE_SK") AND ("TIME_DIM"."T_HOUR" = 20 AND "TIME_DIM"."T_MINUTE" >= 30 AND ("HOUSEHOLD_DEMOGRAPHICS"."HD_DEP_COUNT" = 7 AND "STORE"."S_STORE_NAME" = 'ese'))
ORDER BY 1
FETCH NEXT 100 ROWS ONLY) AS "t1"
