SELECT SUM(CASE WHEN "t1"."SS_CUSTOMER_SK0" IS NOT NULL AND "t4"."CS_BILL_CUSTOMER_SK0" IS NULL THEN 1 ELSE 0 END) AS "STORE_ONLY", SUM(CASE WHEN "t1"."SS_CUSTOMER_SK0" IS NULL AND "t4"."CS_BILL_CUSTOMER_SK0" IS NOT NULL THEN 1 ELSE 0 END) AS "CATALOG_ONLY", SUM(CASE WHEN "t1"."SS_CUSTOMER_SK0" IS NOT NULL AND "t4"."CS_BILL_CUSTOMER_SK0" IS NOT NULL THEN 1 ELSE 0 END) AS "STORE_AND_CATALOG"
FROM (SELECT "STORE_SALES"."SS_CUSTOMER_SK" AS "SS_CUSTOMER_SK0", "STORE_SALES"."SS_ITEM_SK" AS "SS_ITEM_SK0"
FROM "tpcds"."STORE_SALES",
"tpcds"."DATE_DIM"
WHERE "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "STORE_SALES"."SS_CUSTOMER_SK", "STORE_SALES"."SS_ITEM_SK") AS "t1"
FULL JOIN (SELECT "CATALOG_SALES"."CS_BILL_CUSTOMER_SK" AS "CS_BILL_CUSTOMER_SK0", "CATALOG_SALES"."CS_ITEM_SK" AS "CS_ITEM_SK0"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."DATE_DIM" AS "DATE_DIM0"
WHERE "CATALOG_SALES"."CS_SOLD_DATE_SK" = "DATE_DIM0"."D_DATE_SK" AND "DATE_DIM0"."D_MONTH_SEQ" >= 1220 AND "DATE_DIM0"."D_MONTH_SEQ" <= 1220 + 11
GROUP BY "CATALOG_SALES"."CS_BILL_CUSTOMER_SK", "CATALOG_SALES"."CS_ITEM_SK") AS "t4" ON "t1"."SS_CUSTOMER_SK0" = "t4"."CS_BILL_CUSTOMER_SK0" AND "t1"."SS_ITEM_SK0" = "t4"."CS_ITEM_SK0"
FETCH NEXT 100 ROWS ONLY
