SELECT "t3"."I_ITEM_ID00" AS "I_ITEM_ID", "t3"."I_ITEM_DESC00" AS "I_ITEM_DESC", "t3"."I_CATEGORY00" AS "I_CATEGORY", "t3"."I_CLASS00" AS "I_CLASS", "t3"."I_CURRENT_PRICE00" AS "I_CURRENT_PRICE", "t3"."$f50" AS "ITEMREVENUE", "t3"."$f12" AS "REVENUERATIO"
FROM (SELECT "ITEM"."I_ITEM_ID" AS "I_ITEM_ID00", "ITEM"."I_ITEM_DESC" AS "I_ITEM_DESC00", "ITEM"."I_CATEGORY" AS "I_CATEGORY00", "ITEM"."I_CLASS" AS "I_CLASS00", "ITEM"."I_CURRENT_PRICE" AS "I_CURRENT_PRICE00", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") AS "$f50", SUM("STORE_SALES"."SS_EXT_SALES_PRICE") * 100.00 / (SUM(SUM("STORE_SALES"."SS_EXT_SALES_PRICE")) OVER (PARTITION BY "ITEM"."I_CLASS" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)) AS "$f12"
FROM "tpcds"."STORE_SALES",
"tpcds"."ITEM",
"tpcds"."DATE_DIM"
WHERE "STORE_SALES"."SS_ITEM_SK" = "ITEM"."I_ITEM_SK" AND TRIM(TRAILING ' ' FROM CAST("ITEM"."I_CATEGORY" AS VARCHAR(50))) IN ('Books', 'Home', 'Sports') AND "STORE_SALES"."SS_SOLD_DATE_SK" = "DATE_DIM"."D_DATE_SK" AND "DATE_DIM"."D_DATE" >= DATE '1999-02-22' AND "DATE_DIM"."D_DATE" <= (DATE '1999-02-22' + INTERVAL '30 days')
GROUP BY "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", "ITEM"."I_CATEGORY", "ITEM"."I_CLASS", "ITEM"."I_CURRENT_PRICE"
ORDER BY "ITEM"."I_CATEGORY", "ITEM"."I_CLASS", "ITEM"."I_ITEM_ID", "ITEM"."I_ITEM_DESC", 7) AS "t3"
