SELECT "t2"."$f113", "t2"."SM_TYPE0" AS "SM_TYPE", "t2"."CC_NAME0" AS "CC_NAME", "t2"."$f3" AS "30 days", "t2"."$f4" AS "31-60 days", "t2"."$f5" AS "61-90 days", "t2"."$f6" AS "91-120 days", "t2"."$f7" AS ">120 days"
FROM (SELECT SUBSTRING("WAREHOUSE"."W_WAREHOUSE_NAME", 1, 20) AS "$f113", "SHIP_MODE"."SM_TYPE" AS "SM_TYPE0", "CALL_CENTER"."CC_NAME" AS "CC_NAME0", SUM(CASE WHEN "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" <= 30 THEN 1 ELSE 0 END) AS "$f3", SUM(CASE WHEN "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" > 30 AND "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" <= 60 THEN 1 ELSE 0 END) AS "$f4", SUM(CASE WHEN "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" > 60 AND "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" <= 90 THEN 1 ELSE 0 END) AS "$f5", SUM(CASE WHEN "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" > 90 AND "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" <= 120 THEN 1 ELSE 0 END) AS "$f6", SUM(CASE WHEN "CATALOG_SALES"."CS_SHIP_DATE_SK" - "CATALOG_SALES"."CS_SOLD_DATE_SK" > 120 THEN 1 ELSE 0 END) AS "$f7"
FROM "tpcds"."CATALOG_SALES",
"tpcds"."WAREHOUSE",
"tpcds"."SHIP_MODE",
"tpcds"."CALL_CENTER",
"tpcds"."DATE_DIM"
WHERE "DATE_DIM"."D_MONTH_SEQ" >= 1220 AND ("DATE_DIM"."D_MONTH_SEQ" <= 1220 + 11 AND "CATALOG_SALES"."CS_SHIP_DATE_SK" = "DATE_DIM"."D_DATE_SK") AND ("CATALOG_SALES"."CS_WAREHOUSE_SK" = "WAREHOUSE"."W_WAREHOUSE_SK" AND ("CATALOG_SALES"."CS_SHIP_MODE_SK" = "SHIP_MODE"."SM_SHIP_MODE_SK" AND "CATALOG_SALES"."CS_CALL_CENTER_SK" = "CALL_CENTER"."CC_CALL_CENTER_SK"))
GROUP BY SUBSTRING("WAREHOUSE"."W_WAREHOUSE_NAME", 1, 20), "SHIP_MODE"."SM_TYPE", "CALL_CENTER"."CC_NAME"
ORDER BY 1, "SHIP_MODE"."SM_TYPE", "CALL_CENTER"."CC_NAME"
FETCH NEXT 100 ROWS ONLY) AS "t2"
